### ISSUE TITLE
`ssh: handshake failed: ssh: unable to authenticate, attempted methods [none]` when creating `proxmox_virtual_environment_file`

### ISSUE THREAD

**Issue by 1-cameron** [bpg/terraform-provider-proxmox#1005]
**Describe the bug**
When using the provider to create a `proxmox_virtual_environment_file` resource the following error is posted:

```bash
╷
│ Error: failed to open SSH client: failed to dial $PVE_NODE_IP:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

I've got a pam user on the target node with the required permissions and when using it to ssh in to the server manually there's no issue and the `sshd` logs show:

```
debug1: userauth-request for user terraform-imports service ssh-connection method keyboard-interactive [preauth]
```

I'm using the same setup in a different Proxmox cluster so a bit confused as to what's wrong in this one.

**To Reproduce**

1. Create a pam user on the Proxmox node
1. Create a `proxmox_virtual_environment_file` resource
2. Run `terraform apply`
3. See error

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
  }
}

provider "proxmox" {
  alias    = "imports"
  endpoint = var.endpoint
  username = var.username
  password = var.password
  insecure = var.insecure
}

resource "proxmox_virtual_environment_file" "file" {
  provider      = proxmox.imports
  content_type  = "snippets"
  datastore_id  = var.datastore_id
  node_name     = var.node_name
...
}
```

**Expected behavior**

The pam user can ssh in and copies the file over.

**Additional context**

- Single or clustered Proxmox: clustered
- Provider version (ideally it should be the latest version): `v0.45.1`
- Terraform version: `v1.5.7`
- OS (where you run Terraform from): Ubuntu 22.04
- Debug logs (`TF_LOG=DEBUG terraform apply`): Don't provider more detail than the error above

**Comment by 1-cameron** [comment]
Found a file under `/etc/ssh/sshd_config.d/` that disabled password auth 😶‍🌫️

**Comment by bpg** [comment]
You can use ssh agent and configure public key authentication for SSH, than won't compromise security.

**Comment by Tumetsu** [comment]
I seem to get this same error when trying to create `proxmox_virtual_environment_file`. I have ssh keys added to the agent, I can ssh regularly to my Proxmox node using my ssh keys and I can use the Terraform plugin to setup LXC containers etc. just fine. It seems that this problem at least for me occurs only with `proxmox_virtual_environment_file` though I haven't had time to investigate this further.

**Comment by bpg** [comment]
@Tumetsu if you have `ssh` `agent = true` in the provider's config, please make sure you have the agent running and keys loaded to the agent. Here is a good summary: https://github.com/bpg/terraform-provider-proxmox/issues/619#issuecomment-1760582479
