### ISSUE TITLE
Implement a safer snippet file transferring mechanism

### ISSUE THREAD

**Issue by bpg** [bpg/terraform-provider-proxmox#1008]
**Is your feature request related to a problem? Please describe.**
This is a follow up story for #1004, based on [this comment](https://github.com/bpg/terraform-provider-proxmox/pull/1004#discussion_r1478260621). 

Currently the file is uploaded to a temp folder under /tmp on a PVE host, then transferred via `sudo mv` to the target location.

**Describe the solution you'd like**
As per the comment above, use stdin redirect & sudo tee to upload the file directly to the target location. 

**Describe alternatives you've considered**
N/A

**Additional context**
Original issue: #352, regression #986

**Comment by euh2** [comment]
Possibly related:
```
│ Error: error moving file: rm: cannot remove '/tmp/tfpve/4a1ee6ad-610b-4c4b-ab1b-cf43018f3fe6/snippets/user-data.yml': No such file or directory
│
│
│   with proxmox_virtual_environment_file.cloud_config,
│   on files.tf line 9, in resource "proxmox_virtual_environment_file" "cloud_config":
│    9: resource "proxmox_virtual_environment_file" "cloud_config" {
```
files.tf
```
...
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "****"

  source_file {
    path = "cloud-init/user-data.yml"
  }
}
```
