### ISSUE TITLE
[Data Source - VMs] Ability to filter out VMs depending on other criterias

### ISSUE THREAD

**Issue by Dr-Shadow** [bpg/terraform-provider-proxmox#1010]
I suggest adding the ability to filter virtual machines (VMs) based on whether they are templates or not.

Additional criteria could also be considered for filtering.

I propose modifying the `virtual_environment_vms` data source to include other filter options.

Alternatively, exposing more information about the VMs in the returned list of this data source would allow users to filter them after retrieval.

**Comment by bpg** [comment]
Addressed in #1423
