### ISSUE TITLE
Error: error moving file: rm: cannot remove

### ISSUE THREAD

**Issue by ecanuto** [bpg/terraform-provider-proxmox#1011]
When trying to create a file using `proxmox_virtual_environment_file` we got an error:

```terraform
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.proxmox_node_name
  overwrite    = true

  source_file {
    path      = "cloudinit.yaml"
    file_name = "debian12.cloud-config.yaml"
  }
}
```

Error: error moving file: rm: cannot remove '...': No such file or directory

This happens because we are trying to remove a file that we recently moved so it don't exists anymore. We can fix it by remove `rm`, add `rm -f` or replace `rm` and `rmdir` by `rm -rf`.

https://github.com/bpg/terraform-provider-proxmox/blame/46d09f7e980fa9a981b81000fa4bdffc823558fc/proxmoxtf/resource/file.go#L596

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm %s/%s && rmdir -p %s`,
				trySudo,
				srcDir, *fileName,
				dstDir, *fileName,
				srcDir, *fileName,
				srcDir,
			),
```

Possible solutions snippets:

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir -p %s`,
				...
			),
```

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm -f %s/%s && rmdir -p %s`,
				...
			),
```

```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rm -rf %s`,
				trySudo,
				srcDir, *fileName,
				srcDir, *fileName,
				srcDir,
			),
```

**Comment by euh2** [comment]
Anyone has an idea how to work around this until this is fixed? I'm trying to get cloud-init integrated. This requires `snippets`, I think.

**Comment by euh2** [comment]
Thanks! With 0.46.1 though, I get an issue mentioned in another thread: `pvesm path ...`. So I will just wait for the next release.

**Comment by macklenc** [comment]
> Thanks! With 0.46.1 though, I get an issue mentioned in another thread: `pvesm path ...`. So I will just wait for the next release.

Not sure if it will help or not, but I'm not getting any `pvesm path` errors using the `source_raw` attribute for the `proxmox_virtual_environment_file` resource in `0.46.1`: https://github.com/bpg/terraform-provider-proxmox/issues/1012

**Comment by ecanuto** [comment]
Hey, just found another issue with `rmdir`, the `-p`:

```
failed to remove '/tmp': Directory not empty
```

Looking at the **rmdir** man page we can see this:

```
       -p, --parents
              remove DIRECTORY and its ancestors; e.g., 'rmdir -p a/b/c' is similar to
              'rmdir a/b/c a/b a'

``

So, instead of just remove `/tmp/tfpve/.../snippets` it also tries to remove `/tmp`.

The third solution (using rm -rf) can fix the problem but will leave a `/tmp/tfpve/.../`directory behind. 

Searching for a way to properly fix the problem and maybe submit a patch.

**Comment by bpg** [comment]
@euh2 Version 0.44.0 is the last one before the sudo changes, you can try that.

**Comment by ecanuto** [comment]
@bpg pull request (#1013) submitted in case you plan to fix it later tonight.

**Comment by bpg** [comment]
Thanks, but it would be better to avoid rm -rf. There is a mistake in the code, the file is already moved, we don't need to call rm for it at all, so rmdir will be enough. But it should also have a param to suppress error if dir is not empty.
I can't follow up on this right now, but at some point later today.

**Comment by ecanuto** [comment]
> Thanks, but it would be better to avoid rm -rf. There is a mistake in the code, the file is already moved, we don't need to call rm for it at all, so rmdir will be enough. But it should also have a param to suppress error if dir is not empty. I can't follow up on this right now, but at some point later today.

Theres no parameters to prevent error on `rmdir`, also, we can't use `rmdir -p`. The only solution I can see that don't use `rm -rf` is to use two different `rmdir`.


```go
			fmt.Sprintf(`%s; try_sudo "mv %s/%s %s/%s" && rmdir %s && rmdir %s`,
				trySudo,
				srcDir, *fileName,
				dstDir, *fileName,
				srcDir,
				tempFileDir,
			),

```

Going to update PR (#1013).

**Comment by ecanuto** [comment]
@bpg the PR (#1013) updated with new code using two rmdir`s.

**Comment by bpg** [comment]
[v0.46.3](https://github.com/bpg/terraform-provider-proxmox/releases/tag/v0.46.3) is out and will be available in terraform / opentofu registries soon.
