### ISSUE TITLE
source_file change detection for proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by macklenc** [bpg/terraform-provider-proxmox#1012]
**Is your feature request related to a problem? Please describe.**
When using a resource such as:
```tf
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local-lvm"
  node_name    = "pve0"

  source_file {
    path = "./manifests/controlplane.yaml"
  }
}
```

it doesn't detect changes of the source file, requiring me to destroy and re-create my deployment whenever `"./manifests/controlplane.yaml"` is modified. Currently `source_raw` seems to do this correctly.

**Describe the solution you'd like**
I would like to see some kind of test to see if a local file has changed or an update to the docs to advocate for using the workaround when using local files.

**Describe alternatives you've considered**
The following snippet seems to be a valid "work around":

```tf
resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local-lvm"
  node_name    = "pve0"

  source_raw {
    data = file("./manifests/controlplane.yaml")
    file_name = "controlplane.yaml"
  }
}
```

**Comment by bpg** [comment]
Duplicates #677
