### ISSUE TITLE
provider crashed when cloning LXC container

### ISSUE THREAD

**Issue by Xel-Naha** [bpg/terraform-provider-proxmox#1025]
When cloning an existing CT container the provider crashes with error:

Stack trace from the terraform-provider-proxmox_v0.46.3 plugin:
panic: interface conversion: interface {} is types.CustomBool, not bool
Error: The terraform-provider-proxmox_v0.46.3 plugin crashed!

**To Reproduce**
run following terraform script:

```hcl

resource "proxmox_virtual_environment_container" "k3s_master" {
    count = 1
    node_name = "proxmox01"
    tags      = ["kubernetes"]
    description = "k3s-master-nodes${count.index + 1}"
    vm_id     = count.index + 5000

    clone {
      datastore_id = "local"
      vm_id = 9001
    }

}

```

**Expected behavior**
The ct container should be clones without issues

- Single or clustered Proxmox: cluster but against single host
- Provider version (ideally it should be the latest version): v0.46.3
- Terraform version: v1.7.3
- OS (where you run Terraform from): Linux Ubuntu

**Comment by Xel-Naha** [comment]
To add to this,

when I put some initialisation here to overwrite the pre-configured network details from the template it does work, e.g. with this added to terraform:

`    initialization {
        hostname = "k3s-master-${count.index + 1}"

        ip_config {
            ipv4 {
                address = "10.0.90.10${count.index + 1}/24"
                gateway = "10.0.90.1"
            }
        }
        dns {
            domain = "networkdroids.co.uk"
            server = "10.255.255.255"
        }
    }`

**Comment by bpg** [comment]
Hi @Xel-Naha! Could you please attach a full stack trace? It should have references to .go files with line numbers beside them. That will help greatly with identifying the problematic code.
Thanks!

**Comment by Xel-Naha** [comment]
> Hi @Xel-Naha! Could you please attach a full stack trace? It should have references to .go files with line numbers beside them. That will help greatly with identifying the problematic code. Thanks!

hi yup, can do, however i'm seeing token details in the debug, is it possible to filter this out actually as i'd rather not paste any token/confidential details here (for obvious reasons)

**Comment by bpg** [comment]
Yup, that's it, thanks!

**Comment by bpg** [comment]
@Xel-Naha just to confirm, does your source container have the firewall enabled?

**Comment by Xel-Naha** [comment]
hi @bpg , do you mean the clone template? in that case no the firewall settings are disabled:

![Screenshot 2024-02-10 111715](https://github.com/bpg/terraform-provider-proxmox/assets/100222761/746d505f-f0ef-4ac8-9ca6-1def5b49e5fe)

**Comment by bpg** [comment]
I see where the error could pop up from in the code, but I'm having hard time reproducing the bug.
@Xel-Naha could you run this command in PVE shell and paste the output?

```
pvesh get /nodes/proxmox01/lxc/9001/config --output-format json-pretty
```

**Comment by Xel-Naha** [comment]
{
   "arch" : "amd64",
   "cores" : 1,
   "digest" : "610203907ed6df91388350c4456d70c80569f3d6",
   "hostname" : "k3s-node",
   "lxc" : [
      [
         "lxc.apparmor.profile",
         "unconfined"
      ],
      [
         "lxc.cgroup.devices.allow",
         "a"
      ],
      [
         "lxc.cap.drop",
         ""
      ],
      [
         "lxc.mount.auto",
         "\"proc:rw sys:rw\""
      ]
   ],
   "memory" : 2048,
   "net0" : "name=eth0,bridge=vmbr90,firewall=1,gw=10.0.90.1,hwaddr=BC:24:11:A5:90:72,ip=10.0.90.200/24,type=veth",
   "ostype" : "ubuntu",
   "rootfs" : "pNVME_vms:9001/base-9001-disk-1.raw,size=16G",
   "swap" : 512,
   "tags" : "templates",
   "template" : 1
}
