### ISSUE TITLE
local vs local-lvm

### ISSUE THREAD

**Issue by raithedavion** [bpg/terraform-provider-proxmox#1039]
**Describe the bug**
I am attempting to create a basic vm from a cloud image using your tutorial located here:  https://registry.terraform.io/providers/bpg/proxmox/latest/docs/guides/cloud-image

I set all the datastore_id's to "local".  "local" is just a "dir" type right?  Terraform just gripes at me that "local-lvm" doesn't exist so I can't create a VM.  

`# cat storage.cfg
dir: local
        path /var/lib/vz
        content images,iso,snippets,vztmpl,backup,rootdir
        is_mountpoint no
        shared 0`

**To Reproduce**

Quite litterally following your tutorial with datasource_ids set to local.  Note, this is on an OVH bare metal server.  By default this creates everything as a "local" dir mounted as /var/lib/vz.  

```
resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image" {
  content_type = "iso"
  datastore_id = "local"
  node_name    = "leen-proxmox-01"
  url          = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  file_name    = "ubuntu.img"
}

resource "random_password" "ubuntu_vm_password" {
  length           = 40
  override_special = "_%@"
  special          = true
}

resource "tls_private_key" "ubuntu_vm_key" {
  algorithm = "ED25519"
}

resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name      = "test-ubuntu-cloud-img"
  node_name = "leen-proxmox-01"
  vm_id     = 4000
  agent {
    enabled = false
  }

  startup {
    order      = "3"
    up_delay   = "60"
    down_delay = "60"
  }

  disk {
    datastore_id = "local"
    file_id      = [proxmox_virtual_environment_download_file.ubuntu_cloud_image.id](http://proxmox_virtual_environment_download_file.ubuntu_cloud_image.id/)
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 20
  }

  network_device {
    bridge = "vmbr2"
  }

  operating_system {
    type = "l26"
  }

  tpm_state {
    version = "v2.0"
  }

  initialization {
    datastore_id = "local"
    user_account {
      username = "ubuntu"
      keys     = [trimspace(tls_private_key.ubuntu_vm_key.public_key_openssh)]
      password = random_password.ubuntu_vm_password.result
    }

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }
}
```

Please also provide a minimal Terraform configuration that reproduces the issue.

```
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.46.4"
    }
  }
}

provider "proxmox" {
  endpoint  = "https://172.16.0.10:8006/"
  api_token = "terraform@pve!provider=<redacted>"
  insecure  = true
  ssh {
    agent    = true
    username = "terraform"
  }
}
```

**Expected behavior**
Should accept the "local" datasource and create a VM.  

**Screenshots**
![tf_proxmox_error](https://github.com/bpg/terraform-provider-proxmox/assets/10229133/a9cb628d-e534-4e97-80a5-6e4a0500935f)

**Additional context**

- Single or clustered Proxmox: Clustered
- Provider version (ideally it should be the latest version): 0.46.4
- Terraform version:  1.7.3
- OS (where you run Terraform from): ubuntu 22.04
- Debug logs (`TF_LOG=DEBUG terraform apply`):
[tf.log](https://github.com/bpg/terraform-provider-proxmox/files/14335821/tf.log)

**Comment by raithedavion** [comment]
Ah, that would explain it.  I missed that.  Thanks!!!!

**Comment by bpg** [comment]
No prob :) I'm closing this ticket then, feel free to reopen if you need any more help.
