### ISSUE TITLE
[BUG] v0.46.4 -> v0.46.5 breaks : The mac_addresses attribute is missing elements.

### ISSUE THREAD

**Issue by Dr-Shadow** [bpg/terraform-provider-proxmox#1048]
The attribute [mac_addresses](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#mac_addresses) from [proxmox_virtual_environment_vm](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm) went from a list of 3 mac addresses (loopback / ethernet / internal bridge) to a list of 1 mac addresses (only ethernet interface).

What was expected :
A list of mac addresses which would be the same as the one retrieved from the web GUI
![image](https://github.com/bpg/terraform-provider-proxmox/assets/5308086/7f7251ba-f6bb-4c81-89e9-a5194363027b)

I use the index of the list to pair the mac_addresses with the interfaces names and ipv4/ipv6 addresses

**Comment by bpg** [comment]
Thanks for the report @Dr-Shadow!

This piece of the code was [accidentally removed](https://github.com/bpg/terraform-provider-proxmox/pull/1040/files#diff-12bcc7e08b8cbd66ab84826d19fa7875cc1ce8acda247d75e508a3835ace5c15L5233-L5234) 😞 

<img width="931" alt="Screenshot 2024-02-20 at 7 39 02 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/ac0e311d-f597-4574-97d9-1a650e03a381">

**Comment by bpg** [comment]
@all-contributors please add @Dr-Shadow for bug
