### ISSUE TITLE
Can't create disk on VM whith SATA interface

### ISSUE THREAD

**Issue by BURUNDUCHEK** [bpg/terraform-provider-proxmox#1056]
**Describe the bug**
Can't create disk on VM whith SATA interface. SCSI and VIRTIO works right.

**To Reproduce**

1. Apply the config below.

```hcl

resource "proxmox_virtual_environment_vm" "vm" {
  name      = "vm"
  node_name = "pve01"
  stop_on_destroy = true
  memory {
    dedicated = 2048
    floating  = 2048
  }

  cpu {
    cores = 2
  }

   disk {
      interface   = "scsi2"
      size        = 1
      file_format = "raw"
  }

     disk {
      interface   = "sata0"
      size        = 1
      file_format = "raw"
  }

  clone {
    vm_id = 100
    full  = false
  }
}

```

**Expected behavior**
I expected new hard disk with sata0 appears next to scsi disks like on screenshot:
![image](https://github.com/bpg/terraform-provider-proxmox/assets/90559433/f9c6d481-aa3f-49dc-889a-ceae8dc1c323)

**My environment**
- Single Proxmox
- Provider version: 0.46.4
- Terraform version: 1.7.2
- OS: Debian 12
- Debug logs (`TF_LOG=DEBUG terraform apply`): 
![image](https://github.com/bpg/terraform-provider-proxmox/assets/90559433/0a682aed-f819-44b3-9397-50f26f37ad5c)

**Comment by bpg** [comment]
[Fixed](https://github.com/bpg/terraform-provider-proxmox/pull/1124/files#diff-f6144f95e1ea6688c9a6244b06ccb8701e2fb8b4715ed3496bc0e65c0761e97eR306-R308) in #1124

`iothread` attribute is not supported by `sata` interface in PVE, and will be ignored after the fix.

[Section 10.14.3](https://pve.bpglabs.net:8006/pve-docs/pve-admin-guide.html#qm_configuration)
<img width="909" alt="Screenshot 2024-03-14 at 12 31 56 AM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/4ee0f87a-8323-4b15-ad6b-74db0c4ecade">
