### ISSUE TITLE
Support disconnected interfaces

### ISSUE THREAD

**Issue by JD-ISWT** [bpg/terraform-provider-proxmox#1093]
**Is your feature request related to a problem? Please describe.**

I need to setup many networks on my VM. My problem is that the order of theses interfaces is important and all VM do not needs to be connected to all networks.

I use a dummy bridge for that with a disconnected link to ensure that VLAN data is always third interface for example.

**Describe the solution you'd like**

An argument where we could specify that the interface must be disconnected

```terraform   
      network_device {
          bridge      = "vmbr1"
          enabled     = true
          firewall    = false
          connected = false
      }
```

**Describe alternatives you've considered**

Manually disconnected interface

**Additional context**

The feature is available from the GUI within the advanced interface settings

![image](https://github.com/bpg/terraform-provider-proxmox/assets/57483715/819c44a7-b95d-4679-95d5-4e05189d1c52)

**Comment by JD-ISWT** [comment]
I do use `for_each` I just need disconnected attribute

**Comment by maykopetersen** [comment]
So put the `connected` as variable too and use `map` type to configure it in each vlan:

```hcl
variable "network_vlans" {
  type   = map(any)
  default = [
    "vlan01" = true
    "vlan02" = false
    "vlan03" = true
  ]
}

resource "proxmox_virtual_environment_vm" "my_vm" {
  for_each = var.network_vlans
...
  network_device {
    bridge = var.trunk_port
    vlan_id = each.key
    connected = each.value
  }
}
```

**Comment by JD-ISWT** [comment]
This what I want to do, but `connected` does not exists

This is the solution I would like to be implemented

**Comment by maykopetersen** [comment]
https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#enabled

**Comment by bpg** [comment]
> `network_device` has the `enabled` argument: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm.

I don't think it would work that way. The `enabled` argument is [not mapped](https://github.com/bpg/terraform-provider-proxmox/blob/fbd04ed95061f23747e4bb7224901f6a409f7547/proxmox/nodes/vms/vms_types.go#L94) to any PVE property, setting it to `false` will remove the network device from the VM.

Adding `connected` flag is a valid feature request 🙂

**Comment by JD-ISWT** [comment]
`enabled` does not produce the same settings than `disconnected`.

When set `enabled` to `false` the interface is removed

As you can see on the screenshot `disconnected` is a real standalone parameter that is defined in the API 
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config
(link_down)

**Comment by maykopetersen** [comment]
> > `network_device` has the `enabled` argument: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm.
> 
> I don't think it would work that way. The `enabled` argument is [not mapped](https://github.com/bpg/terraform-provider-proxmox/blob/fbd04ed95061f23747e4bb7224901f6a409f7547/proxmox/nodes/vms/vms_types.go#L94) to any PVE property, setting it to `false` will remove the network device from the VM.
> 
> Adding `connected` flag is a valid feature request 🙂

Ah, I'm sorry!
