### ISSUE TITLE
cicustom vendor.yml

### ISSUE THREAD

**Issue by brutesque** [bpg/terraform-provider-proxmox#111]
I'm trying to add a custom cloud init config file. Currently it mentions [here](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#user_data_file_id) that the custom `user_data_file_id` will conflict with the cloudinit configs that proxmox creates (which should are user, network and meta). Which makes sense. Either proxmox will generate them or you can supply them.

It's possible to extend the cloudinit configuration without interfering with the `user`, `network` and `meta` configs that proxmox generates. I propose implementation of the `vendor` config by adding a `vendor_data_file_id` argument in the terraform config.

I've manually tested succesfully that a `vendor` config file not interfere with the cloudinit configs that proxmox generates. Currently I add this line to the vmid config file:
`cicustom: vendor=local:snippets/vendor.yaml`

**Comment by mcalfin** [comment]
+1 for this. was just looking at switching to this provider from an older non working one, but that provider supports cicustom which we use, preventing us from moving to this one.

**Comment by bpg** [comment]
Hi @brutesque, would you share an obfuscated example of `vendor.yaml` file that works for you?

**Comment by brutesque** [comment]
@bpg 

`/var/lib/vz/snippets/vendor-ubuntu-2204.yml`
```
#cloud-config
runcmd:
  - apt update
  - apt install -y qemu-guest-agent
  - systemctl start qemu-guest-agent
```

**Comment by bpg** [comment]
@brutesque thanks! This should be working now in the [latest](https://github.com/bpg/terraform-provider-proxmox/releases/latest) version.
