### ISSUE TITLE
proxmox_virtual_environment_file set destination file name

### ISSUE THREAD

**Issue by outworld66** [bpg/terraform-provider-proxmox#1120]
**Is your feature request related to a problem? Please describe.**

Creating a module with templated cloud-init files for each VM.
proxmox_virtual_environment_file cannot be set to a file name on a proxmox node except through the resource name.

**Describe the solution you'd like**

For proxmox_virtual_environment_file add the name of the destination file

**Describe alternatives you've considered**

I would not like to use depends_on on calls to other modules in module calls.

Specifying proxmox_virtual_environment_file for each VM in the file from which the module is called is not nice. For example, I have metadata, networkdata and userdata files. This is three calls to proxmox_virtual_environment_file per VM. If you have more? In general, I would like to call only the module.

**Additional context**

I would like to create a module in which cloud-init files are created from templates and VMs with such cloud-init files.
The finished cloud-init file arrives at the proxmox node via proxmox_virtual_environment_file as a snippet. The module defines the proxmox_virtual_environment_file resources.

The problem is that if two or more VMs are needed, then there will be two module calls.
proxmox_virtual_environment_file will overwrite cloud-init configs on the proxmox node and the same config will be inserted into each VM. I would not like to use depends_on for each module.

This could be avoided if the proxmox_virtual_environment_file resource could point to a different file name on the proxmox node than the one taken from the resource name.

This could be avoided if terraform supported dynamic resource naming.

**Comment by bpg** [comment]
Hi @outworld66! 👋🏼

I might not have fully grasped your use case, but there's an option to specify the target file name in the PVE storage via the [`file_name`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#file_name) attribute of `proxmox_virtual_environment_file`. Could this be what you're looking for? You can see an example [here](https://github.com/bpg/terraform-provider-proxmox/blob/main/examples/guides/cloud-init/custom/cloud-config.tf#L31).

Additionally, you don't _have_ to reference file IDs via `proxmox_virtual_environment_file` resource IDs. For example, this line:
https://github.com/bpg/terraform-provider-proxmox/blob/be45a2e8403b0b7d983a0811298b52ebd5ea8564/examples/guides/cloud-init/custom/main.tf#L33
can be replaced with:
```terraform
user_data_file_id = "local:snippets/cloud-config.yaml"
```

**Comment by outworld66** [comment]
@bpg Hi! Thanks for the answer.

In my case, source_raw is not used, so specifying file_name is problematic. I would like to keep separate files with templates, and not insert the content into source_raw.

Usage
```bash
user_data_file_id = "local:snippets/cloud-config.yaml"
```
would help me, but the proxmox node does not have such files. The indication "local:..." uses the path on the proxmox node, and not the local directory from where terraform is executed? I checked, it seems to be so.

How then to upload cloud-init files to the node? Provided that separate cloud-init files are used for each VM? If you put it all together into a module, it looks impossible.

workaround: use ssh provider to upload files to the proxmox node. but why if there is a proxmox api.

**Comment by outworld66** [comment]
I found a more suitable option. I'm surprised I didn't notice it before :)
For snippet, each VM needs to indicate the original name:
```bash
resource proxmox_virtual_environment_file cloud_config_meta_data {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name

  source_file {
    path = "./modules/proxmox_vm/cloud-init-configs/data-vm/data-vm-meta-data"
  }
}
```
then the file will not be overwritten and the original snippet will be used for each VM.
