### ISSUE TITLE
Missing protection option for VM

### ISSUE THREAD

**Issue by CRASH-Tech** [bpg/terraform-provider-proxmox#1125]
Hello, thanks for your job!

I want to confiure "protection" option for vms, but option is missing.

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

**Comment by EugenMayer** [comment]
Really would love to see this one happen. Especially for data-vms this is a must-have option which i yet set manually - considering how sensible this option is to the process / idea, i really would appropriate any progress here!

**Comment by bpg** [comment]
This one is quite straightforward, PR is coming! 🙂

**Comment by EugenMayer** [comment]
Wow! Thank you so much. Looking at the PR i guess the next time i could contribute simple attributes like this. Or at least i will try :)
