### ISSUE TITLE
Re-imported cloned VM does not match the original plan

### ISSUE THREAD

**Issue by ratiborusx** [bpg/terraform-provider-proxmox#1131]
**Describe the bug**
Import of said resource is successful but mostly unusable because after import resource loses some arguments it had before, most importantly "clone" collection (i can live with recreating of "agent.timeout" and other general timeouts).

**To Reproduce**

1. Create a resource 'proxmox_virtual_environment_vm'
2. Run 'terraform state rm' and then 'terraform import' to import resource into the same state or just import it into another state initially
```
ratiborus@HOMEWORLD:~/WORKSPACE/terraform/infra$ terraform import 'module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"]' prox-srv1/174
module.infra_px.data.proxmox_virtual_environment_vms.template_vms: Reading...
module.infra_px.data.proxmox_virtual_environment_vms.template_vms: Read complete after 0s [id=fad642ed-4d4a-45c3-b24d-f539eb601a06]
module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"]: Importing from ID "prox-srv1/174"...
module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"]: Import prepared!
  Prepared proxmox_virtual_environment_vm for import
module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"]: Refreshing state... [id=174]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
3. Run 'terraform plan'
```
ratiborus@HOMEWORLD:~/WORKSPACE/terraform/infra$ terraform plan
module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"]: Refreshing state... [id=174]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.infra_px.proxmox_virtual_environment_vm.px_vm["gitlab-runner-px-007"] must be replaced
-/+ resource "proxmox_virtual_environment_vm" "px_vm" {
      + boot_order              = [
          + "scsi0",
        ]
      ~ id                      = "174" -> (known after apply)
      ~ ipv4_addresses          = [
          - [
              - "127.0.0.1",
            ],
          - [
              - "10.177.143.214",
            ],
          - [
              - "172.17.0.1",
            ],
        ] -> (known after apply)
      ~ ipv6_addresses          = [
          - [
              - "::1",
            ],
          - [
              - "fe80::9892:67ff:fe9b:842",
            ],
          - [
              - "fe80::42:c7ff:fe02:3fa2",
            ],
        ] -> (known after apply)
      ~ mac_addresses           = [
          - "00:00:00:00:00:00",
          - "9A:92:67:9B:08:42",
          - "02:42:C7:02:3F:A2",
        ] -> (known after apply)
      + migrate                 = true
        name                    = "gitlab-runner-px-007"
      ~ network_interface_names = [
          - "lo",
          - "eth0",
          - "docker0",
        ] -> (known after apply)
      + on_boot                 = true
      + reboot                  = false
      + stop_on_destroy         = false
        tags                    = [
            "gitlab-runner",
            "task-tinfra-266",
            "template-debian-12-main",
            "terraform",
        ]
      + timeout_clone           = 1800
      + timeout_create          = 1800
      + timeout_migrate         = 1800
      + timeout_move_disk       = 1800
      + timeout_reboot          = 1800
      + timeout_shutdown_vm     = 1800
      + timeout_start_vm        = 1800
      + timeout_stop_vm         = 300
      ~ vm_id                   = 174 -> (known after apply)
        # (9 unchanged attributes hidden)

      ~ agent {
          ~ timeout = "15m" -> "5m"
            # (3 unchanged attributes hidden)
        }

      + clone {
          + full    = true # forces replacement
          + retries = 3 # forces replacement
          + vm_id   = 131 # forces replacement
        }

      ~ cpu {
          - flags        = [] -> null
            # (8 unchanged attributes hidden)
        }

      ~ disk {
          ~ path_in_datastore = "174/vm-174-disk-0.qcow2" -> (known after apply)
            # (8 unchanged attributes hidden)
        }

      ~ network_device {
          ~ mac_address = "9A:92:67:9B:08:42" -> (known after apply)
            # (8 unchanged attributes hidden)
        }

        # (5 unchanged blocks hidden)
    }
```
4. We can see that terraform tries to add 'clone' argument collection it somehow lost after importing resource but that forces recreation of the said resource which defeats the whole purpose of importing it in the first place.

In the end i did it by manually editing state file in S3 bucket (yeah, i know its not a good thing to do):
```
was:
"clone": [],

changed to:
"clone": [
  {
    "datastore_id": "",
    "full": true,
    "node_name": "",
    "retries": 3,
    "vm_id": 131
  }
],
```

**Expected behavior**
It would be nice if 'clone' collection argument could be preserved after import because that's the only one that breaks resource.
As i said we can deal with agent.timeout reset or missing timeout values - their omission not destructive, but this one is.
Also would be nice to know if other folk experience something similar, maybe i'm at fault here.

**Additional context**

- 3-node cluster PVE 8.0.3
- bpg/proxmox v0.48.4
- Terraform v1.7.5
- Ubuntu 22.04 LTS (WSL2)

**Comment by bpg** [comment]
This problem is similar to what I was trying to explain in https://github.com/bpg/terraform-provider-proxmox/issues/1134#issuecomment-2005569477
Basically, any information about the `clone` source (particularly in the case of a full clone) is completely transient and is not stored in the VM. So there is no way to read it back during the import.

But I'm more curious about the actual use case, why you may need to know the clone's source? Are you planning on updating the source and then have those updates automatically reflected in the clone?
Or is it a case of disaster recovery, when you have a previously applied plan, but the state is lost and you're recovering the state?

If the usage scenario is an edge case, then I'd say, manually editing the imported state and/or plan to reconcile them is a viable option.

**Comment by ratiborusx** [comment]
Hey!
Yep, i suspected it won't be an easy solution :D
My case involves 2 possible scenarios:
- We have several directory separated environments with dedicated state file each. So person who's helping me manage Proxmox created a VMs in the wrong environment and i wanted to move them into a correct one by removing resources in the initial state and importing in the correct one.
- Second possible scenario is to try to move already existing manually created VMs under terraform management. It so happened that before i wrote a module some people used to create VMs in GUI so they're "unmanaged" now. I don't remember if i tried that yet though but i thought that i could try to use that on VMs created manually from my module's templates.

Overall i don't really need to know clone's source - i just want my imported VMs to stay and not be re-provisioned by terraform plan. Actually, maybe i could use 'lifecycle' argument for that. Something like this:
```hcl
  lifecycle {
    ignore_changes = [
      clone
    ]
  }
```
UPD.
Yep, it works. At least there's no detected changes in resource that would force re-provision. It would make impossible to re-provision resource by changing clone source of course but i already had 'clone[0].vm_id' in there actually - i guess in case my template VMs change their vm_id (they receive it dynamically and i sometimes re-create these templates with updated images). So it's no biggie.
I suppose we could close this one if you don't have anything to add, i really enjoy your explanations. It is nice to talk to smart people :)
