### ISSUE TITLE
Unsupported argument

### ISSUE THREAD

**Issue by BrickJoris** [bpg/terraform-provider-proxmox#1147]
First of all i don't have a issue i just want to ask something.
I was adding a resource in the root.tf.

When i did this i got the error "Unsupported Argument"
This happend when i used source_url to give the url where the download is for my iso file.
Is ther esomeone who can help me with this or how do I fix this.

**Comment by bpg** [comment]
Ah, I guess you found the answer!
But feel free to submit any questions here in the issues, or in discussions, we’ll try our best to help! 🙂
