### ISSUE TITLE
CPU Affinity

### ISSUE THREAD

**Issue by sergelogvinov** [bpg/terraform-provider-proxmox#1148]
Thank you for your project.
I am really happy to use it!

**Is your feature request related to a problem? Please describe.**

Add cpu-affinity param on VM resource.

**Describe the solution you'd like**

I'd like to pin VM to the special CPUs. It helps me to reach better performance.

```
resource "proxmox_virtual_environment_vm" "example_template" {
  cpu {
    cores =  8
    numa  = true
    limit = 64

    affinity = "0-3,16-19"
  }
}
```

If you ok with it, i think, i can implement it.
Thank you!

**Comment by bpg** [comment]
Hi @sergelogvinov! 👋🏼 

This seems like a good improvement, and the implementation should be pretty straightforward.
I would really appreciate a pull request! ❤️

Thanks!
