### ISSUE TITLE
Numa memory binding 

### ISSUE THREAD

**Issue by sergelogvinov** [bpg/terraform-provider-proxmox#1156]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when <...>

Memory binding by numa.

**Describe the solution you'd like**

Hello, as we can bin the vCPU to special numa node (https://github.com/bpg/terraform-provider-proxmox/issues/1148), I'd like to configure memory binding too.

```tf
resource "proxmox_virtual_environment_vm" "example_template" {
  cpu {
    cores =  8
    numa  = true
    limit = 64

    affinity = "0-3,16-19"
  }
  memory {
    dedicated = 256
  }

  numa {
    cpus = "0-3"
    hostnodes = "0"
    memory = 128
    policy = bind
  }
  numa {
    cpus = "16-19"
    hostnodes = "1"
    memory = 128
    policy = bind
  }
}
```

What do you think the best way to implement it.
Should  we put the block `numa`  outsize the `cpu` block or inside?

Thanks

**Comment by bpg** [comment]
Hi @sergelogvinov! 👋🏼 

I think having `numa` inside the `cpu` block makes more sense.

We may also need to add `interface` attribute e.g. `interface = "numa1"`, to identify numa blocks and simplify mapping to the API without relying on ordering of the blocks.


Just putting it here for reference:
```
 numa: <boolean> (default = 0)

    Enable/disable NUMA.
numa[n]: cpus=<id[-id];...> [,hostnodes=<id[-id];...>] [,memory=<number>] [,policy=<preferred|bind|interleave>]

    NUMA topology.

    cpus=<id[-id];...>

        CPUs accessing this NUMA node.
    hostnodes=<id[-id];...>

        Host NUMA nodes to use.
    memory=<number>

        Amount of memory this NUMA node provides.
    policy=<bind | interleave | preferred>

        NUMA allocation policy.
```

**Comment by sergelogvinov** [comment]
Yep, and inside `memory` block looks like good place too.

I am little bit confused now )

**Comment by sergelogvinov** [comment]
What about `node`  value as numa node index, and we have a key conflict...

```
resource "proxmox_virtual_environment_vm" "example" {
  cpu {
    cores = 8
    limit = 64

    affinity = "0-3,16-19"

    numa = true
    numa {
      node      = 0
      cpus      = "0-3"
      hostnodes = "0"
      memory    = 128
      policy    = bind
    }
    numa {
      node      = 1
      cpus      = "16-19"
      hostnodes = "1"
      memory    = 128
      policy    = bind
    }
  }
  memory {
    dedicated = 256
  }
}

```

**Comment by bpg** [comment]
> Yep, and inside memory block looks like good place too.

I think NUMA is more related to CPU than memory, it depends on number of cores configured on the VM, etc.

> What about node value as numa node index, and we have a key conflict...

`node` cold be confusing, as there is also `hostnode` which may or may not match the `node`.
I believe `hostnode` is what actually [shown](https://pve.proxmox.com/wiki/NUMA) as "node" in  `numactl --hardware` hardware output.
Also `hostnode` could have a range or a list as per doc (`<id[-id];...`)


It feels like some form of stable ID is needed one way or another, as people may inserting `numa {...}` blocks between other `numa` blocks messing up definitions on the PVE side.

So I have something like this in mind:
```
resource "proxmox_virtual_environment_vm" "example" {
  cpu {
    cores = 8
    limit = 64

    affinity = "0-3,16-19"

    numa = true
    numa {
      interface = "numa0"
      cpus      = "0-3"
      hostnodes = "0;2"
      memory    = 128
      policy    = "bind"
    }
    numa {
      interface = "numa1"
      cpus      = "16-19"
      hostnodes = "1;3"
      memory    = 128
      policy    = bind
    }
  }
  memory {
    dedicated = 256
  }
}
```

What do you think?
