### ISSUE TITLE
User token

### ISSUE THREAD

**Issue by sergelogvinov** [bpg/terraform-provider-proxmox#1157]
**Is your feature request related to a problem? Please describe.**

Create a user token.

**Describe the solution you'd like**

```tf
resource "proxmox_virtual_environment_user_token" "kubernetes" {
  # required params
  user_id = "prometheus@pve"
  token_id = "kubernetes"

  # optional
  acl {
    path      = "/"
    propagate = true
    role_id   = "PVEAuditor"
  }

  separate = false
  comment = "Prometheus token"
  expiration_date = "2035-12-31T23:59:59Z"
}
```

What do you think?

**Comment by bpg** [comment]
Hi @sergelogvinov 👋🏼 I believe this is about the [API Tokens](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#pveum_tokens)  
If so, there is a feature request already: #740, which I don't mind to close, and keep this one.

The resource model makes sense to me. I would rename the resource to `proxmox_virtual_environment_api_token` though.
And I saw your WIP branch, having the "user token" naming there is fine.  
Also, the `separate` attribute could be renamed to more explicit "privilege_separation" for more clarity.


Speaking about the implementation, I would like to have all new resource and datasources to be created using the [Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework). My long term plan is to refactor all existing resources to the framework. 
You can find some example under `/fwprovider` folder.

Hope it make sense, pls let me know if you have any questions 🙂

**Comment by bpg** [comment]
Implemented in 
- #1159

**Comment by sergelogvinov** [comment]
Thank you!!!  I'm already using it 👍
