### ISSUE TITLE
CDKTF doesn't extract provider values

### ISSUE THREAD

**Issue by it-happens-nl** [bpg/terraform-provider-proxmox#117]
**Describe the bug**
When using CDKTF (v.0.12.1) and configuring the provider, I cannot add a "virtual_environment {}" block. An error "Argument of type virtualEnvironment is not assignable to parameter of type 'ProxmoxProviderConfig'". CDKTF only recognizes the "alias" parameter. Without the parameter, deployment seems to fail on this:

```
│ Error: you must specify the virtual environment details in the provider configuration
│ 
│   with proxmox_virtual_environment_pool.resource-pool,
│   on cdk.tf.json line 37, in resource.proxmox_virtual_environment_pool.resource-pool:
│   37:       }
```

**To Reproduce**
In a cdktf project, create a proxmox resource and declare the provider:
```nodejs
    // Setup provider
    new ProxmoxProvider(this, 'proxmox', {});
```
run cdktf deploy

**Expected behavior**
The provider should be generated correctly

**Additional context**
None at this point

**Comment by bpg** [comment]
I'm retagging this issue as "enhancement", as [CDKTF](https://www.terraform.io/cdktf) was not initially supported by the [original provider](https://github.com/danitso/terraform-provider-proxmox).
