### ISSUE TITLE
proxmox_virtual_environment_file tries to use all the available computer memory to upload a local image and crashes

### ISSUE THREAD

**Issue by rgl** [bpg/terraform-provider-proxmox#1187]
**Describe the bug**

`proxmox_virtual_environment_file` tries to use all the available computer memory to upload a local image and ends up killed by the OS.

**To Reproduce**

1. `git clone https://github.com/rgl/terraform-proxmox-upload-talos-img.git && cd terraform-proxmox-upload-talos-img`.
2. follow the README.md instructions.
1. Inside that [rgl/terraform-proxmox-upload-talos-img repository main.tf file](https://github.com/rgl/terraform-proxmox-upload-talos-img/blob/main/main.tf), you'll find the resource 'proxmox_virtual_environment_file' used as:
```hcl
resource "proxmox_virtual_environment_file" "talos" {
  datastore_id = "local"
  node_name    = "pve"
  content_type = "iso"
  source_file {
    path      = "tmp/talos/talos-${var.talos_version}.img"
    file_name = "${var.talos_version}.img"
  }
}
```
3. That `tmp/talos/talos-${var.talos_version}.img` file is essentially a raw disk image with 2 GiB in size.
4. Run `./do init && ./do plan-apply`.
5. Observe your computer memory being all used.

**Expected behavior**

Expected it to not crash, nor use all the computer memory, and actually upload the local image to the given proxmox datastore.

**Additional context**

- Single or clustered Proxmox: Single.
- Provider version (ideally it should be the latest version): 0.51.1
- Terraform version: 1.7.5
- OS (where you run Terraform from): Ubuntu 22.04
- Debug logs (`TF_LOG=DEBUG terraform apply`): [terraform-redacted.log](https://github.com/bpg/terraform-provider-proxmox/files/14889580/terraform-redacted.log)

**Comment by bpg** [comment]
Hi @rgl, could you use [`proxmox_virtual_environment_download_file`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_download_file) instead, to download directly to the proxmox host from a remote URL?

If not, you might need to switch the [temp directory](https://registry.terraform.io/providers/bpg/proxmox/latest/docs#temporary-directory) used by the provider from default /tmp to somewhere else, if /tmp is mounted to a ram drive on your host.

**Comment by rgl** [comment]
The file is not available remotely. Its created locally, and only then it can be uploaded. So, I think I cannot use that resource. 

Can the implementation of proxmox_virtual_environment_file be changed not to use a temporary file at all? And directly upload the local file?

**Comment by rgl** [comment]
Trying with:

```hcl
resource "proxmox_virtual_environment_file" "talos" {
  datastore_id = "local"
  node_name    = "pve"
  content_type = "dump"
  overwrite    = false
  source_file {
    path      = "tmp/talos/talos-${var.talos_version}.img"
    file_name = "${var.talos_version}.img"
  }
}
```

produced an unexpected result:

```
roxmox_virtual_environment_file.talos: Creating...
proxmox_virtual_environment_file.talos: Still creating... [10s elapsed]
proxmox_virtual_environment_file.talos: Still creating... [20s elapsed]
╷
│ Warning: the datastore "local" does not support content type "dump"; supported content types are: [backup images iso rootdir snippets vztmpl]
│ 
│   with proxmox_virtual_environment_file.talos,
│   on main.tf line 45, in resource "proxmox_virtual_environment_file" "talos":
│   45: resource "proxmox_virtual_environment_file" "talos" {
│ 
╵
╷
│ Error: failed to read file from "local:dump/1.6.7.img"
│ 
│   with proxmox_virtual_environment_file.talos,
│   on main.tf line 45, in resource "proxmox_virtual_environment_file" "talos":
│   45: resource "proxmox_virtual_environment_file" "talos" {
│ 
```

It seems `dump` is no longer a valid content type for Proxmox 8.1.10.

Also, it tried to create a file named `dump/1.6.7.img` instead of `talos-1.6.7.img` (as defined by `file_name = "${var.talos_version}.img"`).

Are these two expected to be like this?

**Comment by rgl** [comment]
I ended up following https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#important-notes did the trick for me. Sorry for all the noise!

The final result is at https://github.com/rgl/terraform-proxmox-upload-talos-img

**Comment by bpg** [comment]
@rgl I glad you found the solution!

Just curious, why you're rebuilding talos image in the first place? I don't see much of customization in your image, except perhaps https://github.com/rgl/terraform-proxmox-upload-talos-img/blob/main/do#L34?

**Comment by rgl** [comment]
For that, and the system extension(s).

BTW, I'm also using this in the talos example at https://github.com/rgl/terraform-proxmox-talos.
