### ISSUE TITLE
Terraform registry is missing version 0.52.0

### ISSUE THREAD

**Issue by Alex2761** [bpg/terraform-provider-proxmox#1198]
We wanted to try the new numa setting, but unfortunately we can't install the latest version from the registry
![grafik](https://github.com/bpg/terraform-provider-proxmox/assets/60945834/e1d986ba-9d7f-4911-9b2a-29779f3b3ba5)

**Comment by bpg** [comment]
Terraform Registry seems to be ignoring webhooks from GH time to time 😕
