### ISSUE TITLE
IDE disk support

### ISSUE THREAD

**Issue by TheDevMinerTV** [bpg/terraform-provider-proxmox#1202]
**Is your feature request related to a problem? Please describe.**
There is no support for IDE disks at the moment. These have been introduced into Proxmox a couple years back and they are required for some older guest OSes that don't even support SATA.

Given that a lot of people are going to be switching away from VMware and will probably come to Proxmox, it'd be amazing to have all of the UI features supported in the IaC providers as well.

**Describe the solution you'd like**
I'd like to see IDE disk support being implemented.

**Describe alternatives you've considered**
The telmate Terraform provider has the functionality: https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#diskside-block

**Additional context**
I've implemented initial support, though there seems to be some weird bugs that causes the VM creation to hang. https://github.com/TheDevMinerTV/terraform-provider-proxmox/tree/feat/ide-support

**Comment by bpg** [comment]
Thanks @TheDevMinerTV! Would you mind creating a PR from your branch so we can collaborate of it?

**Comment by gadgieOps** [comment]
This would be a useful enhancement for us. We believe that Arista CSX instances have this requirement.

**Comment by TheDevMinerTV** [comment]
Sure
