### ISSUE TITLE
Support for disk expansion without having to reboot the vm

### ISSUE THREAD

**Issue by simonebenati** [bpg/terraform-provider-proxmox#1211]
**Is your feature request related to a problem? Please describe.**
I would like to avoid to recreate each time the vm if I want to add a disk block, or I would like to not reboot the vm if I decide to resize the disk size

**Describe the solution you'd like**
Add a disk to the VM without recreating the instance (if possible) and avoid rebooting the VM when resizing a disk

**Describe alternatives you've considered**
---

**Additional context**
<img width="1350" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/102557087/45d2c6cb-8764-4630-9ecb-5d00057749fc">

**Comment by simonebenati** [comment]
Also please if, possible make it so that when adding a disk while starting the machine from a clone it works correctly in that scenario without having to recreate the cloned machine

**Comment by bpg** [comment]
Also in #103

**Comment by simonebenati** [comment]
@bpg hello there, i just had the chance to test this and it rebooted my vms..
i tried both hotplugging a disk and increasing one already in place..

**Comment by simonebenati** [comment]
<img width="1661" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/102557087/9a3449cc-5559-4ffe-a15b-2efa2f8c4c5a">

**Comment by bpg** [comment]
Hi @simonebenati, thanks for testing! Yeah, it is still not fixed yet.

@all-contributors please add @simonebenati for bug, testing

**Comment by bpg** [comment]
@all-contributors please add @simonebenati for bug, testing

**Comment by bpg** [comment]
Should be fixed in #1580
