### ISSUE TITLE
Add discard option to vm disk creation

### ISSUE THREAD

**Issue by dmeulen** [bpg/terraform-provider-proxmox#122]
One of the great features in proxmox is the discard option on disk volumes. Enabling the discard option on disks in comnbination with an fstrim / cron job or qemu agent fstrim inside the vm would free up discarded space automagically.

An extra option discard=<ignore|on> should be added to diskOptions when setting the virtual machine options in func resourceVirtualEnvironmentVMCreateCustomDisks.

**Comment by bpg** [comment]
Implementation-wise this should be quite similar to https://github.com/bpg/terraform-provider-proxmox/issues/87
