### ISSUE TITLE
Additional parameter for QEMU Agent checking 

### ISSUE THREAD

**Issue by marton-gombocz** [bpg/terraform-provider-proxmox#1248]
The problem is that if I enable guest agent checking and somehow the agent is not running on a machine, then the whole automation fails. We're operating with around 200 machines and we have an automation that creates new machines. If the agent is turned off in an instance then the whole automation crashes.
Best solution would be an additional `ignore_errors` variable that lets the process to continue if some of the machine is unresponsive.
Thanks in advance!
BR,
Márton

**Comment by bpg** [comment]
Hi @marton-gombocz! 👋🏼 

Before deciding on this ticket, I'd like to know a bit more about your error cases:
>The problem is that if I enable guest agent checking and somehow the agent is not running on a machine, then the whole automation fails. We're operating with around 200 machines and we have an automation that creates new machines. If the agent is turned off in an instance then the whole automation crashes.

How does it fail? How does it crash?

Just thinking aloud, if you don't need the QEMU Agent functionality, then don't enable it. If provisioning does not work with the agent disabled, then it depends on the agent functionality, and ignoring agent errors in this case won't do any good either.
But anyway, it's hard to make any decision without full understanding of the use case and seeing those errors messages / debug logs.

**Comment by marton-gombocz** [comment]
Hi @bpg!
Thanks for your response! 
Me and my colleagues will try to gather as much logs as we can, we just need some time and we'll come back to you.
BR,
Márton
