### ISSUE TITLE
Timeout on disk resize

### ISSUE THREAD

**Issue by geekscrapy** [bpg/terraform-provider-proxmox#1254]
**Describe the bug**
During creation of the VM the disk is resized and I get the following message:

`TASK ERROR: command '/usr/bin/qemu-img resize -f qcow2 /mnt/pve/<redacted>/images/1003/vm-1003-disk-0.qcow2 5368709120' failed: got timeout`

I have local disk and NFS datastores. If I use the NFS datastore, it works as expected, no error, but the local provides the timeout error.

After applying terraform and the resize fails (but everything else looks fine, running VM etc.), if I rerun `apply`, it resizes the disk correctly. The difference now being that it uses the user from the provider token rather than the `root` user, like as is shown in the screenshot. It appears that if the command is run by root, it fails.

**To Reproduce**

**providers.tf**
```hcl
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
  }
}

provider "proxmox" {
  endpoint = var.pve_endpoint
  api_token = var.pve_api_token
  insecure = true

  ssh {
    agent = false
    private_key = file("<redacted>")
    username = "<redacted>"
  }

}
```

**vm.tf**
```hcl
resource "proxmox_virtual_environment_vm" "new_vm" {
  node_name   = "pve"

  name        = "new-vm"

  # boot
  disk {
    datastore_id = "<redacted>"
    file_id      = proxmox_virtual_environment_download_file.jammy.id
    size         = 5
    backup       = true
    file_format  = "qcow2"
    interface    = "scsi0"
  }

}

resource "proxmox_virtual_environment_download_file" "jammy" {
  content_type       = "iso"
  datastore_id       = "<redacted>"
  node_name          = "pve"
  url                = "https://cloud-images.ubuntu.com/jammy/20240426/jammy-server-cloudimg-amd64.img"
  checksum           = "da76b0ef1cd45939f0d14ca11dd4dfabbe13b94d2ec144d54c805d1baf852e67"
  checksum_algorithm = "sha256"
  overwrite           = true
}
```

**Expected behavior**
For the disk to resize correctly

**Screenshots**
After the first `terraform apply`
<img width="1431" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/11225502/42a83b4b-7a39-4746-9dce-16ef52916f48">

After the second `terraform apply` when it realises the disk is not the correct size. Note the difference in user
<img width="1372" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/11225502/824280b7-be3f-4c48-96f5-a4189782c87e">

**Additional context**
- VM is eventually created, just with a small disk
- I have followed the ssh config correctly to allow password-less sudo.
- The local datastore filesystem is ext4, options in fstab are `rw,relatime` mounted at `/dev/sdb1`
- Using the command within the task error message (like below) with sudo, I can resize the disk manually from the cli (completed within about 5 seconds):
`sudo /usr/bin/qemu-img resize -f qcow2 /mnt/pve/<redacted>/images/102/vm-102-disk-0.qcow2 5368709120`
- There is no error shown in the terraform output, it looks like it was successful and normal

- Single Proxmox
- Provider version: latest as of posting
- Terraform version: Terraform v1.7.5 on linux_amd64
- OS (where you run Terraform from): Linux abc 6.2.16-12-pve # 1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64 x86_64 x86_64 GNU/Linux

**Comment by bpg** [comment]
Thanks for the report @geekscrapy. That's interesting behaviour. Personally I don't use "directory" storage type for VMs, so it is not tested well.

The user name change is something strange tho. I just want to confirm your case: you simply ran `terraform apply` twice, without any changes in template or the provider config, and second time `apply` passed, but apparently was running under a different user? Is "super" user the one that used to connect to the PVE API? or is the one for SSH access?

**Comment by geekscrapy** [comment]
Yes, I'd do the `apply` them back to back and it would come online with the defined resource as expected.

`super` is my main admin user (the default admin is my breakglass). I have applied all permissions to the super user both in proxmox and the os level

**Comment by geekscrapy** [comment]
I did a quick bit of debugging and it appears that the first resize call is done over SSH (with the `try_sudo` prefix), then the second is done via the API. I captured this via the terraform debug logs.

**Comment by bpg** [comment]
Thanks for the logs, and your conclusion is correct.

I think you're hitting an issue with a directory based storage similar to #1103. There is probably some FS locking or some other race condition in PVE that prevents resizing of a just attached disk.

Speaking about the fix, I double-checked the current API and I think we can get rid of running shell commands over SSH there. I'll take a look into that.

**Comment by geekscrapy** [comment]
Happy to test out the patch for you of course when its in the works 👍

**Comment by bpg** [comment]
Hi @geekscrapy, if you have a chance to test the code change from #1260 in your environment that would be great!

**Comment by bpg** [comment]
Ok, I'm going to merge the PR, and prob. cut out a release today.

**Comment by geekscrapy** [comment]
Hi, sorry I didn't manage to test the PR

I did however download and test the new release, and good news!

1. The final VM is as expected with only having to do one `apply` 👍 
2. It resizes the disk twice... 😄 The first time it fails, then 3 seconds later success. Seems to be a race condition as you say. Maybe add a delay of a few seconds before the resize as a stop gap?

Either way, thanks for pushing it out so fast.

**Comment by bpg** [comment]
I don't want to optimize for a (relatively rare) failure case though, so I'd probably leave the current approach.

BTW, would you consider to set up a [block storage](https://pve.proxmox.com/wiki/Storage) for your VMs,like LVM-thin or ZFS? It would have better overall performance, without the FS overhead.

**Comment by geekscrapy** [comment]
> I don't want to optimize for a (relatively rare) failure case though, so I'd probably leave the current approach.
Understood, so the double resize is intentional then, I presume. Either way it worksn


> BTW, would you consider to set up a [block storage](https://pve.proxmox.com/wiki/Storage) for your VMs,like LVM-thin or ZFS? It would have better overall performance, without the FS overhead.

Yes I probably will, but it would require a bit of upheaval (getting everything setup in terraform is one step). But I might add another disk and do ZFS on that
