### ISSUE TITLE
Support ssh-agent on Windows

### ISSUE THREAD

**Issue by Sparta142** [bpg/terraform-provider-proxmox#1257]
**Is your feature request related to a problem? Please describe.**
The provider does not support the use of ssh-agent (`agent = true`) on Windows.

**Describe the solution you'd like**
Be able to use ssh-agent on Windows, perhaps by connecting to the named pipe at `\\.\pipe\openssh-ssh-agent`.

**Describe alternatives you've considered**
- Pass a private key to the provider: doesn't work with passphrase protected keys
- Use password authentication: not as secure as public key authentication

**Additional context**
I prototyped this by changing this code to use [`winio.DialPipe`](https://pkg.go.dev/github.com/Microsoft/go-winio?GOOS=windows#DialPipe), disabling the POSIX check, and using the following Terraform config:
https://github.com/bpg/terraform-provider-proxmox/blob/b3caf6af8252e1fc737489f71534b96188f50631/proxmox/ssh/client.go#L539

```tf
provider "proxmox" {
  # ...

  ssh {
    agent        = true
    agent_socket = "\\\\.\\pipe\\openssh-ssh-agent"
    username     = "root"
  }
}
```

and it looks like it worked, in my limited manual testing! But maybe there's more to change than that? I could open a PR to work on this.

**Comment by bpg** [comment]
Thanks @Sparta142, a PR would be much appreciated!
