### ISSUE TITLE
Allow setting up (or propagating) the  VM name into cloudconfig. 

### ISSUE THREAD

**Issue by collegue1337** [bpg/terraform-provider-proxmox#1259]
**Is your feature request related to a problem? Please describe.**
The issue is that user_data_file_id does not allow passing on variables, like template files do. So setting up the hostname is currently impossible.

**Describe the solution you'd like**
Allow usage of templates instead of proxmox_virtual_environment_file.{cloud_config}.id or use resource name to populate the hostname.

**Describe alternatives you've considered**
Have one cloudconfig per VM, which is not really perfect when having more then a few VMs

**Comment by bpg** [comment]
Hi @collegue1337 👋🏼

It is possible to use templates with `user_data_file_id`, this is how I'm configuring VMs in my homelab. You can find an example [here](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/guides/cloud-init#custom-cloud-init-configuration). A specific example with host name setting can also be found [here](https://github.com/bpg/terraform-provider-proxmox/issues/1094#issuecomment-1979814366).

Please let me know if you need more assistance on this, or mark the issue as resolved if this solution works for you.

**Comment by collegue1337** [comment]
Hi @bpg,

yes, this is an alternative. The way I am trying to find is something closer to XCP way:

here is cloud-init template:
```
#cloud-config
hostname: ${name}
ssh_pwauth: True
...
```

And the way you use it in vm resource is like this:
```
cloud_config = templatefile("${path.module}/ubuntu_cloudconfig.tpl", {name =  "vm-name" })
```

This allows flexibility of having just one cloud-init config template for multiple VMs.

Do you think there is a hack that allows for something like this?

**Comment by bpg** [comment]
Yeah, I think you can try something like this to define the source in your `proxmox_virtual_environment_file` resource:
```hcl
...
source_raw {
    data = templatefile("${path.module}/ubuntu_cloudconfig.tpl", {name =  "vm-name" })
    file_name = "cloud-config.yaml"
}
...
```

**Comment by collegue1337** [comment]
Fair enough, sounds like a reasonable workaround. 

Long term it would be great to have a mechanism to pass variables from vm resource to a cloudconfig, but your workaround will work great for smaller deployments.

**Comment by bpg** [comment]
I think the terrafom's templating functionality is exactly for that. Implementing something similar in the provider would be duplication of the functionality IMO.

**Comment by collegue1337** [comment]
OK, so the proper feature request would be support for native way of cloudconfiguring the hostname?

**Comment by bpg** [comment]
The native PVE support for cloud-init is somewhat limited, but it does exist. So, if you're not utilizing custom cloud config files (user, vendor, etc.), PVE will supply a cloud-init config to the provisioning VM with the hostname set to the VM name and a few other settings that you can adjust in the UI:
<img width="356" alt="Screenshot 2024-05-04 at 5 24 27 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/014752a8-3f82-4d69-bbe5-c5f870ea643f">

Anything beyond that should be provided by custom cloud configs via the files. However, expecting the provider to understand their format and support file manipulation to inject certain variables is too much effort for just a small percentage of use cases, which can be easily handled with the solution discussed above.

These reasons led to my decision to close the ticket. Nonetheless, feel free to reopen it; I'd be happy to accept a PR if anyone would like to contribute 🙂
