### ISSUE TITLE
CD-ROM is not attached when creating a VM from scratch

### ISSUE THREAD

**Issue by madozu** [bpg/terraform-provider-proxmox#1283]
**Describe the bug**
When creating a VM from scratch using the "proxmox_virtual_environment_vm" node, the VM is created successfully, but the CD-ROM connection is missing fromthe created VM.

**To Reproduce**
1. Create a resource 'proxmox_virtual_environment_vm' with a 'cdrom {...}' block
2. Run 'terraform init -upgrade'
3. Run 'terraform apply'
4. VM is created, but CD-ROM is missing
5. Run 'terraform apply' again
6. VM is modified with the CD-ROM now attached on ide3

Minimal Terraform file to reproduce the issue:

```hcl

resource "proxmox_virtual_environment_vm" "testmachine" {
  name            = "testmachine"
  vm_id           = 999
  node_name       = "pve-1"
  started         = false
  cdrom {
    enabled   = true
    file_id   = "local:iso/existing-cdrom-image.iso"
  }
}

```

**Expected behavior**
CD-ROM attachment should be created with the first run of 'terraform apply'.

**Additional context**
- Single Proxmox server
- Proxmox version: 8.2.2
- Provider version: 0.55.1
- Terraform version: 1.8.3 (using source ```deb [arch=amd64] https://apt.releases.hashicorp.com jammy main```)
- OS: Ubuntu 22.04.4 LTS on amd64

**Comment by Qarasique** [comment]
I have same behaviour with file_id asquired from another module
`resource "proxmox_virtual_environment_vm" "talos_wrk" {
  description      = "k8s control plane cluster vm"
  tags             = ["k8s"]
  machine          = "q35"
  name             = var.name
  pool_id          = var.pool
  node_name        = var.proxmox_host
  vm_id            = var.vmid
  stop_on_destroy  = true
  timeout_create   = 60
  timeout_start_vm = 60

#####
  cdrom {
    enabled   = true
    file_id   = var.cdrom_iso_id
    interface = "ide0"
  }
######
`
