### ISSUE TITLE
proxmox_virtual_environment_user_token is not idempotent if no expiration_date is set

### ISSUE THREAD

**Issue by hamannju** [bpg/terraform-provider-proxmox#1292]
Hello. I was just testing Terraform on my Proxmox cluster and I created a module in order to have a DRY way to create Kubernetes cluster environments confined to their own respective pools. 

I used the resource "proxmox_virtual_environment_user_token" to create an API token for the management user without an expiration date. If I apply this configuration everything gets created correctly. However, if I run terraform plan after applying the configuration I receive this output:

```
module.k8s_dev.proxmox_virtual_environment_user_token.user_token will be updated in-place
  ~ resource "proxmox_virtual_environment_user_token" "user_token" {
      - expiration_date       = "1970-01-01T00:00:00Z" -> null
        id                    = "k8s_dev_user@pve!management_token"
      ~ value                 = (sensitive value)
        # (4 unchanged attributes hidden)
    }
```

The problem seems to be that Proxmox sets the expiration date to "1970-01-01T00:00:00Z" if no expiration date is set upon creating an API token which is different from null. I think the default behavior should be to set the expiration_date to this value if no expiration_date is defined in the resource definition.

Here is the resource definition I used, for reference:

```hcl
resource "proxmox_virtual_environment_user_token" "user_token" {
  comment               = "Managed by Terraform"
  token_name            = "management_token"
  user_id               = proxmox_virtual_environment_user.pool_user.user_id
  privileges_separation = false
}
```

Also thank you for working on this beautiful provider, it is a blessing :)

**Comment by bpg** [comment]
Good catch, @hamannju! This one is easy to fix.

And thanks for the good words! ❤️
