### ISSUE TITLE
Document which is the latest compatible version for Proxmox 7.4

### ISSUE THREAD

**Issue by gabrielke** [bpg/terraform-provider-proxmox#1303]
**Is your feature request related to a problem? Please describe.**
I'd like to have a clear communication about which version of the provider is compatible with proxmox 7.4

**Describe the solution you'd like**
Two sentences in the README

**Describe alternatives you've considered**

**Additional context**

**Comment by bpg** [comment]
I'm currently testing exclusively with the latest Proxmox release, but I'm sure there might be insights and experiences out there that the community can provide.

If you've got any additional info on compatibility, feel free to share! Appreciate your help!

**Comment by bpg** [comment]
Closing due to a lack of feedback
