### ISSUE TITLE
Align Defaults with Proxmox Defaults

### ISSUE THREAD

**Issue by maxexcloo** [bpg/terraform-provider-proxmox#1304]
**Is your feature request related to a problem? Please describe.**
I've noticed that when I create a new VM using the UI and a new VM using Terraform the defaults don't match (or show differently in the UI when switching between even for the same value). It would be good to have these match.

**Describe the solution you'd like**
Defaults match the defaults from the Proxmox UI.

**Describe alternatives you've considered**
Manually setting values, however these do not show as default and are thus shown differently in the UI.

**Additional context**
Awesome plugin, has been a huge help 💯

**Comment by bpg** [comment]
That's another known long standing issue.
I can't do much in the current implementation, unfortunately. Will be addressed in #1231.

Also in #566
