### ISSUE TITLE
HTTP 596 response Connection timed out in proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by Nunction** [bpg/terraform-provider-proxmox#1312]
**Describe the bug**
When using CephFS and `proxmox_virtual_environment_file` the PVE API ocasionally responds with HTTP 596 causing the plan/apply to fail. This seems to be a timeout issue in the PVE API caused by the [storage content listing taking to long](https://forum.proxmox.com/threads/rest-api-connection-error.73670/page-2#post-334768). So far I can only reliably reproduce the bug when using CephFS. Local storage seems to be unaffected. The file size in general is less then 4MB. It sometimes occurs on the first othertimes 20th resource. Using a haproxy infront of proxmox to distribute the requests somewhat helped, but the problem still persists.

```
│ Error: error retrieving files from datastore cephfs: received an HTTP 596 response - Reason: Connection timed out
```

Using `proxmox_virtual_environment_download_file` is not an options as `proxmox_virtual_environment_file` is needed to upload snippets.

**To Reproduce**

1. Create a resource 'proxmox_virtual_environment_file' to upload a snippet to CephFS
2. Run 'tofu apply'
3. See error (Sometimes)

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
# Occurs more often when creating multiple resources with i.e. for_each or count
resource "proxmox_virtual_environment_file" "metadata" {
  content_type = "snippets"
  datastore_id = "cephfs"
  node_name    = "pve1"
  overwrite    = true

  source_raw {
    data      = "example"
    file_name = "example.json"
  }
}

```

**Expected behavior**
While it is unreasonable to not get the error as it seems to be caused by the PVE API having a static timeout of 30s internaly, it would be great if the provider could retry that specific error as it will likely succeed the second time around.

Maybe this could be fixed using [retries](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts) or some other mechanism?

**Additional context**

- Single or clustered Proxmox: 7 node proxmox cluster
- Proxmox version: Proxmox 8.1.10 and CEPH 17.2.7 (Also tested with Proxmox 8.2.2 and CEPH 18.2.2)
- Provider version (ideally it should be the latest version): 0.57.0
- Terraform/OpenTofu version: OpenTofu version: 1.7.1
- OS (where you run Terraform/OpenTofu from): Docker debian:12 and GitLab CI/CD
- Debug logs (`TF_LOG=DEBUG terraform apply`): Available uppon request

**Comment by bpg** [comment]
Hi @Nunction 👋🏼 

I think adding some retries to that call is totally reasonable.
