### ISSUE TITLE
Missing "none" and "VirGL" to VGA type in proxmox_vm proxmox_virtual_environment_vm

### ISSUE THREAD

**Issue by lfelicetti-softatnet** [bpg/terraform-provider-proxmox#1320]
**Describe the bug**
Hello,
 trying to create a new virtual machine with "none" or "virgl" as vga type, causes a validation problem.

Here is an example error:

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected type to be one of ["cirrus" "qxl" "qxl2" "qxl3" "qxl4" "serial0" "serial1" "serial2" "serial3" "std" "virtio" "vmware"], got none
│
│   with proxmox_virtual_environment_vm.ubuntu_vm,
│   on main.tf line 17, in resource "proxmox_virtual_environment_vm" "ubuntu_vm":
│   17:     type = var.vm_vga_type
│

**To Reproduce**
 simply declare a vga type as "none" or "virgl".

```hcl

terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
      version = "0.55.1"
    }
  }
}

provider "proxmox" {
  endpoint = var.proxmox_endpoint_address
  username = var.proxmox_username
  password = var.proxmox_password
  insecure = var.proxmox_insecure
  tmp_dir  = var.proxmox_temp_dir
  ssh {
    username = var.proxmox_ssh_username
    password = var.proxmox_ssh_password
    agent = var.proxmox_use_ssh_agent
    node {
        name = var.proxmox_node_name        
        address = var.proxmox_node_ip_address
    }
  }
}

resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
---SNIP---
  vga {
    type = "none" // or virgl
  }
---SNIP---
}
```
**Expected behavior**

Create the virtual machine

**Additional context**
Versions:
 - Terraform v1.6.3 on Linux amd64
 - bgp/proxmox v0.57.1
 - Proxmox 8.2

Thanks in advance,
Leonardo.

**Comment by bpg** [comment]
There is a `vga.enabled` attribute, which, when set to false, is equivalent to `type="none"`. However, I found it unreliable in my testing, so I marked it as deprecated and added `none` to the available types list.
