### ISSUE TITLE
Container volume mount backup flag defaults to true in provider but false in Proxmox, so volume mounts are created with the flag missing.

### ISSUE THREAD

**Issue by rjshep** [bpg/terraform-provider-proxmox#1323]
**Describe the bug**
When creating a container with a volume mount, the provider code defaults the backup option to true, and omits it from the API call to Proxmox.

Proxmox's [docs](https://pve.proxmox.com/wiki/Backup_and_Restore#:~:text=By%20default%20additional%20mount%20points%20besides%20the%20Root,is%20managed%20outside%20the%20Proxmox%20VE%20storage%20library.) say:

"By default additional mount points besides the Root Disk mount point **are not included in backups**. For volume mount points you can set the Backup option to include the mount point in the backup. Device and bind mounts are never backed up as their content is managed outside the Proxmox VE storage library."

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a resource of type proxmox_virtual_environment_container, specifying with a volume mount, and backup = true set.

2. Apply the terraform, then look in Proxmox and not that the volume mount does not have backup=1 specified.
<img width="455" alt="Screenshot 2024-05-25 at 19 12 28" src="https://github.com/bpg/terraform-provider-proxmox/assets/20207097/b353e9eb-3d9d-489f-a376-b1fc4531c419">

3. Destroy the resource and create again, with `backup = false`

4. Apply the terraform, in Proxmox the volume mount now says backup=0.
<img width="526" alt="Screenshot 2024-05-25 at 19 13 02" src="https://github.com/bpg/terraform-provider-proxmox/assets/20207097/a2422255-e9a9-4cdc-af59-828f07ab3788">

5. Change `backup = false` to `backup = true`.

6. Apply the terraform, in Proxmox the volume mount now says backup=1, along various other options set.
<img width="766" alt="Screenshot 2024-05-25 at 19 14 30" src="https://github.com/bpg/terraform-provider-proxmox/assets/20207097/e17ad8ea-a345-4bf1-af46-0cce17e6eb45">

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
resource "proxmox_virtual_environment_container" "test" {
  node_name = "pve1"
  vm_id     = 101

  initialization {
    hostname = "test"

    user_account {
      password = "password"
    }

  }

  disk {
    datastore_id = "local-zfs"
    size         = 1
  }

  operating_system {
    template_file_id = "local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst"
    type             = "debian"
  }

  mount_point {
    volume = "local-zfs"
    size   = "1G"
    path   = "/mnt"
    backup = "true"
  }
}

```

**Expected behavior**
When creating a new proxmox_virtual_environment_container resource, with a volume mount and `backup=true` (or absent), volume mounted in the container should have backup=1 set.

When modifying an existing resource, changing the state of `backup=false` to `backup=true` and applying the TF the expected backup=1 appears.  Subsequent switch of `backup` is also correct, it's just the initial creation that doesn't appear correct.

If you agree with my understanding of the expected behaviour then I'm happy to look at a PR to fix.

**Screenshots**
See above.

**Additional context**

- Clustered Proxmox:
- Proxmox version: 8.2.2
- Provider version 0.57.1
- Terraform version: 1.8.3
- OS (where you run Terraform/OpenTofu from): MacOS 14.5

**Comment by bpg** [comment]
Hi @rjshep! 👋🏼 

Yes, you're right, and thanks for reporting this 👍🏼
I've made a small fix in #1327 that should solve the problem.
