### ISSUE TITLE
0.58.0 VM resource: `expected clipboard to be one of ["vnc"], got .`

### ISSUE THREAD

**Issue by muhlba91** [bpg/terraform-provider-proxmox#1337]
**Describe the bug**
I have an existing VM that does not specify the `vga.` Hence, the clipboard is set to `Default`, which apparently results in an empty string being returned from the API.

This error did not appear before `v0.58.0`, and I suspect the error is in the validation function of the `clipboard` attribute specified in https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmoxtf/resource/vm/vm.go#L1405-L1407 which expects that the returned value must be one of `["vnc"]`.

This now results in `'vm-home-home-cluster-001-prod' has a problem: expected clipboard to be one of ["vnc"], got . Examine values at 'vm-home-home-cluster-001-prod.vga.clipboard'.`

By looking at the code, I think this should also happen when creating a new machine and not specifying `vga` (maybe just not `vga.clipboard`).

I have not verified this with a Terraform example as I'm running Pulumi, but Pulumi does not do any validation and calls the provider's methods. Hence, the validation and resulting error come from here.

**To Reproduce**

Create a VM with no `vga` (or `vga.clipboard` set to `` representing the default value).

**Expected behavior**
The VM updates or creates successfully without an error.

**Additional context**
- Single or clustered Proxmox: single
- Proxmox version: `pve-manager/8.2.2/9355359cd7afbae4`
- Provider version (ideally it should be the latest version): `0.58.0`
- Terraform/OpenTofu version: N/A
- OS (where you run Terraform/OpenTofu from): macOS
- Debug logs (`TF_LOG=DEBUG terraform apply`): N/A

**Comment by bpg** [comment]
Thanks @muhlba91! I've pushed a fix, will be in the next release.
