### ISSUE TITLE
Problem with obtain ipv4 addresses for group of nodes

### ISSUE THREAD

**Issue by krnworks** [bpg/terraform-provider-proxmox#1349]
Hello!

Occasionally, upon the initial run, I receive empty output for the IP-addresses of virtual machines. However, if I repeat the apply command, I get the expected lists.

```hcl
output "ipv4_addresses" {
  value = {
    for vm_key, vm_value in proxmox_virtual_environment_vm.basic_vm:
    vm_key => flatten(vm_value.ipv4_addresses)
  }
}
```

```shell
Outputs:

ipv4_addresses = {
  "pve-1-1-12-0" = []
  "pve-1-1-12-1" = [
    "127.0.0.1",
    "10.0.200.35",
  ]
  "pve-1-1-13-0" = []
  "pve-1-1-13-1" = []
}
```

It appears that this behavior occurs because the output is retrieved before the virtual machines have acquired their IP addresses.

Is there a workaround for this issue or a way to introduce artificial delay to ensure that the output is retrieved after the virtual machines have acquired their IP addresses?

I use dhcp.

Best regards, Roman

**Comment by bpg** [comment]
Hi @krnwrks!

It won't be possible to reliably populate the VM IP addresses at the end of VM provisioning flow without using [qemu guest agent](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#qemu-guest-agent).

> This provider requires `agent.enabled = true` to populate `ipv4_addresses`,
`ipv6_addresses` and `network_interface_names` output attributes.

**Comment by krnwrks** [comment]
guest agent is enabled

**Comment by bpg** [comment]
Hm... The provider actually does [wait for a non-localhost IP address](https://github.com/bpg/terraform-provider-proxmox/blob/fb1105d93bd2fec4d9fe0cfa9155539d17d8b418/proxmox/nodes/vms/vms.go#L529-L553) 🤔 

@krnwrks Could you pls. provide [additional details about your environment](https://github.com/bpg/terraform-provider-proxmox/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L39-L44), and perhaps output from your plan execution? A debug log would be ideal.

**Comment by bpg** [comment]
As a workaround you may try adding something like this to your VM config:

```hcl

  provisioner "local-exec" {
    when    = create
    command = "sleep 5s"
  }

```

**Comment by bpg** [comment]
There is a good analysis on "wait for IP" behaviour in https://github.com/bpg/terraform-provider-proxmox/issues/668#issuecomment-1785831601

**Comment by bpg** [comment]
I'm going to close this issue as I haven't heard back from the author with additional details.

@krnworks, please feel free to reopen it if you need more support on this.
