### ISSUE TITLE
Control the SDN with Terraform

### ISSUE THREAD

**Issue by Luquor** [bpg/terraform-provider-proxmox#1350]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be very great to be able to manage SDNs, create Zones, VNets, Subnets with Terraform.
I know we can do use the API to do it, but only having one Terraform file is great.
![image](https://github.com/bpg/terraform-provider-proxmox/assets/47946746/9a9f9456-39d0-4ae3-b4fa-a72c01cc0217)

**Comment by bpg** [comment]
This duplicates #817. Please vote on the original issue to prioritize it.
