### ISSUE TITLE
Missing SPICE options for VMs

### ISSUE THREAD

**Issue by bitchecker** [bpg/terraform-provider-proxmox#1369]
**Is your feature request related to a problem? Please describe.**
I was working on code in order to enable SPICE protocol for VDI usage. I enabled VGA and AUDIO section, but if I try to configure USB, the "spice port" option is not available in the provider.

**Describe the solution you'd like**
I don't know if it's a new feature available recently on proxmox (maybe yes): 

![Istantanea_2024-06-09_16-28-14](https://github.com/bpg/terraform-provider-proxmox/assets/11056930/2f2356ce-82af-4cce-b610-a0c83e0944c8)

but the provider is missing this:

![Istantanea_2024-06-09_16-29-46](https://github.com/bpg/terraform-provider-proxmox/assets/11056930/780eb646-4353-4e2c-930e-dfa0d3ba6f61)

**Comment by bpg** [comment]
Hey @bitchecker 👋🏼 

It looks like you can just use `host="spice"` to enable this. From the [doc](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_configuration):
<img width="884" alt="Screenshot 2024-06-10 at 7 43 03 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/5d764a62-1705-4ce8-a037-b64faa7c1bf4">
