### ISSUE TITLE
proxmox_virtual_environment_download_file  new attribute: "path_in_datastore"

### ISSUE THREAD

**Issue by vanillaSprinkles** [bpg/terraform-provider-proxmox#1371]
**Is your feature request related to a problem? Please describe.**
when defining a vm, the disk map has an input of `file_id` or `path_in_datastore` ;  it is relatively easy to use `file_id = proxmox_virtual_environment_download_file.foo.id` however to use `path_in_datastore` the user must remove something like (regex) `^[^:]+:` from the id

**Describe the solution you'd like**
proxmox_virtual_environment_download_file could have an attribute 'path_in_datastore' as the class initializing the object would already have individual components to build the string, vs tf-code to break apart a string. 

the use case would be like (instead of the `replace` blob within the `alternatives` section at the bottom:
`path_in_datastore = proxmox_virtual_environment_download_file.foo.path_in_datastore`

**Describe alternatives you've considered**
currently using tf-string-manipulation instead of a clean attribute:
``` hcl
resource "proxmox_virtual_environment_vm" "foo" {
...
  disk {
   path_in_datastore = replace( proxmox_virtual_environment_download_file.foo.id, "/^[^:]+:/", "" )
...
```

**Comment by bpg** [comment]
Hi @vanillaSprinkles, I'm curious about your use case, why you need to initalize a disk using `path_in_datastore` instead of `file_id`?
The `path_in_datastore` was initially added for a specific case of [attaching disks](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#example-attached-disks) from other VMs.

**Comment by vanillaSprinkles** [comment]
my use case was the import of a vm where the cdrom was marked as a disk - i think this enhancement is likely unneeded. 

will close and can re-open if we need it 

cheers!
