### ISSUE TITLE
Error cloning template from shared storage

### ISSUE THREAD

**Issue by kverqus** [bpg/terraform-provider-proxmox#1387]
**Describe the bug**
I'm attempting to clone a template assigned to node pve01 (and stored on a shared storage) to node pve02 or pve03 (a three node cluster). It works fine when cloning to pve01, and when manually doing it through the web GUI. When attempting to clone to pve02 I get hit by `error cloning VM: received an HTTP 500 response - Reason: unable to f ind configuration file for VM 8000 on node 'pve02'`

**To Reproduce**

1. Create a template on pve01 in the cluster
2. Create a resource using the template on node01 and the destination node pve02
3. Run `terraform apply`

```
resource "proxmox_virutal_environment_vm" "test" {
  name = "test01"
  node_name = "pve02"

  clone {
    vm_id  = 8000  # template resides on node01
    full  = true
  }
}
```

**Expected behavior**
I'd expect the VM to be cloned to pve02 like when I perform the clone action through the web GUI.

**Additional context**
- Clustered Proxmox version: 8.1.4
- Provider version: 0.59.1

**Comment by bpg** [comment]
Probably related: 
- #998

**Comment by thehedgefrog** [comment]
Getting same error.

**Comment by bpg** [comment]
Thanks for the details, @thehedgefrog!

That's totally right. As per the [doc](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#clone)

> `node_name` - (Optional) The name of the source node (leave blank, if equal to the node_name argument).

The wording could be clearer, but it matches the reported case: a template from one node (`node01`) is being cloned to another node (`pve02`)

@kverqus Could you give that a try and see if it works for you?
I’ll close this ticket for now, but feel free to reopen it if you need more help.

**Comment by uchris13** [comment]
> Getting same error.
> 
> Edit: I fixed it by using `node_name` in the `clone` stanza. It creates all VMs on the one node and then migrates what is necessary.

can you please explain? I have this very same issue in my 3 node cluster. The VM is in node01 and it fails every time a VM has to be created in node02 and node03

**Comment by bpg** [comment]
replied in #1827
