### ISSUE TITLE
Cannot create volume mount point in LXC

### ISSUE THREAD

**Issue by megastary** [bpg/terraform-provider-proxmox#1393]
Edited as it throws errors nearly all the time.

**Describe the bug**
When defining mount point for LXC, you will receive various errors depending on current state of the VM.

**To Reproduce**

1. Define volume mount_point for LXC
2. Run tofu apply
3. See error 

When adding mount_point to existing LXC I get this error:
```shell
Error: error updating container: received an HTTP 500 response - Reason: unable to parse volume ID 'ceph'
│ 
│   with module.gitea.module.gitea.proxmox_virtual_environment_container.lxc,
│   on modules/lxc/main.tf line 1, in resource "proxmox_virtual_environment_container" "lxc":
│    1: resource "proxmox_virtual_environment_container" "lxc" 
```

When creating fresh LXC including volume mountpoint from the start:
```shell
Error: error creating container: received an HTTP 500 response - Reason: mount points configured, but 'rootfs' not set - aborting
│ 
│   with module.gitea.module.gitea.proxmox_virtual_environment_container.lxc,
│   on modules/lxc/main.tf line 1, in resource "proxmox_virtual_environment_container" "lxc":
│    1: resource "proxmox_virtual_environment_container" "lxc" {
```

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

# >>> put your example here <<< #
disk {
    datastore_id = "ceph"
    size         = "4"
}

mount_point {
    # volume mount, a new volume will be created by PVE
    volume = "ceph"
    size   = "8G"
    path   = "/opt/gitea"
  }
```

**Expected behavior**
LXC gets created with specified volume mount point.

- Single or clustered Proxmox: clustered
- Proxmox version: 8.2.2
- Provider version (ideally it should be the latest version): 0.60.0
- Terraform/OpenTofu version: OpenTofu v1.7.2
- OS (where you run Terraform/OpenTofu from): Fedora 40
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by megastary** [comment]
Nvm, now it does not work even with plain number.
Anyone knows why could that be happening?

**Comment by bpg** [comment]
Hi @megastary 👋🏼 

Just a sanity check regarding the error message:

> Reason: mount points configured, but 'rootfs' not set - aborting

Do you have the [`operating_system`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container#operating_system) attribute configured in your template? It is not in the example you provided. 🤔

You can also check an [example here](https://github.com/bpg/terraform-provider-proxmox/blob/b7d48f8716422a0f3f8636b3ba849e2446d8abef/example/resource_virtual_environment_container.tf#L11-L16). These templates are used as part of the integration test suite, which runs on every release.

**Comment by LinuCC** [comment]
I have the same problem in 1.55 as well as in 1.60, I just screwed around a bit and this helped:

1. Commenting out `mount_point` and creating the container with `terraform apply`
2. Uncommenting the `mount_point` block and adding its size at the end of the volume name:

```terraform
  mount_point {
    volume = "local:1"
    size   = "1G"
    path   = "/mnt/foobar"
    backup = true
  }
```

Based on https://forum.proxmox.com/threads/unable-to-parse-directory-volume-name-with-pct-create.55373/post-254947 and the API request I got from the debug logs it seems like on creation the size in the volume param is missing.

Also: 
- `operating_system` configured to `ubuntu`
- Proxmox v8.1.4

Trying a system update, maybe this'll fix it.

**Comment by LinuCC** [comment]
Right, after testing out your link @bpg I've been able to reproduce the error by lowering the `disk.size` of `example_template` from `10` to `4` (Which OP and me used as disk size):

```terraform
resource "proxmox_virtual_environment_container" "example_template" {
  vm_id = 323

  start_on_boot = "true"

  disk {
    datastore_id = "local-zfs" // Hardcoded some vals to fit my Proxmox instance
    size         = 4
  }

  // ...
}
```

Do you have an idea why this would lead to that rootfs error?

**Comment by bpg** [comment]
> Thinking about it, maybe the container disk size is just too small for Ubuntu to work properly.

That is my guess as well. After you provisioned with size e.g. `5`, can you check what is the reported root filesystem size on the deployed container?

**Comment by bpg** [comment]
I found the bug, 4Gb rootfs size is the default "magic number". Any value != 4 should work 🤦🏼
Will be fixed in the next release.

**Comment by LinuCC** [comment]
Haha, great to hear! Thanks so much for picking up the terraform provider btw, incredibly helpful (when it works ;) )
