### ISSUE TITLE
Using Cloud Init package_upgrade: false

### ISSUE THREAD

**Issue by willifehler** [bpg/terraform-provider-proxmox#1402]
Hi @bpg,

I'm trying set disable package_upgrade: false via cloud init.

Is this still the recommended way?

```
mkInitializationUpgrade: {
Type:        schema.TypeBool,
Description: "Whether to do an automatic package upgrade after the first boot",
Optional:    true,
Computed:    true,
Deprecated:  "The `upgrade` attribute is deprecated and will be removed in a future release.",
},
```

However putting upgrade: false still leads to that my Proxmox VM will upgrade the packages during the first boot.

Cheers - Willi

**Comment by bpg** [comment]
Hi @willifehler 👋🏼 

This flag was causing issues described in #1291, and has been removed.
Needs to be implemented differently, #1079 is still open.
