### ISSUE TITLE
Error: resizing disk: error waiting for VM disk resize: All attempts fail:

### ISSUE THREAD

**Issue by oussexist** [bpg/terraform-provider-proxmox#1404]
Hello There,
Im facing a little issue with provisionning a vm with cloud-init , so i uploaded a ubuntu image on my proxmox and as i followed the documentation here is my terraform main.tf config : 

```
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.60.0"

    }
  }
}
resource "proxmox_virtual_environment_vm" "master" {
    name        = var.VMasterName
  description = "Managed by Terraform"
  tags        = ["terraform"]
  node_name   = var.MasterNodeName
  vm_id       = 4322

  agent {
    enabled = true
  }
on_boot = false

  memory {
    dedicated = var.Mastermemory
  }
    
    
  disk {
    datastore_id = "local-lvm"
    file_id      = "local:iso/jammy-server-cloudimg-amd64.img"
    interface    = "scsi0"


  }

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }

  network_device {
    bridge = var.net
  }

}


```

i know the error is about the disk block ( althought i dont have local-zfs so ial using local-lvm) , but i really dont know what to put exactly in size argument so any number u'll put it leads to the same error , even putting it without size argument leads to same error cuz by default the size will be 8 ! here's the error : 
```
│ Error: resizing disk: error waiting for VM disk resize: All attempts fail:
│ #1: the server did not include a data object in the response
│
│   with proxmox_virtual_environment_vm.master,
│   on main.tf line 11, in resource "proxmox_virtual_environment_vm" "master":
│   11: resource "proxmox_virtual_environment_vm" "master" {
│
```

PS : I tried to create manually a vm to check what it puts by default in disk size , so it shows 32 , so i tried to put 32 on size arg and leads to same error

**Comment by bpg** [comment]
Hi @oussexist! 👋🏼

This looks suspiciously similar to #1403, which I haven't investigated yet.

Could you provide some more details about your setup? What is the PVE version?

**Comment by oussexist** [comment]
Hello @bpg 
so am using VirtualBox 7.0 and PVE 7.4 
Idk what other details should i provide more , am running virtual box a dell machine.

Although the Vm launched by terraform apply appears  asu u can see 
![image](https://github.com/bpg/terraform-provider-proxmox/assets/92154325/223a9e33-bc76-4622-9b2f-cbf5841b180b)

so by manually starting it here are some pics that may help...
![image](https://github.com/bpg/terraform-provider-proxmox/assets/92154325/00c02826-6442-4325-9052-83d74da0cfb5)
 and then it starts fine : 
![image](https://github.com/bpg/terraform-provider-proxmox/assets/92154325/53d1efd3-d5c5-44dd-ab3e-e35c2137a5c6)
 -----------------------------------------------------
and here are some more code for the file used that maybe u need : 
```
file.tf:
data "local_file" "ssh_public_key" {
  filename = "./id_rsa.pub"
}

resource "proxmox_virtual_environment_file" "cloud_config_master" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data = <<-EOF
    #cloud-config
    users:
      - default
      - name: ubuntu
        groups:
          - sudo
        shell: /bin/bash
        ssh_authorized_keys:
          - ${trimspace(data.local_file.ssh_public_key.content)}
        sudo: ALL=(ALL) NOPASSWD:ALL
    runcmd:
        - apt update
        - apt install -y qemu-guest-agent net-tools
        - timedatectl set-timezone America/Toronto
        - systemctl enable qemu-guest-agent
        - systemctl start qemu-guest-agent
        - echo "done" > /tmp/cloud-config.done
    EOF

    file_name = "cloud-config-master.yaml"
  }
}
```

**Comment by flombois** [comment]
Hi @oussexist I did run in the same issue in #1403 , however when upgrading to Proxmox 8.2.4 and using file_format = 'raw' in the disk block the vm creation succeeded. I suggest to try with 8.x version of Proxmox to see if the error is still reproducible. Nonetheless I still have some trouble with qcow2 format

**Comment by oussexist** [comment]
So Yes , I used PVE 8 and it worked fine ! 
Thanks @flombois

**Comment by bpg** [comment]
Nice! I'm closing the ticket then.
If you interested in some more details about `qcow2` usage I replied in https://github.com/bpg/terraform-provider-proxmox/discussions/1403#discussioncomment-9844733

**Comment by cgrard** [comment]
Hi there,

I am randomly getting this exact same error as well but in my case I'm using proxmox 8.2.7 (provider is version 0.72.0) and it goes away if I plan/apply again. The storage backend is ceph and the disk format is explicitly set to 'raw' so I'm not entirely sure it is related but it is the same error message.
Any idea what I should look at?

**Comment by bpg** [comment]
Hey @cgrard 👋🏼
This seems line a timeout issue to me. If it is reproducible, would you mind opening a new issue?

Also few more questions: Are you cloning a VM? Is the source and target VMs are on the same datastore? Can you share your terraform output when error happens?
