### ISSUE TITLE
Please add new arguments and attributes to the `proxmox_virtual_environment_vms` data source

### ISSUE THREAD

**Issue by konstantin-kornienko** [bpg/terraform-provider-proxmox#1422]
**Is your feature request related to a problem? Please describe.**
The issues described in my comment: https://github.com/bpg/terraform-provider-proxmox/issues/1412#issuecomment-2206061765

**Describe the solution you'd like**
Please add the following to arguments:
  * `template` (optional, bool) - List only template VMs (template = true) or non-template VMs (template = false)
  * `name_regex` (optional, string) - List only VMs which names are matching provided regex
  * `status` (optional, string) - List only VMs with this status (f.e. `running`)
 * `type` (optional, string) - List only VMs with this type (f.e. `qemu`)

Please add the following to returned attributes:
  * `template` (bool) - true for template VMs, false for normal VMs
  * `status` (string) - VM status
 * `type` (string) - VM type
 * `uptime` (number) - VM uptime in seconds

**Describe alternatives you've considered**
I can't see alternatives for the time being.

**Comment by vanillaSprinkles** [comment]
if those features are added, perhaps too maybe add timestamps for when vm is created, and/or when template was created
