### ISSUE TITLE
CloudImage size changes forces replacement of VM

### ISSUE THREAD

**Issue by metaevolution** [bpg/terraform-provider-proxmox#1440]
**Describe the bug**
Change in size of CloudImage after VM creation forces replacement of VMs

**To Reproduce**

1. Define a `proxmox_virtual_environment_download_file` resource.
2. Define a `proxmox_virtual_environment_vm` resource that references cloudimage created by `proxmox_virtual_environment_download_file`.
3. Run `terraform apply` anytime after the remote cloudimage source has been changed will trigger replacement of VMs created using that cloud image.

```hcl

resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image_noble" {
  content_type = "iso"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name
  url = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  overwrite = false
}

resource "proxmox_virtual_environment_vm" "example_vm" {
  name  = "example_vm"
  node_name = var.virtual_environment_node_name
  tags = ["linux"]

  agent {
    enabled = true
  }

  initialization {

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    dns {
      domain = "example.net"
      servers = [
        "192.168.1.1"
      ]
    }
    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }
  memory {
    dedicated = 4096
  }
  cpu {
    cores      = 4
  }
  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_download_file.ubuntu_cloud_image_noble.id
    interface = "virtio0"
    size      = 32
    file_format       = "raw"
  }
  network_device {
    bridge = "evpnvnet"
  }
}


```

**Expected behavior**
VM is not expected to be rebuilt when base cloudimage is later changed by maintainers.

**Screenshots**
<img width="943" alt="Screenshot 2024-07-14 at 6 39 35 PM" src="https://github.com/user-attachments/assets/086e8c12-2d9b-401e-866d-b78760db1f74">

terraform plan output:
```bash
│ Warning: The file size from url has changed.
│
│   with proxmox_virtual_environment_download_file.ubuntu_cloud_image_noble,
│   on main.tf line 52, in resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image_noble":
│   52: resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image_noble" {
│
│ Size from url 585105408 does not match size from datastore: 584843264
```

- Single or clustered Proxmox: single
- Proxmox version: 8.2.4
- Provider version (ideally it should be the latest version):  bpg/proxmox v0.60.1
- Terraform/OpenTofu version: Terraform v1.9.1
- OS (where you run Terraform/OpenTofu from): Ubuntu 22.04.4 LTS (Jammy Jellyfish)
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by elias314** [comment]
This doesn't look like a bug.  This is by design and how Terraform is intended to work.  When Terraform notices that your deployed infrastructure doesn't match what's codified (in this case that the cloud image has changed), its job is to bring your infrastructure back up to date.

To work around this, either version your images, or you can use [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) in a [lifecycle block](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) to tell Terraform not to update your infrastructure when it sees that the cloud image has changed.

**Comment by metaevolution** [comment]
Thanks for the info! Adding `ignore_changes` to the Terraform config resolved my issue. 

```hcl
  lifecycle {
    ignore_changes = [disk,]
  }
```
