### ISSUE TITLE
proxmox_virtual_environment_network_linux_bridge additional config

### ISSUE THREAD

**Issue by bitchecker** [bpg/terraform-provider-proxmox#1454]
**Is your feature request related to a problem? Please describe.**
When you use `proxmox_virtual_environment_network_linux_bridge` you're able to configure as a normal Linux bridge, but sometimes you need to configure a bridge for configure a NAT network for your virtual resources

**Describe the solution you'd like**
When you use `proxmox_virtual_environment_network_linux_bridge` resource will be great to be able to pass also `post-up` and `post-down` configuration useful to configure masquerading

**Comment by bpg** [comment]
The [PVE API](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/network) does not support additional `post-` parameters, unfortunately. I don't think building some shell scripting that would allow injecting additional config (via SSH!) is a feasible solution, too many things could go wrong with that.
