### ISSUE TITLE
Adding VM/container to resource pool when creating

### ISSUE THREAD

**Issue by Ekaums** [bpg/terraform-provider-proxmox#1459]
**Is your feature request related to a problem? Please describe.**
When creating a VM/container, it would be nice to assign it to a resource pool as well

**Describe the solution you'd like**
An additional argument in the resource "proxmox_virtual_environment_vm"/"proxmox_virtual_environment_vm" to specify a resource pool

**Describe alternatives you've considered**
The Proxmox command line allows you to add a VM/container to a pool via `pvesh set /pools/{poolid} -vms {vmid}`, and there is equivalent functionality in the Proxmox API.

**Additional context**
If this functionality already exists, please let me know :)
If not, I would be interested in contributing to working on it!

**Comment by bpg** [comment]
I guess you found [`pool_id`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#pool_id) attribute 🙂
