### ISSUE TITLE
Make user password expired

### ISSUE THREAD

**Issue by Nordal** [bpg/terraform-provider-proxmox#1477]
I am creating users with the user_account resource like this:

user_account {
      keys     = [trimspace(tls_private_key.ubuntu_vm_key.public_key_openssh)]
      password = xxx
      username = "xxx"
    }

Users will fill out a web form, and it will create the user and generate a random password. The password policy in my company requires the initial user password to be one-time.

It would be nice to have an option to set the password as expired, forcing the user to create a new password at first login.

I am sure this can be achieved with "real" cloud-init, but to keep things simple I am using the build in cloud-init support, with the limitations it has.

Thank you for doing a great work with this provider 

BR Kasper

**Comment by bpg** [comment]
Hi @Nordal 👋🏼 

> I am sure this can be achieved with "real" cloud-init, but to keep things simple I am using the build in cloud-init support, with the limitations it has.

You're right in this part. Unfortunately, the provider is very limited in what it can do in the "standard" cloud-init. Basically, it can only configure parameters exposed via PVE APIs:
![Screenshot 2024-08-08 at 9 09 13 PM](https://github.com/user-attachments/assets/939e88bd-b201-4ef1-8eb5-73158a7d5926)


For anything extra operators should provide "real" cloud-init configs via ouser / vendor / meta data files.
