### ISSUE TITLE
Add support for hardware watchdog timers (watchdog:)

### ISSUE THREAD

**Issue by voxxit** [bpg/terraform-provider-proxmox#1508]
**Is your feature request related to a problem? Please describe.**
I would like to add hardware watchdogs to my VMs.

**Describe the solution you'd like**
`watchdog` is an argument available in `/etc/pve/qemu-server/*.conf` files, i.e. `watchdog: model=i6300esb,action=reset`

**Describe alternatives you've considered**
None.

**Additional context**
* https://www.talos.dev/v1.7/advanced/watchdog
* https://forum.proxmox.com/threads/hardware-watchdog-at-a-per-vm-level.104051

Thank you!

**Comment by svengreb** [comment]
[The `watchdog` option is exposed by the Proxmox VE API for VMs][1] so adding support is luckily straight forward, modifying configuration files would be another (bad) story. The option is also [available through the API for configuration updates][2] so this covers the CRUD functionality (delete is always possible through the `delete` array).

![The watchdog option documentation in the Proxmox VE API explorer](https://github.com/user-attachments/assets/839c653c-cb92-47df-8d1a-515f9f8417dd)


[1]: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu
[2]: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config
