### ISSUE TITLE
Support `bzip2` decompression algorithm in `pve_download_file`

### ISSUE THREAD

**Issue by jmuchovej** [bpg/terraform-provider-proxmox#1513]
**Is your feature request related to a problem? Please describe.**
Yes. `bzip2` compressed ISOs cannot be downloaded/used to complete the full VM creation pipeline via Terraform. (Here's a [link to the OPNSense ISO][opnsense-iso] I was trying to use.)

[opnsense-iso]: https://mirror.dns-root.de/opnsense/releases/mirror/OPNsense-24.7-vga-amd64.img.bz2

**Describe the solution you'd like**
Clarity on whether the limitations of `decompression_algorithm` are imposed by the provider or the Proxmox API? (Perusing the [Proxmox API][proxmox-api], it seems like the API doesn't impose such limitations? It also appears that [Go natively supports `bzip2`][go-support] [de]compression?)

[proxmox-api]: https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/%7Bnode%7D/storage/%7Bstorage%7D/download-url
[go-support]: https://pkg.go.dev/compress/bzip2

**Describe alternatives you've considered**
There aren't really any? OPNSense only appears to ship `bz2` image files and I'm not going to rebuild the provider from scratch just to support this. 😅

*I'm happy to contribute, but I'm a Go novice and am unsure where the decompression is handled, based on [`download_url.go`][file] – perhaps Proxmox itself does this?*

[file]: https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/nodes/storage/download_url.go

**Comment by jmuchovej** [comment]
Ah! I didn't realize that this was actually limited by Proxmox! Feel free to close.
![CleanShot 2024-08-25 at 16 48 16](https://github.com/user-attachments/assets/3ada22cd-fdbc-4f88-8945-6f1a101ad054)

**Comment by QlemWasTaken** [comment]
Hi,

Proxmox 8.3 was published 2 days ago, and it comes with built-in support for bzip2 algorithm.

> The ISO upload functionality now supports images compressed with bzip2 (see [changelog](https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_8.3))

The code changes seem minor. I’ve made it work on my small infra with own fork/branch. However, I’ve never pushed code to someone else repository so I’m not clear how to do it.

I reopened this issue as it was recent, tell me if you need me to create another one.

**Comment by bpg** [comment]
Hey @QlemWasTaken 👋🏼

Yeah, it should be straightforward to support now, on PVE 8.3

If you push your changes to your fork, it will be easy to create a PR from the GitHub UI. But there are a few conventions for this repo that you'd have to follow, take a look here: https://github.com/bpg/terraform-provider-proxmox/blob/main/CONTRIBUTING.md#coding-conventions

And don't worry if the PR won't be pretty or produce some errors, I'll help you to sort everything out.

Thanks for contributing! ❤️
