### ISSUE TITLE
Raw device disk passthrough instead of datastore

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [bpg/terraform-provider-proxmox#1525]
**Is your feature request related to a problem? Please describe.**
Not sure if this is already implemented or not, but I need to create a VM that gets a HDD passed through directly from hardware to the VM. I'm not sure how to achieve this using the provider. If it's already a feature can you point me to the documentation?

**Describe the solution you'd like**
To learn how to have a raw unpartitioned HDD attached to a VM

**Comment by otopetrik** [comment]
That should work, see: https://github.com/bpg/terraform-provider-proxmox/issues/473#issuecomment-1873695427, unfortunately it looks like it is not documented. Documentation has only [example for using disks from other VMs](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#example-attached-disks).

**Comment by bpg** [comment]
@luis-guimaraes-exoawk Could you check if that solution works for you, and report back?

**Comment by huwany** [comment]
@bpg the https://github.com/bpg/terraform-provider-proxmox/issues/473#issuecomment-1873695427 works. but need to ignore the `size` and `file_format` life changes manually.
