### ISSUE TITLE
Lack of interaction between vlan & bridge

### ISSUE THREAD

**Issue by Tristan-GG** [bpg/terraform-provider-proxmox#1531]
**Describe the bug**
Lack of interaction between proxmox_virtual_environment_network_linux_vlan & proxmox_virtual_environment_network_linux_bridge

The Proxmox provider (BPG) currently does not support creating VLAN interfaces with custom names, such as `VMNetPrivateGRA.10`, and using these custom-named VLAN interfaces in bridges. This limitation makes it difficult to implement custom network naming conventions required in complex environments.

Currently, the provider only supports VLANs using the default naming convention `interface.vlan_id` (e.g., `enp10s0f1np1.10`), which limits the ability to use custom names for VLAN interfaces.

**To Reproduce**

1. Create a resource 'proxmox_virtual_environment_network_linux_vlan'  with a custom vlan name & create a ressource 'proxmox_virtual_environment_network_linux_bridge' and put this brige on the vlan
2. Run 'terraform apply'
3. See error : 

│ Error: Error reloading network configuration
│
│ with proxmox_virtual_environment_network_linux_bridge.GRA,
│ on main.tf line 76, in resource “proxmox_virtual_environment_network_linux_bridge” “GRA”:
│ 76: resource “proxmox_virtual_environment_network_linux_bridge” “GRA” {
│
│ Could not reload network configuration on node 'ns31720262', unexpected
│ error: failed to reload network configuration for node “ns31720262”: All
│ attempts fail:
│ #1: timeout while waiting for task
│ “UPID:ns31720262:000307B1:007A51FA:66E1519A:srvreload:networking:root@pam:”
│ to complete

4. Modify the resource 'proxmox_virtual_environment_network_linux_vlan ' and configure with vlan tag
5. Run 'terraform apply'

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

# >>> 
resource "proxmox_virtual_environment_network_linux_vlan" "vlan10" {
  depends_on = [ovh_dedicated_server_install_task.server_install]
  node_name = var.node_name
  name           = "VMNetPrivateGRA"
  interface      = "enp10s0f1np1"
  vlan              = 10
}

resource "proxmox_virtual_environment_network_linux_bridge" "GRA" {
  depends_on = [proxmox_virtual_environment_network_linux_vlan.vlan10]
  node_name = var.node_name
  name           = "vmbr10"
  ports = [
    "VMNetPrivateGRA.10" # Obviously this doesn't work with enp10s0f1np1.10
  ]
}
 <<< #

```

**Expected behavior**
Users should be able to create custom-named VLAN interfaces and use these custom interfaces in network bridges. For example:
resource "proxmox_virtual_environment_network_linux_vlan" "vlan10" { node_name = var.node_name name = "VMNetPrivateGRA" interface = var.network_interface vlan = 10 }

resource "proxmox_virtual_environment_network_linux_bridge" "GRA" { depends_on = [proxmox_virtual_environment_network_linux_vlan.vlan10] node_name = var.node_name name = "vmbr10" ports = ["VMNetPrivateGRA.10"] }

**Screenshots**
<img width="339" alt="Capture d'écran 2024-09-11 110314" src="https://github.com/user-attachments/assets/4e83b735-8cf7-4279-b07e-1ea7221c9aec">

**Additional context**

- Single or clustered Proxmox: single
- Proxmox version: 8.2.4
- Provider version (ideally it should be the latest version): 0.64.0
- Terraform/OpenTofu version: Terrafom 1.8.4
- OS (where you run Terraform/OpenTofu from): CentOS 7
- Debug logs (`TF_LOG=DEBUG terraform apply`):  sensitive data

**Comment by bpg** [comment]
Hey @Tristan-GG,

When you're creating a bridge using a VLAN interface with a _custom name_ **and** a _VLAN ID_, you don't need to add the VLAN suffix to the interface name when referencing it in the bridge ports. That's because the VLAN ID is already set explicitly on the VLAN interface.

So, you can rewrite your config like this:
```hcl
resource "proxmox_virtual_environment_network_linux_vlan" "vlan10" {
  depends_on = [ovh_dedicated_server_install_task.server_install]
  node_name = var.node_name
  name           = "VMNetPrivateGRA"
  interface      = "enp10s0f1np1"
  vlan           = 10
}

resource "proxmox_virtual_environment_network_linux_bridge" "GRA" {
  depends_on = [proxmox_virtual_environment_network_linux_vlan.vlan10]
  node_name = var.node_name
  name           = "vmbr10"
  ports = [
    "VMNetPrivateGRA"
  ]
}
```

This is basically the same as the config with the VLAN suffix:
```hcl
resource "proxmox_virtual_environment_network_linux_vlan" "vlan10" {
  depends_on = [ovh_dedicated_server_install_task.server_install]
  node_name = var.node_name
  name      = "enp10s0f1np1.10"
}

resource "proxmox_virtual_environment_network_linux_bridge" "GRA" {
  depends_on = [proxmox_virtual_environment_network_linux_vlan.vlan10]
  node_name = var.node_name
  name           = "vmbr10"
  ports = [
    "enp10s0f1np1.10"
  ]
}
```

Could you give it a try and let me know if it works for?

**Comment by Tristan-GG** [comment]
Hello,

Yes, it works, thank you very much.
It might be relevant to add a line on the resource doc: proxmox_virtual_environment_network_linux_bridge because it is not specified and is confusing I think. (maybe it's just me after all 😄).

In any case, thank you for your responsiveness and your work on this provider 🔥
