### ISSUE TITLE
hostpci always gets updated to same value if set (if more than 4)

### ISSUE THREAD

**Issue by aamkye** [bpg/terraform-provider-proxmox#1541]
**Describe the bug**
While having more than `hostpci` blocks in `proxmox_virtual_environment_vm` resource, anything above 4 blocks tries to update even if the same and already set (observed even on import).

**To Reproduce**

1. Import/create VM with more than 4 `hostpci` blocks in `proxmox_virtual_environment_vm` resource.

```hcl
resource "proxmox_virtual_environment_vm" "test" {
  vm_id     = 100
  node_name = "test"
  name      = "test.test"

  hostpci {
    device  = "hostpci0"
    ...
  }

  hostpci {
    device  = "hostpci1"
    ...
  }

  hostpci {
    device  = "hostpci2"
    ...
  }

  hostpci {
    device  = "hostpci3"
    ...
  }

  hostpci {
    device  = "hostpci4"
    ...
  }

  hostpci {
    device  = "hostpci5"
    ...
  }

  hostpci {
    device  = "hostpci6"
    ...
  }

  hostpci {
    device  = "hostpci7"
    ...
  }

  hostpci {
    device  = "hostpci8"
    ...
  }
}

```

**Expected behavior**
Everything applies as expected and the state is updated to corespondent state.

**Screenshots**
![CleanShot 2024-09-18 at 23 25 51](https://github.com/user-attachments/assets/9efc9afc-2c6b-4208-8451-02eb36af3626)

**Additional context**

- Single or clustered Proxmox: Single
- Proxmox version: 8.2.4
- Provider version (ideally it should be the latest version): bpg/proxmox v0.64.0
- Terraform/OpenTofu version: 
- OS (where you run Terraform/OpenTofu from): TF 1.8.5
- Debug logs (`TF_LOG=DEBUG terraform apply`):

<details><summary>Toggle me!</summary>

![CleanShot 2024-09-18 at 23 38 18](https://github.com/user-attachments/assets/955f6a0e-2d96-4bfa-828d-d7a861028679)

```shell
https://pastebin.com/09jXN4R0
```

</details>

**Comment by bpg** [comment]
Hey @aamkye! 👋🏼 

Thanks for the report. Should be [relatively easy](https://github.com/bpg/terraform-provider-proxmox/blob/f4ee6291ccd42ef6c6c7d0e8d6780f68a46ac218/proxmoxtf/resource/vm/vm.go#L5527-L5536) to fix.

**Comment by bpg** [comment]
Based on `/usr/share/perl5/PVE/QemuServer/PCI.pm`, the maximum number of `hostpci` devices is 16, so it will be better to fix this properly, rather than hardcoding 16 fields
