### ISSUE TITLE
datasource proxmox_virtual_environment_vms - strange behaviour when filtering using tags

### ISSUE THREAD

**Issue by camaeel** [bpg/terraform-provider-proxmox#1577]
**Describe the bug**
I have VM with 2 tags: ABC, DEF.
When I create data source like:
```
data "proxmox_virtual_environment_vms" "source-templates" {
  tags = [ "ABC",
     "DEF"]
}
```
this VM is not found. 

To find it I have to specify resource like this
```
data "proxmox_virtual_environment_vms" "source-templates" {
  tags = [ "ABC,DEF"]
}
```
so tags need to be concatenated in alphabetical order in order to select VM

**To Reproduce**
1. create VM with 2 tags
2. try to create datasource that will select this VM by tags

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
data "proxmox_virtual_environment_vms" "source-templates" {
  tags = [ "ABC,DEF"]
}
```

**Expected behavior**
Documentation states that it is enough to provide list off tags like this:
```
[ "ABC", "DEF"]
```

**Screenshots**

**Additional context**

- Single or clustered Proxmox: single
- Proxmox version: 8.2.7
- Provider version (ideally it should be the latest version): 0.66.1
- Terraform/OpenTofu version:
- OS (where you run Terraform/OpenTofu from):
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by bpg** [comment]
PVE automatically lowercase tags. This use case works:

VM:
<img width="1093" alt="Screenshot 2024-10-09 at 7 53 39 PM" src="https://github.com/user-attachments/assets/6d03fb7f-597f-4362-936c-dc98e75df8bd">

config:
```hcl
data "proxmox_virtual_environment_vms" "test" {
  tags = [ "abc", "def" ]
}

output "vms" {
  value = data.proxmox_virtual_environment_vms.test.vms
}
```

`tofu apply -auto-approve`
```
❯ tofu apply -auto-approve
data.proxmox_virtual_environment_vms.test: Reading...
data.proxmox_virtual_environment_vms.test: Read complete after 0s [id=fae91e9a-8762-4d9f-a053-6b3aa2a1747a]

Changes to Outputs:
  + vms = [
      + {
          + name      = "VM 100"
          + node_name = "pve"
          + status    = "stopped"
          + tags      = [
              + "abc",
              + "def",
            ]
          + template  = false
          + vm_id     = 100
        },
    ]

You can apply this plan to save these new output values to the OpenTofu state, without changing any real infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vms = tolist([
  {
    "name" = "VM 100"
    "node_name" = "pve"
    "status" = "stopped"
    "tags" = tolist([
      "abc",
      "def",
    ])
    "template" = false
    "vm_id" = 100
  },
])
```

@camaeel could you try your tags filter in lowercase and see if it works?
If it still doesn't could you post output of `qm config <your vm id>` (run in PVE shell) pls?

**Comment by camaeel** [comment]
@bpg 
Thanx, it seems it works for me as well. 
No idea what was the issue, I change the code and the setup since then.
