### ISSUE TITLE
cannot provision VMs after changing DNS setting

### ISSUE THREAD

**Issue by gorgonzola5000** [bpg/terraform-provider-proxmox#1582]
After provisioning a VM with:
```
dns {
  servers = ["10.2.137.1"]
}
```
I cannot provision any VMs. Independent of dns block presence in the plan. VM creation fails during `terraform apply`:

Error message:
```
#1: received an HTTP 400 response - Reason: Parameter verification failed. (name: invalid format - value does not look like a valid DNS name)
```

My config file (notice no 'dns' block inside 'initialization' block). VM creation still fails
```
resource "proxmox_virtual_environment_vm" "debian_12_homelab" {
  name        = "debian_12_homelab"
  description = "Managed by Terraform"
  tags        = ["terraform", "debian"]

  node_name = "pve"
  vm_id     = 222

  agent {
    # read 'Qemu guest agent' section, change to true only when ready
    enabled = true
  }
  # if agent is not enabled, the VM may not be able to shutdown properly, and may need to be forced off
  stop_on_destroy = true

  disk {
    datastore_id = "local-lvm"
    file_id      = "local:iso/debian12-homelab-qcow2.iso"
    interface    = "scsi0"
    size         = 20
  }

  initialization {
    ip_config {
      ipv4 {
        address = "10.2.137.11/24"
        gateway = "10.2.137.1"
      }
    }

  }

  network_device {
    bridge = "vmbr0"
  }
}
```

My setup:
- Linux 6.11.2-arch1-1 kernel
- opentofu 1.8.2-1/terraform-1.9.6-1 (tested both)
- bpg/proxmox 0.66.1 (tested 0.64.0 too)
 
I set up bpg/proxmox provider with:
- 'terraform' user in PVE realm
- SSH connection

What I did to resolve the issue:
- clean reinstall of proxmox (then only added users, ssh keys, `apt update && apt upgrade`)
- reinstall of terraform binary
- cleared the whole directory of state files etc.
- checked on a completely different host running Alma Linux 9

terraform DEBUG log dump: https://pastebin.com/KrmN5W55
log dump from /var/log/pveproxy: https://pastebin.com/jTYqD2yB

**Comment by gorgonzola5000** [comment]
`#1: received an HTTP 400 response - Reason: Parameter verification failed. (name: invalid format - value does not look like a valid DNS name)` - coincidentally, I changed the dns block inside the initialization block when this error message started appearing. I became so fixated on 'DNS' that I just glanced over 'name: invalid format'. I was so hopeless that I even started looking into Proxmox source code to find the [function which checks if a DNS name is valid](https://git.proxmox.com/?p=pve-common.git;a=blob;f=src/PVE/JSONSchema.pm;hb=aeff857f77130352f18e67d57df838602ab128d0#l554) and the exact regex used for validation. Only after this I managed to spot the error - '_' instead of '-' in 'name' of the VM.

**Comment by dh0169** [comment]
Hello, I had the same issue and was able to resolve it by changing '_' to '-'. However I'm not sure why this affects the deployment, does the provider try to parse strings with "_" as domain names?

**Comment by gorgonzola5000** [comment]
> Hello, I had the same issue and was able to resolve it by changing  '\_' instead of '-' in 'name' of the VM. However I'm not sure why this affects the deployment, does the provider try to parse strings with '\_' as domain names?

hi, this is how Proxmox (or even KVM/QEMU - I'm not sure) handles the VM names. They need to be valid DNS names
