### ISSUE TITLE
Loading file from backup

### ISSUE THREAD

**Issue by EugenMayer** [bpg/terraform-provider-proxmox#1617]
env:
- proxmox 8.2.7
- bgp/proxmox: 0.66.3

The following definition fow a proxmox_virtual_environment_file

```hcl
resource "proxmox_virtual_environment_file" "dummy_backup" {
  content_type = "dump"
  datastore_id = "remote-backup"
  node_name    = "proxmox"

  source_file {
    path = "vzdump-qemu-999-2024_11_02-12_29_42.vma"
  }
}
```

this is the filename
```bash
ls -la /mnt/pve/remote-backup/dump | grep 999 | grep vma
-rwxrwxrwx 1 root root   3447566848 Nov  2 12:30 vzdump-qemu-999-2024_11_02-12_29_42.vm
```

the storage config

![image](https://github.com/user-attachments/assets/bdf260ad-84d8-4524-9c8c-2be7f909d1bc)

When applying the resource, i get

```bash
│ Error: open vzdump-qemu-999-2024_11_02-12_29_42.vma: no such file or directory
│ 
│   with proxmox_virtual_environment_file.dummy_backup,
│   on test.tf line 8, in resource "proxmox_virtual_environment_file" "dummy_backup":
│    8: resource "proxmox_virtual_environment_file" "dummy_backup" {
```

Anything i misunderstood in this regard? Used https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#backups-dump as my guide

Thanks

**Comment by bpg** [comment]
Hey @EugenMayer 👋🏼 

I’m not entirely clear on the use case, are you trying to download a backup file from PVE to your local machine, or upload a backup file to PVE?

The doc you referenced is indeed a bit sparse and may not be very helpful. We can definitely work on improving it to make it more useful.

**Comment by EugenMayer** [comment]
Hey @bpg 

the backup is located on a mounted NFS volume, you might be able to see it in the screenshot. For promox, this is just a common backup from a local folder, see the shell output i provided ( the ls ).

My goal is to restore a disk from a backup

**Comment by bpg** [comment]
Well, the `proxmox_virtual_environment_file` resource allows you to "create" a file in PVE, which in this context means uploading a backup file to PVE storage. Which might not be particularly useful in your use case.

The provider does not support restore from a backup at the moment.

**Comment by EugenMayer** [comment]
Sorry, i assume i simply misunderstood this then. May i close the ticket?
