### ISSUE TITLE
Context: Deadline Exceeded before clone_timeout

### ISSUE THREAD

**Issue by tyxieblub** [bpg/terraform-provider-proxmox#1621]
**Describe the bug**

While cloning a VM with a somewhat large disk, I'm hitting a 20min timeout (Context: Deadline Exceeded), while `timeout_clone` defaults to `1800` (30min).

I think it is because 20mins is the default and the deadline is never cancelled before applying the `timeout_clone` value.

I tried replacing this line (in `vmCreateClone(...)`):

```go
ctx, cancel := context.WithTimeout(ctx, time.Duration(cloneTimeoutSec)*time.Second)
```

with this

```go
ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), time.Duration(cloneTimeoutSec)*time.Second)
```

and it seems to work correctly, the disk took 35mins to clone (I had `timeout_clone` at `3600`).

Here is the interesting part of the context before the change:

```
WithDeadline(2024-11-05 16:39:43.75721 +0100 CET m=+1200.039349710 [19m59.999865875s])
```

After the change:

```
WithDeadline(2024-11-05 16:43:28.700545 +0100 CET m=+1200.040166668 [19m59.999876084s]).WithoutCancel.WithDeadline(2024-11-05 17:23:28.700629 +0100 CET m=+3600.040250793 [59m59.999959667s])
```

While this works I'm unsure if this is the right way to correct it, and if this is something that should be done on all updated contexts with deadlines (like `timeout_create`). If it looks ok to you, I can open a PR.

**To Reproduce**

Clone a VM with a large enough disk to hit the 20min deadline on your infra.

**Comment by bpg** [comment]
Thanks @tyxieblub, good find!

You're right about the [default `create` timeout](https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.35.0/helper/schema/resource_data.go#L418).

I believe you can mitigate your error by increasing it in the VM resource using the [`timeouts` block](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts), which doesn't require a code change:

```hcl
timeouts {
  create = “60m”
}
```

I don't like the fact that there are multiple ways to set timeouts. I don’t think the VM resource should have, for example, `timeout_create`, nor do I see a particular need for specific "migrate" or "clone" timeouts. However, they all come from legacy code, and I don’t want to break compatibility now, as these fields might still be in use.

Let me think about it... I'll probably go ahead and implement the fix you've suggested — it makes sense in this context.

**Comment by tyxieblub** [comment]
Hello!

Thanks for the fix, I'll test it next time I have a big VM to clone!
