### ISSUE TITLE
connection reset by peer  when creating new machines from templates

### ISSUE THREAD

**Issue by valkiriaaquatica** [bpg/terraform-provider-proxmox#1624]
**Describe the bug**
Probably is a network error, but this error does not happen with other proxmox providers..
Having correct credentials, user, endpoint, connectivity after the terrraform apply the it does not connect to proxmox and throws this errror

_│ Error: error waiting for VM clone: All attempts fail:
│ #1: error cloning VM: failed to authenticate HTTP POST request (path: nodes/pve/qemu/197/clone) - Reason: failed to authenticate: failed to retrieve authentication response: Post "https://ip_proxmox:8006/api2/json/access/ticket": read tcp my_ip:57402->prox,px_node_ip:8006: read: connection reset by peer_

Probably os because I am using a VPN to access the network where there are also palo alto firewalls that maybe is making the golang backend to not work because doing the SAME POST request with CURL works well.  So i guess is someathinw with the way golang executes it?

**To Reproduce**
have a template machine to clone from 
try to clone with this main.tf
```
resource "proxmox_virtual_environment_vm" "dns" {
  name        = var.vm_name
  description = var.vm_description
  node_name   = var.node_name
  vm_id       = var.vm_id
  tags        = var.vm_tags

  agent {
    enabled = var.agent_enabled
  }

  cpu {
    cores   = "2"
    sockets = "1"
    type    = var.cpu_type
  }

  memory {
    dedicated = "4096"
  }

  operating_system {
    type = var.os_type
  }

  disk {
    datastore_id = var.disk_datastore_id
    file_format  = var.disk_file_format
    interface    = var.disk_interface
    size         = var.disk_size
  }


  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  clone {
    vm_id = var.clone_vm_id 
    full  = var.clone_full
  }
}

```
Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
Using latest terraformversion and bgp latest versionn provider

```

**Expected behavior**
Create the virtual machine and resize the disk, the problem is the connection.

**Screenshots**
The errro above

**Additional context**
POST request with curl is done correctly but with terraform not(error above).

- Single or clustered Proxmox: Clustered two nodes
- Proxmox version: 8.2.2
- Provider version (ideally it should be the latest version): Latest
- Terraform/OpenTofu version: Latest version
- OS (where you run Terraform/OpenTofu from): Ubuntu22 WSL

**Comment by bpg** [comment]
Hey @valkiriaaquatica 👋🏼 

I really don't have much details from the issue to do any debugging. If you could try running Wireshark to inspect traffic between the provider and PVE, it may give you some details on why connection is getting reset. My best guess it could be related to TLS inspection done by your network equipment. Are you testing with curl from WSL, or from Windows? WSL may not have all necessary palo alto certs...

**Comment by valkiriaaquatica** [comment]
Hi, I'm sorry I didn't complete it. It was as I said (as a summary) problem with Palo Alto firewall , the  main problem was that with the "generic" error output was difficult to troublehoot. I tried with other domains with similar TLS certs and had the same. I close it due to NOT  a problem with the provider but a problem with Palo Alto .

Thanks!!
