### ISSUE TITLE
Add support for xz decompression

### ISSUE THREAD

**Issue by heckface** [bpg/terraform-provider-proxmox#1680]
I am attempting to create Talos VMs from an image that is compressed with xz utils. Unfortunately the decompression_algorithm does not accept xz as a decompression utility according to https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_download_file. 

I would love to see xz added as an option for decompression_algorithm if/when possible.

**Comment by bpg** [comment]
Hey @heckface 👋🏼  

The [`virtual_environment_download_file`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_download_file) resource leverages the server-side file download feature [provided by Proxmox](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/download-url).  

As a result, the provider is constrained to the list of compression algorithms supported by PVE, e.g.:  
![PVE Compression Algorithms](https://github.com/user-attachments/assets/841e7bb6-bc10-40bf-bd68-ad3cacc2a2aa)
