### ISSUE TITLE
proxmox_virtual_environment_vm does not use proper path from proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by fpicot** [bpg/terraform-provider-proxmox#187]
**Describe the bug**
Following the VM creation example with a .tar.xz image as a source fails, the VM creation does not use the correct path for the file. 

**To Reproduce**
With the following TF resources, run terraform apply : 
```
resource "proxmox_virtual_environment_file" "debian_cloud_image" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = var.proxmox_node_name

  source_file {
    path = "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-genericcloud-amd64-daily.tar.xz"
  }
}
resource "proxmox_virtual_environment_vm" "reproduce_bug" {
  name        = "reproduce_bug"
  started     = true

  node_name = var.proxmox_node_name
  vm_id     = random_integer.vmid.result

  disk {
    datastore_id = "local"
    file_format  = "qcow2"
    interface    = "scsi0"
    file_id      = proxmox_virtual_environment_file.debian_cloud_image.id
    size         = "10"
  }
}
```

**Expected behavior**
The VM is created using the correct image. 

**Actual behavior**
The creation fails with the following error:
```Error: cp: cannot stat '/var/lib/vz/vztmpl/debian-12-genericcloud-amd64-daily.tar.xz': No such file or directory```

**Additional context**
Looking at the created resource, it appears that proxmox_virtual_environment_vm is using the id as if it was the path relative to datastore root. However, inspecting the storage shows it is not the case:
```
# pvesm path local:vztmpl/debian-12-genericcloud-amd64-daily.tar.xz 
/var/lib/vz/template/cache/debian-12-genericcloud-amd64-daily.tar.xz
```

**Comment by bpg** [comment]
This really gnarly code is responsible for disk creation: https://github.com/bpg/terraform-provider-proxmox/blob/3c02cb13895f7095ef0b0aaf58fe799e396a0715/proxmoxtf/resource_virtual_environment_vm.go#L1993-L2016

It doesn't know anything about special handling of `vztmpl` content type 😞. Without much of unit tests any change there is kind of open heart surgery, but let me see what can be done. It seems that `pvesm` can replace most of the custom `getdsi()` logic over there, so I have some hope.

I would really appreciate any help with testing the fix when it will be available, on as many different storage types as possible.

**Comment by bpg** [comment]
Hi @fpicot! 👋🏼 
I think #241 should fix this particular issue, although i'm not sure if the image you're trying to create VM from is the right one. I wasn't able to boot the VM using a "raw" disk from that image. 
Have you had any success with any of non-qcow2 images for VMs on proxmox?
