### ISSUE TITLE
Unable to create VM using raw, xz compressed cloud image

### ISSUE THREAD

**Issue by fpicot** [bpg/terraform-provider-proxmox#188]
**Describe the bug**
When using raw, xz compressed cloud image, the VM creation fails no matter which disk format is specified

**To Reproduce**
With the following resource, run terraform apply:
``` 
resource "proxmox_virtual_environment_vm" "reproduce_bug" {
  name        = var.vm_name
  started     = true

  node_name = var.proxmox_node_name
  vm_id     = random_integer.vmid.result

  disk {
    datastore_id = "local"
    file_format  = "raw"
    interface    = "scsi0"
    file_id      = proxmox_virtual_environment_file.debian_cloud_image.id
    size         = "10"
  }
}
```

**Expected behavior**
VM created using the specified image (in this case : https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-genericcloud-amd64-daily.tar.xz)

**Actual behavior**
The creation fails: 
* if file_format is set to raw, there is an extension handling issue, and the output is : 
``` 
│ Error: WARNING: Image format was not specified for '/tmp/vm-487-disk-0.raw' and probing guessed raw.
│          Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
│          Specify the 'raw' format explicitly to remove the restrictions.
│ Image resized.
│ unable to parse volume filename '487/vm-487-disk-0.qcow2.qcow2'
```
* if file_format is set to qcow2, there is an extension handling issue, and the output is :  
```
│ Error: WARNING: Image format was not specified for '/tmp/vm-487-disk-0.qcow2' and probing guessed raw.
│          Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
│          Specify the 'raw' format explicitly to remove the restrictions.
│ Image resized.
│ qemu-img: Could not open '/tmp/vm-487-disk-0.qcow2': Image is not in qcow2 format
│ copy failed: command '/usr/bin/qemu-img convert -p -n -f qcow2 -O qcow2 /tmp/vm-487-disk-0.qcow2 zeroinit:/var/lib/vz/images/487/vm-487-disk-0.qcow2' failed: exit code 1
│ unable to parse volume filename '.qcow2'
```

**Additional context**

**Comment by bpg** [comment]
Hey @fpicot, thanks for the report! Could you please check if there is any error in the PVE UI reported at the same time?
I was running a similar test I got this in PVE while provider reported `unable to parse volume filename '.qcow2'` error:

<img width="1414" alt="Screenshot 2022-12-19 at 10 15 25 AM" src="https://user-images.githubusercontent.com/627562/208459083-0e1a58f7-7ae0-4393-852c-a9fa8c963dfa.png">

**Comment by fpicot** [comment]
Hello @bpg, 

Sorry for the late response, I haven't had a chance to look at this in a while! Unfortunately no, I don't have any error in the console with either format.
