### ISSUE TITLE
Supporting token auth

### ISSUE THREAD

**Issue by pawandubey** [bpg/terraform-provider-proxmox#190]
**Is your feature request related to a problem? Please describe.**
Proxmox has a concept of [API Tokens](https://pve.proxmox.com/pve-docs/chapter-pveum.html#pveum_tokens) that provide stateless access to the REST API. Over using password-auth for accessing the API, tokens can offer some benefits:
- Much simpler auth workflow (as it is stateless)
- More security as the user credentials are never exposed and tokens can have separated permissions from the user who creates them.

It would be nice to have the option to use token auth, in addition to the password based auth already present - this is not an argument for one over the other. Wanted to get a feeler out to see how you feel about it? I am open to actually adding support for it. I understand that some of the API may not be accessible using API Tokens, but the Proxmox documentation is vague about it so I am not sure where the edges are.

**Describe the solution you'd like**
The provider supports authenticating via API tokens. The declaration may look like:

```hcl
provider "proxmox" {
  virtual_environment {
    endpoint = "https://10.0.0.2"
    username = "apiuser@pam"
    token_id = "apitokenname"
    token_secret = "337e5340-6485-43d6-a0f6-7c4d3ceda74d" # or sourced from an env var or variable
    insecure = true
  }
}
```
This will translate into API requests of the form:
```
curl -k https://10.0.0.2/ -H 'Authorization: PVEAPIToken=apiuser@pam!apitokenname=337e5340-6485-43d6-a0f6-7c4d3ceda74d
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bpg** [comment]
Hey @pawandubey! This is a reasonable request for sure, and I'd love to see token-based auth supported by the provider.
Unfortunately, this can't be easily implemented, as we heavily dependent on ability to execute PVE commands over ssh. Particularly, in one key area -- the VM disks import: https://github.com/bpg/terraform-provider-proxmox/blob/3c02cb13895f7095ef0b0aaf58fe799e396a0715/proxmoxtf/resource_virtual_environment_vm.go#L1991-L2028

I don't know all details why this specific approach of dealing with disks was chosen by the original plugin authors, probably due to the lack of some specific functionality from the PVE REST API.

**Comment by pawandubey** [comment]
Hey @bpg Thanks for the response! I took a deeper look into the current state of the API just now. 

It does look like there is [now an API for importing VM disks](https://github.com/proxmox/qemu-server/commit/e6ac9fed7bd214844c3c5a94b7a33b22d46c9706), but there are some rough edges it seems given what another person ran into while implementing the feature in the Telmate provider: https://github.com/Telmate/terraform-provider-proxmox/issues/605#issuecomment-1305956180

Apart from that it still seems like creating snippets is not yet supported in the API.

So overall, there probably won't be a way to support all of the features with the token yet. I think it might be possible to remove the VM disk limitation now with some effort, but that should be tracked in a separate issue.

I'll close this issue for now, and maybe come back to it if/when the API matures. Thank you for this project nonetheless!
