### ISSUE TITLE
unable to parse volume filename `id/vm-id-disk-x.qcow2.qcow2`

### ISSUE THREAD

**Issue by 0c370t** [bpg/terraform-provider-proxmox#203]
**Describe the bug**
As a note; this is using an upstream wrapper; and I have also filed [an issue there](https://github.com/muhlba91/pulumi-proxmoxve/issues/24); however, I believethe issue likely stems here.
I'm interacting with this using [Pulumi](https://www.pulumi.com/), not terraform directly.

When attempting to create a VM Template with a Cloud Init drive, I am given the following error:
```
  proxmoxve:VM:VirtualMachine (Debian Cloud Template Template Virtual Machine):
    error: 1 error occurred:
        * creating urn:pulumi:infra::homelab-infrastructure::HomeLab:Proxmox:CloudImageTemplate$proxmoxve:VM/virtualMachine:VirtualMachine::Debian Cloud Template Template Virtual Machine: 1 error occurred:
        * Image resized.
    unable to parse volume filename '10000000/vm-10000000-disk-0.qcow2.qcow2'
```

I've put the relevant code here:
https://gist.github.com/0c370t/1fbaecbbbb32d18d7a9207e07c8b1e5b

**To Reproduce**
1. Download a qcow2 disk ( i.e. [Debian 10 Generic Cloud AMD64](https://cdimage.debian.org/cdimage/cloud/buster/20221224-1239/debian-10-genericcloud-amd64-20221224-1239.qcow2) )
1. Load that into `/your/storage/root/qcow2`
1. Create a VM with some drive `scsi0`
```json
{
    "interface": "scsi0",
    "datastoreId": "local",
    "fileId": "local:qcow2/debian-genericcloud.qcow2"
}
```
1. See error

**Expected behavior**
I expected the VM to be created without errors.

**Additional context**
It looks like the disk and the VM are getting _created_, it just isn't getting mounted / attached; see the screenshot:
![image](https://user-images.githubusercontent.com/10779616/211340527-0473dde1-4c66-4a14-9121-9add66881d80.png)

To fix this in the UI, it is simply a matter of hitting "Add"

**Comment by 0c370t** [comment]
Update: this might be a duplicate of #188

**Comment by 0c370t** [comment]
Another update: I'm not fluent in go, but I think the issue may be caused here:
https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmoxtf/resource_virtual_environment_vm.go#L2124

if `$dsp_target` includes the file extension already, this adds a redundant `.qcow2` that seems to come up in the bug

**Comment by bpg** [comment]
Hi @0c370t, thanks for the report!
#187 is also seems to be related. My intention is to replace that custom shell scripting with a `pvesm` call, which should be more reliable.
