### ISSUE TITLE
Support LXC nesting property

### ISSUE THREAD

**Issue by Tumetsu** [bpg/terraform-provider-proxmox#250]
My Wireguard/PiVPN container fills my host syslog with following logs:
```
Mar 07 19:00:28 korppi kernel: audit: type=1400 audit(1678208428.390:34877): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-101_</var/lib/lxc>" name="/run/systemd/unit-root/proc/" pid=707813 comm="(d-logind)" fstype="proc" srcname="proc" flags="rw, nosuid, nodev, noexec"
```
After some googling this apparently has to do with running the container as privileged vs. unprivileged. In addition to my understanding, nesting feature should be on too. See for example this discussion: https://discuss.linuxcontainers.org/t/apparmor-denied-operation-mount/2424/18

After consulting the docs for `unprivileged = true` option and adding it to my TF script, the container seems to be created with following config:
```
pct config 101
arch: amd64
cmode: tty
console: 1
cores: 1
cpuunits: 1024
description: "Managed by TF"
hostname: pivpn.home.arpa
memory: 256
nameserver: 1.1.1.1
net0: name=eth0,bridge=vmbr0,gw=10.0.10.1,hwaddr=...,ip=...,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-101-disk-0,size=4G
searchdomain: home.arpa
swap: 0
template: 0
tty: 2
unprivileged: 1
```
where as if I manually create LXC container via GUI, the config is as follows. Note feautre nesting=1:
```
pct config 103
arch: amd64
cores: 1
features: nesting=1
hostname: testi
memory: 512
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=9E:75:D2:D4:2B:E5,ip=dhcp,type=veth
ostype: debian
rootfs: local-lvm:vm-103-disk-1,size=8G
swap: 512
unprivileged: 1
```

This closed issue https://github.com/bpg/terraform-provider-proxmox/issues/224 seems to talk about nesting but the associated PR seems to add only unprivileged option: https://github.com/bpg/terraform-provider-proxmox/pull/225

Would it be possible to add `nesting=true` property to the config? It is enabled in the Proxmox UI when unprivileged is checked: 
![image](https://user-images.githubusercontent.com/3398165/223500868-20401ae6-305a-43d7-8dce-304f13068ce7.png)

Or am I missing something on how to define the nesting feature?

**Comment by Tumetsu** [comment]
I'll see if I manage to make a PR from this. I haven't programmed Go before and just started with TF but I suppose the #225 is a good example how to add new properties to the provider.

**Comment by bpg** [comment]
Hey @Tumetsu 👋
Nice catch, thanks for the detailed report! I may be able to put this fix fairly quickly.

**Comment by Tumetsu** [comment]
@bpg That would be great! While I managed to hack a `nesting = true` kind of property I suppose the more correct config would be something along the lines of 
```
features {
  nesting = true
}
```
in case there is need for other feature configs in the future. Couldn't get that to work yet :sweat_smile:

**Comment by Tumetsu** [comment]
@bpg I went ahead and submitted a PR. Seemed to work on my Proxmox homelab setup. Not sure about required tests for options inside the features block but hopefully this helps.

**Comment by bpg** [comment]
Thanks for this! I really appreciate PRs! :)
It looks good so far, let me just run a few more tests in my env before merge
