### ISSUE TITLE
Permission denied error when creating proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by 1-cameron** [bpg/terraform-provider-proxmox#281]
**Describe the bug**
When creating a `proxmox_virtual_environment_file` resource of type `snippets` it fails with a _permission denied_ error. 

**To Reproduce**
1. Declare a `proxmox_virtual_environment_file` resource of type `snippets`
2. `terraform apply`

**Expected behavior**
The resource is created successfully.

**Additional context**
The PVE version is 7.3-4 and I've run basically the same Terraform config against a different PVE cluster of the same version without any issues which makes me think I'm missing something. However, I can't see why it would be failing due to lack of perms.

I have a pam user with the required permissions on the node and within PVE - The `PVEDatastoreAdmin` role and write access to the snippets directory in the target storage. 

The debug logs show the final API call before the error but I can see from the proxy logs on the node that the call was successful.

```bash
[DEBUG] provider.terraform-provider-proxmox_v0.15.0: sending request: @caller=github.com/bpg/terraform-provider-proxmox/proxmox/virtual_environment_client.go:183 tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=fa1f843b-af2b-a04e-84f8-6e0df26c0238 tf_resource_type=proxmox_virtual_environment_file tf_rpc=ApplyResourceChange @module=proxmox path=/api2/json/nodes/pve-node/network timestamp=2023-03-31T13:19:26.083+0100

[ERROR] provider.terraform-provider-proxmox_v0.15.0: Response contains error diagnostic: diagnostic_summary="permission denied" tf_proto_version=5.3 tf_req_id=fa1f843b-af2b-a04e-84f8-6e0df26c0238 tf_resource_type=proxmox_virtual_environment_file tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/bpg/proxmox @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= timestamp=2023-03-31T13:19:26.505+0100

[ERROR] vertex "module.nessus.proxmox_virtual_environment_file.user_cloud_config" error: permission denied
```

```bash
terraform-imports@pam [31/03/2023:13:19:26 +0100] "GET /api2/json/nodes/pve-node/network HTTP/1.1" 200 1016
```

Any help would be appreciated! 

Thanks in advance.

**Comment by bpg** [comment]
Hi there @1-cameron! When provisioning a virtual machine with custom disks, the provider needs to establish an SSH session with the node to execute some PVE CLI commands. Prior to that, the provider retrieves the IP address of the node by making another API call to `GET` `/api2/json/nodes/pve-node/network`.

Therefore, the user that you have configured for the provider should have read access to the `/nodes/pve-node` API path. The `PVEAuditor` role should suffice for this purpose, but I haven't tested it yet. Please let me know if it works for you, and I'll update the docs.

**Comment by 1-cameron** [comment]
Thanks for getting back to me so quickly!

I gave the user the permissions in PVEAuditor and I'm still getting a _permission denied_ error at the same point. If I log in as the pam user in the PVE GUI and then access the api2/json/nodes/pve-node/network address I can see it.

**Comment by 1-cameron** [comment]
And the pveproxy logs don't contain a single failed API call from the user

**Comment by bpg** [comment]
I have found the bug in the code. The provider is attempting to read `/etc/pve/storage.cfg`, which may not be accessible to the user. In fact, we don't really need to read that file at all, as we can retrieve all the necessary information from the API. The fix is coming,
thanks for bringing this up! :)

**Comment by 1-cameron** [comment]
Nice spot! Thanks for patching that so quickly
