### ISSUE TITLE
Enable terraform import

### ISSUE THREAD

**Issue by yuqo2450** [bpg/terraform-provider-proxmox#29]
Hey there!
First of all nice work and thx for keeping this project alive!

I am using packer to create templates for my vms and it would be amazing, if it was possible, to import these templates into my terraform state. Therefore I wanted to ask if it was possible to add the terraform import functionality to this provider.
Another option could be to create a data resource for vms.

Thanks a lot!

**Comment by pescobar** [comment]
are there any plans to add the import functionality?

**Comment by bpg** [comment]
Hi @pescobar! 👋🏼 
No, I don't have plans of adding this at the moment. But I'll reopen this ticket to collect more feedback from the community, and perhaps someone could contribute implementation of this feature.

In a meantime, would some minimalistic `datasource`(s) would be enough to unblock you, e.g. if you need to read just a few attributes of a PVE resource? There was a similar case before: https://github.com/bpg/terraform-provider-proxmox/issues/261

**Comment by pescobar** [comment]
Thanks for the kind reply @bpg . No worries, no need to invest any time on adding extra datasources.

**Comment by ForsakenHarmony** [comment]
Was pretty simple, added a bunch of resources as a part of #384
