### ISSUE TITLE
How to enable firewall for container network device?

### ISSUE THREAD

**Issue by Tumetsu** [bpg/terraform-provider-proxmox#294]
**Is your feature request related to a problem? Please describe.**
I want to automatically set security group and assign said security group to my lxc container. I can do that by using security group resource and firewall options resource. However, to me it looks like Proxmox requires you to check one more checkbox to actually enable the firewall. That checkbox is located in Network page of a container:
![image](https://user-images.githubusercontent.com/3398165/230737969-f494fe86-f892-4974-abb6-47dec7d3e52e.png)

Is there support for toggling that to true? For me it seems to default false. I checked container resource's docs but its network part did not have any mention of firewall. Am I missing something here?

**Describe the solution you'd like**
Add boolean flag for network device firewall.

**Comment by bpg** [comment]
Hey @Tumetsu 👋🏼 
Indeed, there should be a `firewall` argument for network adapters, both for LXC and VM. Will add it in the next release.

Thanks for reporting!

**Comment by bpg** [comment]
LXC example:

```terraform
resource "proxmox_virtual_environment_container" "example" {
  ...

  network_interface {
    name     = "veth0"
    mtu      = 1450
    firewall = true
  }
}
```

**Comment by Tumetsu** [comment]
Thanks for quick fix! Got my firewall settings IaC'd now :+1:
