### ISSUE TITLE
Add the ability to authenticate by API token

### ISSUE THREAD

**Issue by skensell201** [bpg/terraform-provider-proxmox#300]
Hello, please consider adding user token authentication.

**Comment by bpg** [comment]
Hey @skensell201 👋🏼 
It duplicates https://github.com/bpg/terraform-provider-proxmox/issues/190

TL;DR: VM provisioning require some disk operations that are not supported over PVE API at the moment, so we need to have an SSH access to the PVE nodes.

**Comment by camaeel** [comment]
@bpg What about having token + ssh key from ssh-agent?

**Comment by bpg** [comment]
@camaeel Working on it :) There are some issues / limitations that I'm trying to figure out.

**Comment by bpg** [comment]
Reopening, as we can now support this use case along with the separate authentication settings for SSH, added in https://github.com/bpg/terraform-provider-proxmox/issues/307

**Comment by bpg** [comment]
@camaeel I have a version that supports API Token auth in #350. Would you be able to give it a shot and check if it works for your use cases? I really appreciate as much testing as possible for this type of changes :)

**Comment by camaeel** [comment]
@bgp Works as expected. 

I was able to create a VM using the token. 

Another nice security improvement could be if ssh connection could use sudo, so you can log with ssh key into ordinary user and then elevate priviledges to root (it should require NOPASSWD access of course) so the proxmox server's sshd can have direct root login disabled.

**Comment by bpg** [comment]
Created https://github.com/bpg/terraform-provider-proxmox/issues/352 to follow up
