### ISSUE TITLE
False SSH connection

### ISSUE THREAD

**Issue by yuqo2450** [bpg/terraform-provider-proxmox#302]
**Describe the bug**
Hello there,
I am trying to add a **snippet** to my proxmox host. It worked flawless in the past but I recently changed my network and now I cant add snippets anymore. Adding **iso** files does not cause any issues.

I realized that the error is telling me that the provider tried to connect to the old ip of the host. Now I wonder, where does the provider get its **SSH connection** information from?
It does not seem it uses the one given in the _provider endpoint_, I even put the IP not the hostname.

Would be amazing if I could figure this out without reinstalling the host.

**Comment by yuqo2450** [comment]
Ok I solved the problem. But I will keep this issue open cause I don't think it works as intended.

The ssh configuration seems to be the IP address of the first configured interface.

Probably this should be changed to the endpoint host?

**Comment by bpg** [comment]
Hi @yuqo2450! 
Thanks for the report, and I'm glad to hear that you were able to solve it for your environment!

You are correct about the IP address lookup. The provider enumerates interfaces on the target node and picks up the IP address of the first one, which unfortunately means we can't rely on the endpoint IP address. In a clustered PVE setup, the target node where the VM is deployed may differ from the one that is used as an API endpoint.

I understand that this may not be the most transparent approach, and it can be confusing for many people. I am going to take some time to update the documentation to provide more clarity on this topic.

**Comment by yuqo2450** [comment]
Hi @bpg!
Thanks for your quick answer. Honestly I haven't thought about clustered environments and you are totally right.
Just wondering if it would be a good idea to add an ***ssh_connection*** argument to the snippet resource, so one can specify the address if needed? Could be also just me and my special setup having these kind of issues ;).

**Comment by bpg** [comment]
I don't think we want to do it _per-resource_, as it can become very messy very soon if one operates multiple resources.
There is another discussion going on about SSH connection improvements in https://github.com/bpg/terraform-provider-proxmox/pull/306. We can define a map on the provider level with overrides `node` -> `IP`, or something like that. Feel free to chime in there :)

**Comment by bpg** [comment]
Closing this ticket in favour of #307
