### ISSUE TITLE
SSH Agent support

### ISSUE THREAD

**Issue by zoop-btc** [bpg/terraform-provider-proxmox#307]
Hello,

Due to security considerations I don't allow password authentication for ssh on my proxmox. Thus I can only use this provider if it supports ssh-agent.

Just to see if it works I have implemented it myself in this [draft pr](https://github.com/bpg/terraform-provider-proxmox/pull/306).
Since I am no go developer I didn't know how to do the windows part for it. However I would consider looking it up and polishing the PR if interest is there.
As was hinted in other discussions ssh is due for a rewrite so I don't want to duplicate any work.

Thank you kindly,
Zoop

**Comment by bpg** [comment]
Hey @zoop-btc! 👋🏼
Thanks a lot for the PR! I'll be able to take a look and give you some feedback later this week.

**Comment by bpg** [comment]
> As was hinted in other discussions ssh is due for a rewrite so I don't want to duplicate any work.

Nothing is currently in progress (at least on my side)
So I'm going to hijack this ticket to collect all SSH improvements in one place 😄

**Comment by zoop-btc** [comment]
Ok from what I can see #302 needs an ssh IP override and @249 would be solved by ssh-agent as well. I can do that in my PR as well.

**Comment by bpg** [comment]
Let's do the SSH IP address mapping / improvements in a separate PR. I think [this approach](https://github.com/bpg/terraform-provider-proxmox/pull/306#issuecomment-1530841041) will solve the issue for majority of use cases without introducing extra configs.

**Comment by bpg** [comment]
> Let's do the SSH IP address mapping / improvements in a separate PR. I think [this approach](https://github.com/bpg/terraform-provider-proxmox/pull/306#issuecomment-1530841041) will solve the issue for majority of use cases without introducing extra configs.

Well, that didn't work well. In case of unrouted IP address the approach of trying each interface in the list until getting the working one takes quite a while.
So discarded this idea and implemented a simple `node` -> `ip` lookup map in #355.
