### ISSUE TITLE
Add EFI disk support

### ISSUE THREAD

**Issue by michaelfranzl** [bpg/terraform-provider-proxmox#316]
During `terraform apply`, version 0.18.1 of this provider fails with an error even though the VM creation is successful (there is only a warning):

`Error: task "UPID:myhost:00000000:00000000:00000000:qmstart:1000:me@domain:" on node "myhost" failed to complete with error: WARNINGS: 1`

I think that this is the responsible line:

https://github.com/bpg/terraform-provider-proxmox/blob/7c9505d11f7cc99f6052e814f549004fe97e8b49/proxmox/virtual_environment_nodes.go#L297

The web interface (Proxmox 7.4-3) gives the details of the warning:

```
generating cloud-init ISO
WARN: no efidisk configured! Using temporary efivars disk.
TASK WARNINGS: 1
```

The obvious workaround is to add an EFI disk to the VM template (I have to use the Proxmox UI for this, because configuration of an EFI disk doesn't seem to be supported, see https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/resources/virtual_environment_vm.md).

However, if I do this, then I'm hit by issue #314. And unfortunately, it doesn't seem to be possible to change the EFI disk size in Proxmox - it will always use k or M units.

Because `terraform apply` was not successful, it will destroy the resource on the next try, so I cannot move forward.

Do you know a workaround or fix?

Thank you for this project and your efforts, much appreciated.

**Comment by bpg** [comment]
Hi @michaelfranzl! 👋🏼
Thanks for the report. I think there is no workaround available at the moment, unfortunately.

I'll convert this issue to an "enhancement", to add EFI support.

**Comment by bpg** [comment]
Also related: https://github.com/bpg/terraform-provider-proxmox/issues/202

**Comment by michaelfranzl** [comment]
Hi @bpg  and thanks.

I would like to point out that this issue could also be solved (maybe quicker) by ignoring Proxmox warnings. In most contexts, warning are not errors and it is OK to carry on.

I have tested and can confirm that the following change in proxmox/virtual_environment_nodes.go makes Terraform complete successfully, while the desired action is performed nevertheless.

```
-   if status.ExitCode != "OK" {
+   matched, _ := regexp.MatchString("(WARNING|OK).*", status.ExitCode)
+   if !matched {
```

**Comment by ForsakenHarmony** [comment]
Created a PR for it: #384
