### ISSUE TITLE
Try to update arguments in every run

### ISSUE THREAD

**Issue by marcovergueira** [bpg/terraform-provider-proxmox#339]
**Describe the bug**
The resource proxmox_virtual_environment_vm tries to update the resource arguments, when the qemu-guest-agent it's used, seems the agent updates the network interfaces on proxmox and then when I run terraform apply it will try to update the follow arguments, ipv4_addresses, ipv6_addresses, network_interface_names.

**To Reproduce**
1. Create a resource 'proxmox_virtual_environment_vm'
3. Run 'terraform apply'
4. Run 'terraform apply'
5. See the terraform trying to change the resource arguments 'ipv4_addresses, ipv6_addresses, network_interface_names'

Please also provide a minimal Terraform configuration that reproduces the issue.

user-data
```
#cloud-config
# user and hostname stuff between
package_upgrade: true
packages:
  - qemu-guest-agent
runcmd:
  - [ systemctl, start, qemu-guest-agent.service ]
  - [ systemctl, restart, networking.service ]
```
terraform resource
```
resource "proxmox_virtual_environment_vm" "debian-test" {
  name        = "debian-test"
  node_name = "pve"
  vm_id     = 1000

  cpu {
    cores = 4
  }

  memory {
    dedicated = 8192
  }

  agent {
    enabled = true
  }

  vga {
    enabled = true
    memory  = 16
    type    = "serial0"
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_file.virtual_machine_isos["debian-11"].id
    interface    = "scsi0"
  }

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_data_file_id = proxmox_virtual_environment_file.snippet_user_data.id
  }

  network_device {
    bridge = "vmbr0"
  }

  operating_system {
    type = "l26"
  }

  serial_device {}
}
```

**Expected behavior**
Do not detect any change on arguments.

**Screenshots**
![image](https://github.com/bpg/terraform-provider-proxmox/assets/929114/955ed7e3-34b5-4870-a59d-141928d1a062)
![image](https://github.com/bpg/terraform-provider-proxmox/assets/929114/7e459590-507b-44d5-968e-5f4005928b04)

**Additional context**
- Provider version (ideally it should be the latest version): 0.19.1
- Terraform version: v1.4.6
- OS (where you run Terraform from)): Arch Linux, 6.3.1-zen2-1-zen
- Debug logs (`TF_LOG=DEBUG terraform apply`): let me know if this is really needed

**Comment by JonTheNiceGuy** [comment]
Looks like you need to add the following to your resource:

```
  lifecycle {
    ignore_changes = [
      network_interface_names,
      ipv4_addresses,
      ipv6_addresses
    ]
  }
```

Remember that terraform is designed to be declarative - I want this resource to exist here, configured like this - what you're seeing is (kinda) designed behaviour.

**Comment by marcovergueira** [comment]
> Looks like you need to add the following to your resource:
> 
> ```
>   lifecycle {
>     ignore_changes = [
>       network_interface_names,
>       ipv4_addresses,
>       ipv6_addresses
>     ]
>   }
> ```
> 
> Remember that terraform is designed to be declarative - I want this resource to exist here, configured like this - what you're seeing is (kinda) designed behaviour.

Right, I tried that, I'm used to ignore_changes, however usually I use it with Arguments not with Attributes. 

These three variables are Attributes, like an output to bind with other resources, we can't change them, if we want a certain network configuration we should use the arguments/block network_device.

If I use the ignore_changes I get this warning, which seems to not be the expected behavior.
![image](https://github.com/bpg/terraform-provider-proxmox/assets/929114/b4974049-8cb5-4f91-896d-81bdfcbd3045)

**Comment by f0rkz** [comment]
Seeing the same thing on my side. These attributes must have a bad lookup or something.

**Comment by otopetrik** [comment]
The above pull-request should fix it.
Workaround for current version is to ensure that every `network_device` block has `mac_address` field set to an actual MAC address.
