### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by joshrmcdaniel** [bpg/terraform-provider-proxmox#351]
When attempting to upload an ISO file larger than `419430400` bytes from a raw data stream (`raw_source` stanza), the GRPC module throws an error stating the payload size is larger than the maximum size. I am using the pulumi port of this provider, [see here for bug issue raised there](https://github.com/muhlba91/pulumi-proxmoxve/issues/50).

My specific scenario:
- Using Pulumi
- Downloading multiple gzipped ISOs programatically, storing each in a buffer. I then extract the ISO, and pass it as the `data` argument in the `source_raw` stanza.

**To Reproduce**
1. Create a resource `proxmox_virtual_environment_file` with the `raw_source` stanza. Have the `data` length be larger than `419430400` bytes
2. Apply the configuration

This is a fresh IaC stack, there are no other resources.

Example problematic resource:
```hcl
resource "proxmox_virtual_environment_file" "iso" {
  content_type = "iso"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data      = "<really long binary string>" # (larger than `419430400` bytes)
    file_name = "os.iso"
  }
}
```

**Expected behavior**
The file resource to upload successfully

**Additional context**
- Provider version (ideally it should be the latest version): 0.20.1
- Terraform version: N/A, using pulumi
- OS (where you run Terraform from)): Windows 11
- Debug logs (`TF_LOG=DEBUG terraform apply`): N/A, using pulumi

**Comment by bpg** [comment]
Hi @joshrmcdaniel

This seems to be a limitation of the protocol between the provider (runs as a grpc server) and the terraform (a grpc client). `source_raw` in general is not well suited to handle large data blocks, its whole content needs to buffered into memory on both client and server sides during the transmission.

Could you buffer the ISO content to a disk and then use [`source_file`](https://registry.terraform.io/providers/bpg/proxmox#source_file) instead?

**Comment by joshrmcdaniel** [comment]
🤦 That resolved my issue!

**Comment by bpg** [comment]
Awesome! 👍🏼
