### ISSUE TITLE
Template name instead of vm_id when  full cloning vm template

### ISSUE THREAD

**Issue by enmanuelmoreira** [bpg/terraform-provider-proxmox#368]
**Is your feature request related to a problem? Please describe.**
I have 3 proxmox nodes, On each nodes I have templates of ubuntu,  which clone them to spread to all nodes but the vm_ids must be different. It could be better if instead of vm_id or addition the template name (which is the same on all nodes) 

**Describe the solution you'd like**
Replace vm_id for template_name on clone {} when cloning a vm template

**Comment by bpg** [comment]
Hi @enmanuelmoreira! 👋🏼 
Thanks for reporting! Yes, this feature is missing, but in a meantime you can use [virtual_environment_vms](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/data-sources/virtual_environment_vms) datasource to get ID of the template by tag, and then use it in the resource when cloning.
