### ISSUE TITLE
Firewall settings missed remotely and in corrupted state locally after changing the container template

### ISSUE THREAD

**Issue by kam193** [bpg/terraform-provider-proxmox#388]
**Describe the bug**
Using Terraform, I created a Debian 12 container and corresponding firewall settings, but then recognized that I need Debian 11. I changed the template and Terraform recreated the container. However, all firewall settings were lost (enable for the container, enable for each interface, chosen security groups). In addition, the provider isn't able to retrieve the current state anymore - it fails on asking for FW rules. 

**To Reproduce**
1. Create a resource `proxmox_virtual_environment_container`, and add corresponding FW settings (see example below).
2. Run `terraform apply`
3. Verify the settings in Proxmox UI, possibly apply once more to enable firewall on the interface (is it intentional, or another bug?). The  security groups and firewall settings are correctly applied.
4. Modify the container, changing the template.
5. Run `terraform apply` - the container will be recreated.
6. See in the Proxmox UI the firewall is disabled, and the security group is gone.
7. Run `terraform plan`
8. See error:
```
│ Error: error reading rule 0 : error retrieving firewall rule 0: received an HTTP 500 response - Reason: no rule at position 0
│ 
│   with proxmox_virtual_environment_firewall_rules.minimal_fw_rules,
│   on iciga copy.tf line 41, in resource "proxmox_virtual_environment_firewall_rules" "minimal_fw_rules":
│   41: resource "proxmox_virtual_environment_firewall_rules" "minimal_fw_rules" {
```

Example Terraform (may be incomplete):

```
resource "proxmox_virtual_environment_container" "minimal" {
  description  = "Container for testing"
  node_name    = var.pve_node
  vm_id        = 202
  unprivileged = true

  disk {
    datastore_id = var.pve_disk_store
  }

  initialization {
    hostname = "test.home"

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  network_interface {
    name        = "eth0"
    bridge      = "vmbr0"
    firewall    = true
  }

  operating_system {
    template_file_id = proxmox_virtual_environment_file.debian_11_ct.id # Changee this to trigger the problem
    type             = "debian"
  }
}

resource "proxmox_virtual_environment_firewall_options" "minimal" {
  depends_on = [proxmox_virtual_environment_container.minimal]
  node_name  = var.pve_node
  vm_id      = proxmox_virtual_environment_container.minimal.vm_id
  enabled    = true
  dhcp       = true
}

resource "proxmox_virtual_environment_firewall_rules" "minimal_fw_rules" {
  depends_on = [proxmox_virtual_environment_container.minimal]
  vm_id      = proxmox_virtual_environment_container.minimal.vm_id
  node_name  = var.pve_node

  rule {
    security_group = proxmox_virtual_environment_cluster_firewall_security_group.test_group.name
  }
}

resource "proxmox_virtual_environment_cluster_firewall_security_group" "test_group" {
  name = "test_ssh"
  rule {
    type   = "in"
    action = "ACCEPT"
    macro  = "SSH"
    source = "0.0.0.0/0"
  }
}
```

**Expected behavior**
The container should be recreated with all related firewall settings.

**Additional context**
- Provider version (ideally it should be the latest version):  0.21.1
- Terraform version: 1.5.1
- OS (where you run Terraform from)): Linux Mint 21.1
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by bpg** [comment]
Thanks for the report @kam193!

Firewall support is relatively new feature, and some edge cases may not be tested well by the community (personally I'm not using PVE firewall in my LAB). So it is great that you're able to help with testing!

I think you'd need to update your template with
```terraform
resource "proxmox_virtual_environment_firewall_options" "minimal" {
  depends_on   = [proxmox_virtual_environment_container.minimal]
  node_name    = var.pve_node
  container_id = proxmox_virtual_environment_container.minimal.vm_id
  enabled      = true
  dhcp         = true
}
```
It should have `container_id` instead of `vm_id` in the options arguments. [Documentation](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_firewall_options#argument-reference) may not be super clear on that, but essentially provider is using `container_id` vs `vm_id` argument to decide which Proxmox API to use (lxc or qemu) when update settings.

This change may fix both problems you're seeing. Could you please try and report back?

Thanks!

**Comment by kam193** [comment]
Hey, thanks for the answer! I've just tried it, but it didn't help. But I also see that the plan didn't contain any changes to the firewall settings. Maybe the provider isn't aware that they strictly depend on container/vm? 

```
  # proxmox_virtual_environment_container.minimal must be replaced
-/+ resource "proxmox_virtual_environment_container" "minimal" {
      ~ id           = "202" -> (known after apply)
      - tags         = [] -> null
        # (6 unchanged attributes hidden)

      ~ network_interface {
          ~ firewall    = false -> true
          - mac_address = "3E:9E:0F:D1:D6:EE" -> null
            name        = "eth0"
            # (5 unchanged attributes hidden)
        }

      ~ operating_system {
          ~ template_file_id = "local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst" -> "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst" # forces replacement
[...]
```

Provider is aware that it needs to replace the container, but I assume that it also destroys any related firewall settings - but the plan doesn't contain replacing them. I think the provider should just recognize, that any deletion of VM/Container removes all dependents as well.
