### ISSUE TITLE
LXC networking 

### ISSUE THREAD

**Issue by Msabljic** [bpg/terraform-provider-proxmox#405]
Been working on some containers I noticed that nic’s are a dynamic block but gateway and ip_config is its own block. I think it would work better if this was one block which can be dynamic. (Similar to how the interface presents it) As always I can test the functionality !

**Comment by bpg** [comment]
I think this request is quite similar to #377 🤔

**Comment by Msabljic** [comment]
Ah didn’t see this one, you are correct I will close this one!

**Comment by Msabljic** [comment]
Duplicate
