### ISSUE TITLE
Let’s back things up!

### ISSUE THREAD

**Issue by Msabljic** [bpg/terraform-provider-proxmox#406]
In a world where I break things all the time it would be nice to provision and configure backups both on the node and resource level. I’m sure this is a big ask! I’m always willing to test!

**Comment by 149segolte** [comment]
I think backup configuration is a great feature to have. Can this issue be reopened? I don't see a reason for it being closed as "not planned".

**Comment by bpg** [comment]
Hey @149segolte! 👋🏼  

This ticket has almost no actionable information, so I don’t see much point in reopening it.  

Could you open a new ticket and describe how you’d like this feature to work? Including an example config that satisfies your use case would be really helpful.

**Comment by 149segolte** [comment]
Done. Just created #1815 with some examples attached.

**Comment by bpg** [comment]
Thanks @149segolte 🙇‍♂ Great job writing this up!

**Comment by bpg** [comment]
@all-contributors please add @149segolte for ideas
