### ISSUE TITLE
Multiple lxc disks

### ISSUE THREAD

**Issue by Msabljic** [bpg/terraform-provider-proxmox#407]
I’m sure by now you’re seeing a theme of my provisioning and test lol. It would be a nice feature to have to be able to create mounts via code. I’m not sure if this can be one resource for both vm’s and containers but the ability to create multiple disks/ mounts would be cool!

**Comment by bpg** [comment]
Hi @Msabljic! 👋🏼
Speaking about LXC disk/mount, is this is similar to what is described in #256?

> ... if this can be one resource for both vm’s and containers

I'm not quite sure I understand the use case you have in mind. In my inderstanding VMs and containers can't share disks.

**Comment by Msabljic** [comment]
> Hi @Msabljic! 👋🏼 Speaking about LXC disk/mount, is this is similar to what is described in #256?
> 
> > ... if this can be one resource for both vm’s and containers
> 
> I'm not quite sure I understand the use case you have in mind. In my inderstanding VMs and containers can't share disks.

Sorry maybe a bit unclear on my side. Not that they share a disk/ mount but that the resource can work for both vm or ct (looking at it I’m not sure how worth it that would be)

**Comment by bpg** [comment]
I'm closing this as the multiple LXC mount points support has been added in #394.
