### ISSUE TITLE
Wrong type for `NetworkInterfaceListResponseData.data.bridge_fd`

### ISSUE THREAD

**Issue by zroug** [bpg/terraform-provider-proxmox#410]
**Describe the bug**

The following error occurs when attempting to create a resource:

> Error: failed to find node endpoint: failed to list network devices of node "pve": failed to get network interfaces for node "pve": failed to decode HTTP GET response (path: nodes/pve/network) - Reason: json: cannot unmarshal number into Go struct field NetworkInterfaceListResponseData.data.bridge_fd of type string

**To Reproduce**

Have a Proxmox node with a 'Linux Bridge' network interface and try to create a file resource.

<details>
<summary>Minimal Terraform configuration</summary>

```terraform
resource "proxmox_virtual_environment_file" "test" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data      = "..."
    file_name = "test.txt"
  }
}
```

</details> 

**Additional context**

Provider version: 0.23.0
Proxmox VE version: 7.3

<details>
<summary>Response from `GET /api2/json/nodes/pve/network`:</summary>

```json
{
  "data": [
    {
      "autostart": 1,
      "options": ["hwaddress ether da:73:2c:98:ae:c0"],
      "priority": 4,
      "iface": "vmbr0",
      "families": ["inet"],
      "type": "bridge",
      "active": 1,
      "bridge_ports": "bond0",
      "bridge_stp": "off",
      "method6": "manual",
      "method": "dhcp",
      "bridge_fd": 0
    },
    ...
  ]
}
```

</details>

**Comment by bpg** [comment]
Hi @zroug! 👋 
Thanks for the report. What is the Proxmox VE version you're using?

**Comment by bpg** [comment]
Just for tracking, the /nodes/<node>/network API is undocumented, so we have some incompatibilities between versions:  

```
root@pve:~# pvesh get /version --output-format json-pretty
{
   "release" : "8.0",
   "repoid" : "bbf3993334bfa916",
   "version" : "8.0.3"
}
```
```
root@pve:~# pvesh get /nodes/pve/network --output-format json-pretty
[
...
   {
      "active" : 1,
      "address" : "192.168.x.x",
      "autostart" : 1,
      "bridge_fd" : "0",
      "bridge_ports" : "ens18",
      "bridge_stp" : "off",
      "bridge_vids" : "2-4094",
      "bridge_vlan_aware" : 1,
      "cidr" : "192.168.x.x/24",
      "families" : [
         "inet"
      ],
      "gateway" : "192.168.x.x",
      "iface" : "vmbr0",
      "method" : "static",
      "method6" : "manual",
      "netmask" : "24",
      "priority" : 5,
      "type" : "bridge"
   }
]
```
`bridge_fd` is string.

I'm going to remove this field from the golang message struct altogether, as it is not used.

**Comment by bpg** [comment]
can use `types.CustomInt` to work around this API "feature".
