### ISSUE TITLE
Loops break containers

### ISSUE THREAD

**Issue by Msabljic** [bpg/terraform-provider-proxmox#413]
So from the best I can see it looks like looping the nics breaks the container creation. 

Stack trace from the terraform-provider-proxmox_v0.23.0 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 83 [running]:
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.containerCreateCustom({0x101d548, 0xc000456840}, 0x15da180?, {0xde5000?, 0xc000465140?})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/container.go:1110 +0x2c74
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.containerCreate({0x101d548, 0xc000456840}, 0x0?, {0xde5000, 0xc000465140})
	github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/container.go:656 +0x9f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002749a0, {0x101d580, 0xc000211ec0}, 0xd?, {0xde5000, 0xc000465140})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002749a0, {0x101d580, 0xc000211ec0}, 0xc000219110, 0xc000410000, {0xde5000, 0xc000465140})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000116f8, {0x101d580?, 0xc000211ce0?}, 0xc000163540)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1023870?, 0xc0000116f8?}}, {0x101d580, 0xc000211ce0}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc00026f320, 0xc00026f380, {0xc0002acfc0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002d81e0, {0x101d580?, 0xc000210fc0?}, 0xc0000afc00)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xe79540?, 0xc0002d81e0}, {0x101d580, 0xc000210fc0}, 0xc0000afb90, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001[203](https://gitlab.earth/proxmox/feature/container-registry/testing-ground/-/jobs/761#L203)c0, {0x1022818, 0xc0002c9ba0}, 0xc000[214](https://gitlab.earth/proxmox/feature/container-registry/testing-ground/-/jobs/761#L214)120, 0xc0003907b0, 0x15cbd40, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001203c0, {0x1022818, 0xc0002c9ba0}, 0xc000214120, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.0/server.go:957 +0x18c
Error: The terraform-provider-proxmox_v0.23.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by bpg** [comment]
Hey @Msabljic, could you please attach an example of the container resource that causes the issue?

**Comment by Msabljic** [comment]
[main.txt](https://github.com/bpg/terraform-provider-proxmox/files/11963416/main.txt)
[terraform.tfvars.txt](https://github.com/bpg/terraform-provider-proxmox/files/11963417/terraform.tfvars.txt)

**Comment by Msabljic** [comment]
Additionally testing shows that its if the variables are passed as objects it breaks the looping creating. I think this might not be a large impacting problem and if its not an easy fix maybe just need a note placed somewhere?

**Comment by FKouhai** [comment]
same issue while creating VMs

**Comment by bpg** [comment]
This seems to be related to handling of empty blocks. This particular error is related to an empty `initialization.dns` in the plan.

Related:
- https://github.com/bpg/terraform-provider-proxmox/pull/1043
- https://github.com/bpg/terraform-provider-proxmox/pull/977

Also in VM:
- https://github.com/bpg/terraform-provider-proxmox/pull/1033
- https://github.com/bpg/terraform-provider-proxmox/pull/1196
