### ISSUE TITLE
unable to use cdrom with q35 machine

### ISSUE THREAD

**Issue by si458** [bpg/terraform-provider-proxmox#420]
**Describe the bug**
when attaching a cdrom with a q35 machine, you cannot start the VM
```
kvm: -device ide-cd,bus=ide.1,unit=1,drive=drive-ide3,id=ide3,bootindex=100: Can't create IDE unit 1, bus supports only 1 units
TASK ERROR: start failed: QEMU exited with code 1
```

after checking the proxmox forums, q35 machines cannot use ide3, only ide 0 or ide2 
https://forum.proxmox.com/threads/error-when-using-4-ide-devices.97634/post-422958

**To Reproduce**
1. create resource with cdrom set
2. start vm

**Expected behavior**
VM to start

**Screenshots**

**Additional context**
- Provider version (ideally it should be the latest version): 0.24.0
- Terraform version: 1.5.2
- OS (where you run Terraform from)): Windows 11
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by si458** [comment]
you could also make this a feature request to allow us to specify which IDE port to connect the ISO to? 
OR
change the default to IDE2 as its the default when you create a blank VM in the proxmox GUI anyways

**Comment by bpg** [comment]
Hi @si458! 👋🏼 Thanks for the report!
That's interesting use case, I'd need to investigate a bit more. IDE2 is currently reserved for cloud-init configuration.

**Comment by si458** [comment]
@bpg I have always had to set the cloud-init drive to iscsi2 to be able to get Ubuntu cloud images to work correctly?

**Comment by bpg** [comment]
@si458 Could you post your template that causes cloud-unit issues?

**Comment by si458** [comment]
```
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
  }
}
provider "proxmox" {
  endpoint = "https://1.2.3.4:8006/"
  username = "root@pam"
  password = "mypasswordgoeshere"
  insecure = true
}
resource "proxmox_virtual_environment_vm" "k8s-01" {
  agent {
    enabled = true
  }
  bios = "ovmf"
  cdrom {
    enabled = true
    file_id = "ISOImages:iso/talos-amd64-v1.4.6.iso"
  }
  cpu {
    cores = 8
    sockets = 1
    type = "x86-64-v2-AES"
  }
  disk {
    datastore_id = "local-zfs"
    discard = "on"
    file_format = "raw"
    interface = "scsi0"
    iothread = true
    size = 32
  }
  efi_disk {
    datastore_id = "local-zfs"
    file_format = "raw"
    type = "4m"
  }
  machine = "q35"
  memory {
    dedicated = 8192
  }
  name = "k8s-01"
  network_device {
    bridge = "vmbr168"
    vlan_id = 251
  }
  node_name = "pve1"
  on_boot = false
  operating_system {
    type = "l26"
  }
  serial_device {
    device = "socket"
  }
  scsi_hardware = "virtio-scsi-single"
  started = false
}
```

**Comment by si458** [comment]
did you have any luck at all @bpg ?

**Comment by bpg** [comment]
I'm travelling this week, so will be able to look at it on the weekend. Your right, ide2 seems to be the default for cdrom. But I'd like to dig into the code history to understand better why ide2 was selected as a default for cloud init and cdrom moved to ide3.

**Comment by bpg** [comment]
Should be able to override default `ide3` with supported device via `interface` argument:

```hcl
  cdrom {
    enabled = true
    file_id = "local:iso/talos-amd64-3.iso"
    interface = "ide2"
  }
```

**Comment by si458** [comment]
thanks @bpg! i was wondering if you was gunna add this in or just simple change the default from ide3 to ide2!
look forward to a new release!

**Comment by bpg** [comment]
couldn't really change the default, as it will cause issues with existing VMs that have cdrom.

**Comment by si458** [comment]
thats perfectly fine! thanks @bpg! just wondering if u could have alook at my other issue when u have a sec? #427
