### ISSUE TITLE
Not specifying the interface name for lxc container crashes plugin

### ISSUE THREAD

**Issue by awanaut** [bpg/terraform-provider-proxmox#422]
**Describe the bug**
When leaving out the `name` parameter for network_interface{}, the plugin crashes when running an apply. If I specify the name, the apply finishes with no issues. The error below is what is outputted from Terraform: 

> ╷
> │ Error: Request cancelled
> │ 
> │ The plugin6.(*GRPCProvider).ApplyResourceChange request was cancelled.
> ╵
> 
> Stack trace from the terraform-provider-proxmox_v0.24.0 plugin:
> 
> panic: interface conversion: interface {} is types.CustomBool, not bool
> 
> goroutine 103 [running]:
> github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.containerCreateClone({0x1c36188, 0xc0002bd800}, 0x2204080?, {0x19faea0?, 0xc000416fa0})
>         github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/container.go:921 +0x2234
> github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.containerCreate({0x1c36188, 0xc0002bd800}, 0x0?, {0x19faea0, 0xc000416fa0})
>         github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/container.go:669 +0x76
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0003289a0, {0x1c361c0, 0xc000320c60}, 0xd?, {0x19faea0, 0xc000416fa0})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0x12e
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003289a0, {0x1c361c0, 0xc000320c60}, 0xc0000fd860, 0xc00020ed00, {0x19faea0, 0xc000416fa0})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000133788, {0x1c361c0?, 0xc000255680?}, 0xc0002d8500)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
> github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1c3c768?, 0xc000133788?}}, {0x1c361c0, 0xc000255680}, 0x0?)
>         github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5to6server/tf5to6server.go:37 +0x5a
> github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000321380, 0xc0000e92b0, 0xc0003213b0, 0xc0003213e0, {0xc0001119c0, 0x2, 0x2}}, {0x1c361c0?, 0xc000254f00?}, 0xc0002d84b0)
>         github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x139
> github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001e5cc0, {0x1c361c0?, 0xc000122960?}, 0xc00044c070)
>         github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x574
> github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1a90bc0?, 0xc0001e5cc0}, {0x1c361c0, 0xc000122960}, 0xc00044c000, 0x0)
>         github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d81e0, {0x1c3b698, 0xc0004049c0}, 0xc0001b4000, 0xc0003d51d0, 0x21f6040, 0x0)
>         google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
> google.golang.org/grpc.(*Server).handleStream(0xc0001d81e0, {0x1c3b698, 0xc0004049c0}, 0xc0001b4000, 0x0)
>         google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
>         google.golang.org/grpc@v1.56.1/server.go:959 +0x98
> created by google.golang.org/grpc.(*Server).serveStreams.func1
>         google.golang.org/grpc@v1.56.1/server.go:957 +0x18c
> 
> Error: The terraform-provider-proxmox_v0.24.0 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

**To Reproduce**
1. Create "proxmox_virtual_environment_container" resource and leave out the "name" parameter for network_interface{}.
2. `terraform apply`
3. See error above
4. Set name to something. Ex. vmbr0
5. `terraform apply`
6. Completes successfully

Please also provide a minimal Terraform configuration that reproduces the issue.

```
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.24.0"
    }
  }
}

provider "proxmox" {
  insecure = true
  endpoint = "https://<proxmoxnodeip>:8006"
  username = "root@pam"
  password = "pw"
}
```

**Expected behavior**
The documentation says `name` is required, therefore an error catch needs to occur if it is left out informing the user the `name` parameter is required or a default value should be set

**Comment by bpg** [comment]
Hi @Shauncoss! 

I haven't been able to reproduce this issue

Here is my template:
```hcl
resource "proxmox_virtual_environment_container" "ubuntu_container" {
  disk {
    datastore_id = "local-lvm"
    size         = 10
  }

  initialization {
    dns {
      server = "1.1.1.1"
    }

    hostname = "ubuntu-lxc"

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_account {
      keys     = [trimspace(data.local_file.ssh_public_key.content)]
      password = "example"
    }
  }

  network_interface {
#    name = "veth0"
    mtu  = 1450
  }

  node_name = "pve"

  operating_system {
    template_file_id = proxmox_virtual_environment_file.ubuntu_container_template.id
    type             = "ubuntu"
  }
}

resource "proxmox_virtual_environment_file" "ubuntu_container_template" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name

  source_file {
    path = "http://download.proxmox.com/images/system/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz"
  }
}

data "local_file" "ssh_public_key" {
  filename = "./id_rsa.pub"
}
```

The `network_interface.name` has already been declared as a [required attribute](https://github.com/bpg/terraform-provider-proxmox/blob/v0.24.0/proxmoxtf/resource/container.go#L535), and `terraform apply` returns an error as expected:
```
╷
│ Error: Missing required argument
│
│   on main.tf line 26, in resource "proxmox_virtual_environment_container" "ubuntu_container":
│   26:   network_interface {
│
│ The argument "name" is required, but no definition was found.
```

Could it be something else in your container operations flow that triggered the error?
The [code line](https://github.com/bpg/terraform-provider-proxmox/blob/v0.24.0/proxmoxtf/resource/container.go#L921C1-L921C1) from the error is referencing a firewall option. Do you have it enabled? Would you mind sharing the actual container template your'e using?

**Comment by bpg** [comment]
I'm going to close this ticket. @awanaut feel free to reopen if you still can reproduce the error.
