### ISSUE TITLE
Configurable timeout for `proxmox_virtual_environment_file`

### ISSUE THREAD

**Issue by zroug** [bpg/terraform-provider-proxmox#426]
**Is your feature request related to a problem? Please describe.**
`proxmox_virtual_environment_file` can timeout for large files and/or slow internet connections.

**Describe the solution you'd like**
The timeouts used by `proxmox_virtual_environment_file` should be configurable.

**Describe alternatives you've considered**
One could increase the default timeout, but I don't think there is a one size fits all.

**Additional context**
Currently there are two timeouts in place. One is defined in [this](https://github.com/bpg/terraform-provider-proxmox/blob/6a3bc034706cef4190651118bfc2e8f62de8aecd/proxmox/api/client.go#L34) line and the other is given by Terraform in the `context.Context` object.

I suggest getting rid of the first one by setting it to zero and making the second one configurable. This can be done by simply adding something like

```go
Timeouts: &schema.ResourceTimeout{
    Create: schema.DefaultTimeout(5 * time.Minute),
}
```

to the [Schema](https://github.com/bpg/terraform-provider-proxmox/blob/6a3bc034706cef4190651118bfc2e8f62de8aecd/proxmoxtf/resource/file.go#L65). See also this [documentation](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts).

**Comment by bpg** [comment]
Hi @zroug 👋🏼

Thanks for the report! I think we may not need to override the default timeout in the schema. Terraform already generously uses 20 minutes as a default. The option to override it per-resource with:

```hcl
timeouts {
  create = "60m"
}
```

will work if the HTTP client timeout you've mentioned has been removed.
