### ISSUE TITLE
allow setting smbios for each VM (optional values)

### ISSUE THREAD

**Issue by si458** [bpg/terraform-provider-proxmox#451]
**Is your feature request related to a problem? Please describe.**
when i clone a VM i created using the talos nocloud option, i need to set the smbios to a URL with confirmation already set
https://www.talos.dev/v1.4/talos-guides/install/cloud-platforms/nocloud/#smbios-proxmox

**Describe the solution you'd like**
to allow myself to set the smbios to certain values
this is already possible via the API GET and POST, values are base64 encoded
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

**Describe alternatives you've considered**
create vm and set the smbios manually in the web panel of proxmox

**Additional context**

```
{
  smbios: {
    base64: 1|0,
    family: "family",
    manufacturer: "manufacturer",
    product: "product",
    serial: "serial",
    sku: "sku",
    uuid: "uuid",
    version: "version"
  }
}
```

**Comment by bpg** [comment]
Duplicates https://github.com/bpg/terraform-provider-proxmox/issues/353, but I'll keep them both for tracking.

**Comment by si458** [comment]
> Duplicates https://github.com/bpg/terraform-provider-proxmox/issues/353, but I'll keep them both for tracking.

Not sure how I missed that thanks!

**Comment by bpg** [comment]
@si458 Thanks for contributing bugs / enhancements! Really appreciated! 
Please don't be shy to review my PRs as well :)

Typos are sneaky, so a second pair of 👀 is really welcome, as well as any other suggestions regarding terraform API / namings / docs, etc, etc...

**Comment by si458** [comment]
Thanks @bgp 
And this might sound daft but I have no clue with Golang 🤣 I'm a nodejs guy
And pointers on how to test ur test branch before u merge?

**Comment by bpg** [comment]
Oh... thanks! I didn't test this case, which seems quite obvious now 😅

**Comment by bpg** [comment]
> OH NO it doesnt work with cloning?

@si458 this should be fixed now.

**Comment by si458** [comment]
thanks @bpg! just waiting a new release now 👍
