### ISSUE TITLE
allow creating tpm

### ISSUE THREAD

**Issue by si458** [bpg/terraform-provider-proxmox#453]
**Is your feature request related to a problem? Please describe.**
currently you cannot add a virtual TPM device and would be nice to add one

**Describe the solution you'd like**
to add a TPM device for Windows Server 2022 / Windows11 Installations

**Describe alternatives you've considered**
create vm then go into proxmox gui and add tpm

**Additional context**
its possible via POST - tpmstate0
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

**Comment by bpg** [comment]
well, not much really, I think it is pretty straight-forward (section 10.2.11 in [the doc](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings)), i just don't have enough spare time to work on this, hence added "help wanted" label.

**Comment by si458** [comment]
ah right ok no worries @bpg, if i get time ill have a look at a PR for you, if i can understand it all haha

**Comment by si458** [comment]
Just wondered if you had time to add this at all?

**Comment by bpg** [comment]
Hi @si458, no, haven't had a chance to look at this feature.

**Comment by bpg** [comment]
Hi @rgl! 👋🏼
Sure, let me take a look :)
