### ISSUE TITLE
proxmox_virtual_environment_vm: startup => down_delay and up_delay options not applied when order not configured

### ISSUE THREAD

**Issue by yoshikakbudto** [bpg/terraform-provider-proxmox#475]
**Describe the bug**

using 0.28.0 version

If i configure only the down_delay or up_delay option without configuring the order, the confgiuration  is not actually applied. 

**To Reproduce**

1. Create a VM resource with only `down_delay` startup option configured:
  ```
  resource "proxmox_virtual_environment_vm" "pulumi_test_node" {
     startup {
        down_delay = "600"
    }
  }
  ```
3. terraform apply (will be applied successfully)
5. Check the VM configuration not applyed
![image](https://github.com/bpg/terraform-provider-proxmox/assets/10331946/6226bee3-0c85-4e14-bd3a-4d400d2f49c4)

 
**Expected behavior**
Shutdowm timeout should be equal to 600 and not the default

**Comment by bpg** [comment]
related to #445

**Comment by bpg** [comment]
https://github.com/all-contributors please add @yoshikakbudto for bug

**Comment by bpg** [comment]
@all-contributors please add @yoshikakbudto for bug

**Comment by bpg** [comment]
Related to: https://github.com/muhlba91/pulumi-proxmoxve/issues/107
