### ISSUE TITLE
Control over the CloudInit interface

### ISSUE THREAD

**Issue by tseeker** [bpg/terraform-provider-proxmox#485]
I am using templates which include a CloudInit image on their `ide0` interface. Because of this, trying to use an `initialization` block while cloning the templates fails.

I would like to be able to specify which IDE interface should be used for the CloudInit image, or to have the provider detect that it isn't on the default interface and none is specified. It should be possible to change the interface without having to recreate the VM.

I have implemented this feature and will submit a PR for it shortly.

**Comment by bpg** [comment]
@all-contributors please add @tseeker for code
