### ISSUE TITLE
Provider fails to detect IP address of VM

### ISSUE THREAD

**Issue by mandrav** [bpg/terraform-provider-proxmox#492]
I 've been using this provider pretty much exclusively since I found out about it. Great work!

The issue I 'm having is that after the first `terraform apply` and the successful creation of the resources, further calls to `terraform apply` hang for the duration of the agent timeout. The agent is running in the VMs, I 'm seeing the IP addresses in the Proxmox interface, all is well. Except for this provider which fails to find the IPs...

Some details about my setup:
* Proxmox has a single NIC, connected to a trunk port on the switch. Only vlan-tagged traffic is allowed through.
* I 'm using cloud-init for user data as well as networking (<- this is important).
* The network interface on the VM is bound to `vmbr0` which is the bridge connected to the trunk port on the switch.
* No vlan is set on the network interface. I want services from inside the VM to access other vlans.
* In my cloud-init network data file, I used to have 1 ethernet interface and 1 vlan bound to that interface (everything was working fine with this setup).
* Recently I made a change to the cloud-init network data file, adding a bridge to the mix and making the network config like this:
  * One network interface
  * One bridge, parent to the network interface
  * One vlan, linked to the bridge
* This broke this provider's ability to read the VM's IP addresses...

Now, before submitting this issue, I took the liberty to have a look at the source code, hoping you won't mind ;-)
I maybe wrong, but this looks like the root of the problem:

https://github.com/bpg/terraform-provider-proxmox/blob/9045183c1dd18ba2ebd3c1afcd7c16e73213bf27/proxmox/nodes/vms/vms.go#L446C1-L450C1

See, not having in-depth knowledge about the source code, it looks to me like if **any** network interface has no IP address assigned, the entire loop is aborted (see the `break` statement). The simple fix I see, if I 'm right, is to change the `break` to `continue`.

Thanks for taking a look at this!

**Comment by mandrav** [comment]
I just built the provider and tested the following fix:
```diff
diff --git a/proxmox/nodes/vms/vms.go b/proxmox/nodes/vms/vms.go
index 7735f6a..eb0854e 100644
--- a/proxmox/nodes/vms/vms.go
+++ b/proxmox/nodes/vms/vms.go
@@ -445,7 +445,7 @@ func (c *Client) WaitForNetworkInterfacesFromVMAgent(

                                                if nic.IPAddresses == nil ||
                                                        (nic.IPAddresses != nil && len(*nic.IPAddresses) == 0) {
-                                                       break
+                                                       continue
                                                }

                                                for _, addr := range *nic.IPAddresses {
```
It works fine with this small change.

**Comment by mandrav** [comment]
Thanks @bpg for the quick response!
PR #493  submitted.

**Comment by bpg** [comment]
@all-contributors please add @mandrav for code,bug
