### ISSUE TITLE
Can't set hostpci

### ISSUE THREAD

**Issue by andstu** [bpg/terraform-provider-proxmox#495]
**Describe the bug**
When I try to set the hostpci I get the error `error updating VM: received an HTTP 500 response - Reason: only root can set 'hostpci1' config for non-mapped devices`. I believe this is because it is not  using the SSH connection

This is my provider config:
```terraform
provider "proxmox" {
  endpoint = var.api_url
  username = "root@pam"
  api_token = var.api_token
  insecure = true
  ssh {
    username = "root"
    agent = true

    node {
    name    = "shipyards"
    address = "192.168.0.100"
    }
  }
}
```
This is my vm config:
```terraform
resource "proxmox_virtual_environment_vm" "gpu" {
  name = "gpu"
  node_name = var.proxmox_host

  clone {
    vm_id = var.template_id
  }

  cpu {
    cores = 8
  }

  memory {
    dedicated = 16384
    floating = 16384
  }

  agent {
    enabled = true
  }

  initialization {
    ip_config {
      ipv4 {
        address = "192.168.1.5/32"
        gateway = "192.168.1.1"
      }
    }
    user_account {
        keys = var.ssh_keys
    }
  }

  boot_order = [
    "ide2",    
    "scsi0",
  ]

  hostpci {
    device = "hostpci0"
    id = "0000:03:00.0"
    rombar = true
    pcie = true
  }

    hostpci {
    device = "hostpci1"
    id = "0000:04:00.0"
    rombar = true
    pcie = true
  }

  reboot = true

}
```

I assumed setting `agent = true` would use my ssh key? I verified that I can connect with ssh using the key normally.

**Comment by bpg** [comment]
Hi @andstu 👋🏼 

When using the API token authentication, the `username` and `password` fields in the `provider` block are ignored, and `api_token` takes precedence. So, in your example the user that owns the token is used with the API calls, not the "root@pam" from the `username` attribute: 

```terraform
provider "proxmox" {
  endpoint = var.api_url
  username = "root@pam"
  api_token = var.api_token
...
}
```

You're right about the SSH connection -- it is used to only for [a small subset](https://registry.terraform.io/providers/bpg/proxmox/latest/docs#ssh-connection) of PVE operations. `hostpci` devices are configured via regular API calls.

As you see from the error message, PVE can manage hostpci only when authenticated as a root user. If you can't use a root token in your environment, I'm afraid the provider can't support this case at the moment.

Can you double-check if your API token belongs to the `root` user?

**Comment by andstu** [comment]
This is the API token I am using.
```
root@proxmox:~# pveum user token list root@pam
┌───────────┬─────────┬────────┬─────────┐
│ tokenid   │ comment │ expire │ privsep │
╞═══════════╪═════════╪════════╪═════════╡
│ test-root │         │      0 │ 0       │
└───────────┴─────────┴────────┴─────────┘
```
This is it in my terraform.tfvars: `api_token="root@pam!test-root=XXXXXXXXXXXXXXXX"`

**Comment by andstu** [comment]
This seems related to #386. I tried setting the CPU architecture and also see the same error.

**Comment by agokhale1** [comment]
My workaround (or hack) is this:
```terraform
provisioner "remote-exec" {
  connection {
    type = "ssh"
    user = "root"
    host = var.proxmox_node_address
    private_key = file("~/.ssh/proxmox_root")
  }

  inline = [
    "qm set ${proxmox_virtual_environment_vm.test_vm.vm_id} -hostpci0 0000:01:00.0,rombar=on,pcie=on",
    "qm reboot ${proxmox_virtual_environment_vm.test_vm.vm_id}"
  ]
}
```

**Comment by zharalim** [comment]
To remove the need for the root user I created a PR to support mapped PCI resources (might need some cleanup & tests still): https://github.com/bpg/terraform-provider-proxmox/pull/500

**Comment by bpg** [comment]
Thanks everyone for the feedback of this ticket!

It looks like root API token auth is not the same as root PAM user auth, and certain operations on PVE are limited to proper root users. While the workaround suggested by @agokhale1 is a good stop-gap solution, and we can technically adopt it in the provider (i.e. run these commands over SSH), the [PR](https://github.com/bpg/terraform-provider-proxmox/pull/500) proposed by @zharalim is a better way to do that!

As the PR is merged, I'm closing this issue as resolved. @andstu please feel free to reopen, or create a new one if this feature doesn't work for you well.

**Comment by bpg** [comment]
@all-contributors please add @zharalim for code

**Comment by TheNotary** [comment]
Hi all, thank for working on this feature.  Could someone (perhaps @zharalim if you have a moment) please share information around how to use "mapped" devices?  I tried using "gpu" on a VM, and while it worked through the provider, the VM couldn't boot.  Are there steps for creating mappings that I'm not following correctly?

**Comment by bpg** [comment]
Hi @TheNotary, based on the error you posted I think you'd need to manually add PCI Device mapping via Datacenter > Resource Mapping UI:
<img width="930" alt="Screenshot 2023-11-11 at 9 01 03 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/0f2cec03-52d7-4607-ba1e-a6cb5f335aaf">
(though I haven't tried this feature myself)

**Comment by zharalim** [comment]
Yes, add a resource mapping to all the nodes with the proper device and you can reference it with the mapping parameter. Use the same mapping name in all the nodes ("gpu" in your config).

**Comment by TheNotary** [comment]
I see, thanks!
