### ISSUE TITLE
Unable to create linux_bridge with 'vlan_aware=false' or 'autostart=false'

### ISSUE THREAD

**Issue by otopetrik** [bpg/terraform-provider-proxmox#519]
**Describe the bug**
Unable to create linux_bridge with `vlan_aware=false` or `autostart=false`

**To Reproduce**
1. Create a resource '....'
```
resource "proxmox_virtual_environment_network_linux_vlan" "vlan200" {
  node_name = var.default_node
  name      = "eth0.200"
} 
resource "proxmox_virtual_environment_network_linux_bridge" "vmbr200" {
  node_name = var.default_node
  name      = "vmbr200"
  address = "99.99.99.99/16"
  vlan_aware = false
  autostart = false
  ports = [
    proxmox_virtual_environment_network_linux_vlan.vlan200.name
  ] 
} 


```
2. Run 'terraform apply'
3. See error
```
proxmox_virtual_environment_network_linux_bridge.vmbr200: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_network_linux_bridge.vmbr200, provider "provider[\"registry.terraform.io/bpg/proxmox\"]" produced an unexpected new value: .autostart: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to proxmox_virtual_environment_network_linux_bridge.vmbr200, provider "provider[\"registry.terraform.io/bpg/proxmox\"]" produced an unexpected new value: .vlan_aware: was cty.False, but now cty.True.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

```

Starting with `vlan_aware` and `autostart` commented out, creating the bridge, and then uncommenting and running apply results in bridge and with `vlan_aware` and `autostart` correctly set to false, with only the `autostart` error above.
The `vlan_aware` error does _not_ appear, so it looks like each is broken a bit differently.

**Expected behavior**
It should be possible to create bridge with vlan_aware set to false and autostart set to false.

**Screenshots**

**Additional context**
- Provider version (ideally it should be the latest version): 0.30
- Terraform version: v1.5.3
- OS (where you run Terraform from): nixos
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by bpg** [comment]
Hey @otopetrik! Thanks for the report 👍🏼 

Was able to reproduce both issues in tests.
