### ISSUE TITLE
Releases of darwin_arm64 fail with error "Error: Failed to retrieve authentication response"

### ISSUE THREAD

**Issue by NekoKeys** [bpg/terraform-provider-proxmox#54]
**Describe the bug**
When running on my m1 mac mini (MacOs ver: 12.0.1) , specifying any release of the provider and attempting to run results in the following error getting printed: "Error: Failed to retrieve authentication response". 

**Temporary workaround**
Building the provider from source on the mac solves the issue.

**Comment by bpg** [comment]
Hi @NekoKeys, thanks for reporting!

I was able to spin up a VM on PVE 7.1 with 0.5.1 version of the provider running on M1 macOS 12.3.1. Didn't notice any errors.
 
Could you try to reproduce the issue while running terraform in the debug mode: `TF_LOG=DEBUG terraform apply -auto-approve` and share the log?

**Comment by NekoKeys** [comment]
Thanks for getting back to me!

I think the issue somehow may have sorted itself out? I just re-tried my terraform module and it successfully applied with no errors with the provider. 

I'll close the issue for now and if it ever pops back up I'll open a new one with a more verbose set of logs/reproduction steps. Thanks!
