### ISSUE TITLE
OpenTF / Change of Terraform license to BSL / Terraform Registry / future

### ISSUE THREAD

**Issue by rafsaf** [bpg/terraform-provider-proxmox#542]
**Is your feature request related to a problem? Please describe.**
Change of Hashicorp license from open source MPL to BSL for terraform.

Problem of using TF alternatives with Terraform Registry since changes in Terraform Registry terms.

**Describe the solution you'd like**
Nothing yet, just describing the issue and starting discussion if the author or other people missed above event.

Using this provider with OpenTF in the future would be nice option (for this to be fair with Terraform Registry and legal, it would probably need to use additional registry other than from HashiCorp, see 3rd link below)

**Describe alternatives you've considered**
.

**Additional context**
- https://opentf.org/
- https://opentf.org/announcement
- https://github.com/opentffoundation/roadmap/issues/24#issuecomment-1699535216

**Comment by bpg** [comment]
This is an interesting development indeed. I don't fully understand yet how BSL for terraform and new terms for HashiCorp's TF registry affect providers.

Personally I would not consider adopting anything other than an open source license.

Now I'm also considering to include [DCO](https://developercertificate.org/) to all contributions as well.

**Comment by bpg** [comment]
As per [this FAQ](https://www.hashicorp.com/license-faq#impact-on-terraform-providers), the license change does not affect individual non-HasiCorps's providers.

**Comment by bpg** [comment]
Created a separate ticket to track OpenTF support:
- https://github.com/bpg/terraform-provider-proxmox/issues/562
