### ISSUE TITLE
full clone not working error POST /api2/json/nodes/nodename/qemu/9000/clone' not implemented

### ISSUE THREAD

**Issue by BillyMyIT** [bpg/terraform-provider-proxmox#547]
Hi,

I'm new to terraform and i'm trying to deploy vm on Proxmox but it's not working :

`resource "proxmox_virtual_environment_vm" "test-TF" {
  count       = 1
  vm_id       = 300
  name        = "test-TF"
  description = "Managed by Terraform"
  tags        = ["test"]

  node_name = "nodename"

  cpu {
    cores   = 2
    sockets = 1
    type    = "host"
  }

  timeout_clone       = 3600
  timeout_start_vm    = 3600
  timeout_reboot      = 3600
  timeout_move_disk   = 3600
  timeout_stop_vm     = 600

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    user_account {
      username = "ubuntu"
    }
  }
  memory {
    dedicated = 4096
  }
  agent {
    enabled = true
  }

  startup {
    order      = 2
    up_delay   = 10
    down_delay = 30
  }

  disk {
    datastore_id = "b1-sda"
    interface    = "virtio0"
    size         = 10
  }
  clone {
    vm_id   = "9000"
    retries = "5"
    full = "true"
    node_name = "nodename"
  }

  network_device {
    bridge = "vmbr0"
  }
  operating_system {
    type = "l26"
  }

  serial_device {}

}
`

I'm trying to use api with a root@pam token id

Let me know if i need to provide mode information

**Comment by bpg** [comment]
Hi @BillyMyIT!

Looking at your template and the error message, I'd like to clarify a few things:
- the template and the error reference "nodename" -- is this the actual name of the PVE node you're using for deployment? That's fine if this is just a masking for sake of opening the issue, the main point is the actual name of your PVE node must be set in the template's `node_name` attributes. 
- the template is make a clone of an existing VM with ID = 9000 from the node "nodename". Does this VM exist on the node?
- run terrafrom apply with debug log will help investigate further. Could you pls. run `TF_LOG=DEBUG terraform apply` and attach the output? It doesn't need to be a full log, just ~20-30 lines before the error + full error message itself.
- is your PVE a cluster, or a single node?

**Comment by Fabiosilvero** [comment]
I encountered the same error, due to a bad copy/paste from Packer Proxmox builder :') 

In Packer code, you have to add the URL `/api2/json` and not on this Terraform provider. To gain time (and therefore lose more in troubleshooting), I copy pasted the value.

Once I removed that suffix to `  endpoint = "https://my.proxmox.server:8006/"`, the Terraform execution worked flawlessly.

**Comment by bpg** [comment]
Oh, that's make sense, thanks for the insight @Fabiosilvero!
