### ISSUE TITLE
Allow linked clones

### ISSUE THREAD

**Issue by AaronSeibert** [bpg/terraform-provider-proxmox#551]
**Is your feature request related to a problem? Please describe.**
Full clones use additional space, take more time when cloning, lots of chatter when using cephfs to back the disks

**Describe the solution you'd like**
Proxmox supports linked clones - we should be able to create linked clones

**Describe alternatives you've considered**
Not really an available alternative out there

**Additional context**

**Comment by AaronSeibert** [comment]
Well, guess this is more of a "document and maybe change the default"

https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmoxtf/resource/vm.go#L165

Found that the provider does accept a "full" parameter in the clone block, but it's not documented.
Also, proxmox default handling for this may be preferred over defaulting to "true" for a full clone:

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/clone

The implication is that "full" is optional, when cloning a vm it will always be full but when cloning a template pve will try a linked clone by default.

**Comment by otopetrik** [comment]
The documentation for `full` appears to be missing, that is a bug.

However changing the defaults may cause problems.
When using ZFS, fast backups can be done using [PVE-zsync](https://pve.proxmox.com/wiki/PVE-zsync), it does not seem to work at all when operating on linked clones.
Silently changing defaults might result in new VMs without the ability to fast backup. That could be especially painful for users who discover `terraform-provider-proxmox` first and `PVE-zsync` later.

Making the field `full` non-optional and documenting trade-offs may be the best solution.
(even on ZFS, linked clones can be useful - for short term or immutable VMs)

**Comment by bpg** [comment]
I'm closing this issue as documentation for clone type [has been added](https://github.com/bpg/terraform-provider-proxmox/pull/797/files), and the default behavior is unlikely to change. 
Feel free to reopen if new information arises.
