### ISSUE TITLE
proxmox_virtual_environment_file clobbers existing file

### ISSUE THREAD

**Issue by mritalian** [bpg/terraform-provider-proxmox#571]
`proxmox_virtual_environment_file` clobbers existing file if it happens to exist, without warning.

**To Reproduce**
1. Upload an iso manually
2. Now upload the same file using "proxmox_virtual_environment_file" using terraform apply
3. You only see one iso

```
resource "proxmox_virtual_environment_file" "fedora_coreos" {
	content_type = "iso"
	datastore_id = "local"
	node_name    = var.proxmox_node_name

	source_file {
		path = "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/38.20230819.3.0/x86_64/fedora-coreos-38.20230819.3.0-live.x86_64.iso"
	}
}
```

**Expected behavior**
Easy solution: fail the operation and not clobber a file that might not be the same?

**Comment by bpg** [comment]
Hi @mritalian! 👋🏼

Thanks for the report! Although I'm a bit reluctant to straight up throw an error in this case, as it will mean a backward-incompatible change. I would rather make it a warning and add a separate flag to the file resource to opt-in for failing an upload if the file already exists on PVE.

**Comment by mritalian** [comment]
@bpg hey there.  Yeah, I'd suggest a warning.   And something in the docs, see PR.

**Comment by mritalian** [comment]
Related issue: if the resource is deleted by another mechanism, this resource doesn't re-create it.

Looking at `fileRead` inside `proxmoxtf/resource/file.go` the only code path executed in case the file doesn't exist is:

`d.SetId("")`

I suspect this doesn't mark the resource as changed and terraform doesn't re-create it.

**Comment by bpg** [comment]
@all-contributors please add @mritalian for testing, doc
