### ISSUE TITLE
Add support to allow cloudinit interface type to be scsi

### ISSUE THREAD

**Issue by 0xinterface** [bpg/terraform-provider-proxmox#575]
**Is your feature request related to a problem? Please describe.**
Currently cloudinit will not run if bios is set to ovmf (uefi) since the interface type for cloudinit drive for ideN will not be detected in uefi

**Describe the solution you'd like**
Expand the options of interface parameter inside the initialization block to allow for specifying scsiN 

**Describe alternatives you've considered**
One can manually remove the cloudinit drive in hardware section for guest and re-add it with scsi as interface type but that would defeat the purpose of using terraform in the first place

**Additional context**
The reason for opt into ovmf for bios is because when there is a need for provisioning vm with GPUs passthrough, bios and machine type have to be set to ovmf and q35 in order it to work, and cloudinit would naturally be the way for the installation of graphics driver during provisioning process. 

[a proxmox forum post describing the problem](https://forum.proxmox.com/threads/cloud-init-image-only-applies-configuration-on-second-boot.93414/)

**Comment by 0xinterface** [comment]
https://github.com/bpg/terraform-provider-proxmox/blob/b9106ff93d3a162605d36fa5482cc940d0a2a312/proxmoxtf/resource/validator/vm.go#L252

right now the only thing that seems to prevent one from creating a cloudinit drive with scsi interface is this validator function, may I know if it is possible to add "scsi1" and "scsi2" to the code or are there some concerns that will need to be dealt with first?

**Comment by bpg** [comment]
Hi @0xinterface! 👋🏼
Thanks for the report, that feature is indeed missing! While updating the validator could be a quick fix, we also need to check a few other places where we use the cloudinit drive, mainly to avoid conflicts with the cdrom. So, adding proper support for scsiX will require some work and testing to make sure it covers all the use cases.

**Comment by bpg** [comment]
@all-contributors please add @0xinterface for ideas

**Comment by bpg** [comment]
Hey @0xinterface! I've added support for scsi and sata interfaces in #598.
But to be honest, I don't quite understand why `ide2` doesn't work for you?

I've used this template:
```hcl
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name = "575-cloudinit-scsi"

  node_name = var.virtual_environment_node_name
  vm_id     = 575
  machine   = "q35"
  bios      = "ovmf"

  agent {
    enabled = true
  }

  efi_disk {
    datastore_id = "local-lvm"
    file_format  = "raw"
    type         = "4m"
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = "local:iso/jammy-server-cloudimg-amd64.img"
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 20
  }

  initialization {
#    interface = "ide2" -- this is set by default
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_account {
      username = "ubuntu"
      password = "ubuntu"
      keys     = [trimspace(data.local_file.ssh_public_key.content)]
    }
    vendor_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }

  network_device {
    bridge = "vmbr0"
  }

  operating_system {
    type = "l26"
  }

}

data "local_file" "ssh_public_key" {
  filename = "./id_rsa.pub"
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name

  source_raw {
    data = <<EOF
#cloud-config
runcmd:
    - apt update
    - apt install -y qemu-guest-agent net-tools
    - timedatectl set-timezone America/Toronto
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/vendor-cloud-init-done
    EOF

    file_name = "cloud-config.yaml"
  }
}
```
which produced this VM without any errors:
<img width="787" alt="Screenshot 2023-10-01 at 10 11 15 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/6e0adaa1-5d92-4d79-a419-16bcb1fc49b5">
