### ISSUE TITLE
hostpciX not handled correctly when planning

### ISSUE THREAD

**Issue by michaelze** [bpg/terraform-provider-proxmox#577]
**Describe the bug**
We are currently on our way to upgrade the terraform-provider-proxmox to the latest version. This includes handling manual configuration that could not be applied via terraform with older versions of the provider (in our case hostpci devices).

After adding the hostpci devices to the vm resources (again, those devices have been previously added to the vms by hand because this was not possible with this provide in older versions), `terraform plan` tries to add these devices. I'm not that familiar with terraform in order to decide whether this is working as intended or not, but I concluded that it is and that I have to `terraform plan -refresh-only` in order to update my terraform state to the real state.

This however does not include the hostpci device entries in the refresh plan.

**To Reproduce**
1. Create a vm resource without a hostpci device
2. Run `terraform apply`
3. Manually add a hostpci device to the vm
4. Modify the vm resource by adding the very same hostpci device
5. Run `terraform plan -refresh-only`
6. The hostpci device is not included in the refresh plan

```terraform
resource "proxmox_virtual_environment_vm" "recreate_when_hostpci_changes" {
  name        = "recreate-when-hostpci-changes"
  description = "## TEST recreate-when-hostpci-changes"

  node_name = "foo"

  started = false

  cpu {
    cores = 1
  }

  memory {
    dedicated = 512
  }

  operating_system {
    type = "l26"
  }

  network_device {
    bridge = "vmbr0"
  }

### only add this after the vm has been created
#  hostpci {
#   device = "hostpci0"
#    id = "81:00.8"
#    rombar = true
#  }
}
```

**Expected behavior**
I would expect the hostpci device to appear in the refresh plan.

**Comment by bpg** [comment]
Hey @michaelze! 👋🏼 

Thanks a lot for the report and the PR, that's a good catch!
