### ISSUE TITLE
Can not create proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by devopski** [bpg/terraform-provider-proxmox#623]
Code:
```
resource "proxmox_virtual_environment_file" "centos_container_template" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = "proxmox"

  source_file {
    path = "https://download.proxmox.com/images/system/centos-9-stream-default_20221109_amd64.tar.xz"
    insecure = true
  }
}
```

Error:
```
proxmox_virtual_environment_file.centos_container_template: Creating...
╷
│ Error: open /var/tmp\download1747534024: The system cannot find the path specified.
│
│   with proxmox_virtual_environment_file.centos_container_template,
│   on main.tf line 53, in resource "proxmox_virtual_environment_file" "centos_container_template":
│   53: resource "proxmox_virtual_environment_file" "centos_container_template" {
│
╵
```

**Comment by bpg** [comment]
Hi @devopski! 👋🏼 

Thank you for the report! The proxmox_virtual_environment_file is a commonly used resource and has been tested in various environments, which leads me to believe that this issue may be somewhat environment-specific. 
Could you please provide more details about your environment and use case, as per [issue template](https://github.com/bpg/terraform-provider-proxmox/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)? This information will help developers investigate further. I'm particularly interested in:
> **Additional context**
> Add any other context about the problem here.
> - Single or clustered Proxmox:
> - Provider version (ideally it should be the latest version):
> - Terraform version:
> - OS (where you run Terraform from):
> - Debug logs (`TF_LOG=DEBUG terraform apply`):

Thanks!

**Comment by devopski** [comment]
Single or clustered Proxmox: **Single**
Provider version (ideally it should be the latest version): **0.34.0**
Terraform version: **Terraform v1.5.0**
OS (where you run Terraform from): **Windows 10**
Debug logs (TF_LOG=DEBUG terraform apply): [logs.log](https://github.com/bpg/terraform-provider-proxmox/files/12924929/logs.log)

**Comment by bpg** [comment]
Thanks @devopski. Could you please check if your provider's config has `tmp_dir` specified?
```
provider "proxmox" {
  ...
  tmp_dir  = "/var/tmp"
}
```

This optional parameter specifies an override for the temp folder on a local machine where provider is running.

**Comment by devopski** [comment]
Thak you @bpg 
After deleting `tmp_dir  = "/var/tmp"` from my provider section works fine.

**Comment by bpg** [comment]
Thanks for confirming! I think we should remove that line from the example in docs.
