### ISSUE TITLE
Cache invalid argument in vms

### ISSUE THREAD

**Issue by dgarner-cg** [bpg/terraform-provider-proxmox#629]
**Describe the bug**
Validate returning error for `cache = writeback`

**To Reproduce**
Create VM with disk writeback in body.

Please also provide a minimal Terraform configuration that reproduces the issue.

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_file.debian_cloud_image.id
    interface    = "scsi0"
    size         = 20
    discard      = "on"
    ssd          = true
  }

**Expected behavior**
Cache to be valid as per documentation

**Screenshots**

![image](https://github.com/bpg/terraform-provider-proxmox/assets/61340105/e842bfad-2d4b-4b32-b058-6abe963dcd52)

**Comment by bpg** [comment]
Hi @dgarner-cg! 👋🏼 
The example you've posted in the issue does not have the `cache` attribute 🤔, so I suspect your template may have gotten a bit scrambled. You can find an example of how to use the `cache` attribute here: https://github.com/bpg/terraform-provider-proxmox/blob/main/example/resource_virtual_environment_vm.tf#L48
These examples are part of the acceptance test suite and are guaranteed to work. 🙂

**Comment by dgarner-cg** [comment]
Apologies, lol. It was there when I had the error pop up, I've been having a rough time getting this working, even using the templates or slightly altering them, but I've been attempting to spin up 3 instead of one, so perhaps I am altering things I shouldn't be. However, the code when I attempted to get that working and it would not was literally before ssd = true, `cache = "writeback"`

The main issue seems to stem from it saying that things like in the virtual-machine tf aren't expected there, so perhaps I have structure incorrect. Let me try and get to that point again and if I have issues, will post entire problematic cache code.

Right now I'm attempting to sort out how to use api token for initial log on instead of username and password but getting errors :$

**Comment by bpg** [comment]
Sounds good, @dgarner-cg! Please reach out if you need any help. And please close the ticket if you managed to solve the issue :)
