### ISSUE TITLE
Can't resize (increase) disk in VM

### ISSUE THREAD

**Issue by ratiborusx** [bpg/terraform-provider-proxmox#632]
**Describe the bug**
Can't increase a disk size, some error about ownership - can change it via GUI though.
Not sure what's going on here, from what i've read people don't have such issues (at least i couldn't find anything similar in search)...

**To Reproduce**
1. Create a resource:
```
resource "proxmox_virtual_environment_vm" "base" {
  name        = "astra-test-vm"
  description = "Managed by Terraform"
  tags        = sort(["terraform", "astra-1.7.4-base"])

  node_name     = "prox-srv1"
  #vm_id         = 4321
  migrate       = true
  on_boot       = true
  #reboot        = true
  #scsi_hardware = "virtio-scsi-single"

  agent {
    enabled = true
  }

  clone {
    node_name    = "prox-srv1"
    retries      = 3
    vm_id        = 1001
  }

  cpu {
    architecture = "x86_64"
    cores        = 1
    numa         = true
    sockets      = 2
    type         = "host"
  }

  memory {
    dedicated    = 4096
  }

  disk {
    datastore_id = "vzdata"
    discard      = "on"
    file_format  = "qcow2"
    interface    = "scsi0"
    iothread     = true
    size         = 50
    ssd          = true
  }

  initialization {
    datastore_id = "vzdata"
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  network_device {
    bridge = "vmbr0"
  }

  operating_system {
    type = "l26"
  }

  serial_device {
    device = "socket"
  }
  lifecycle {
    ignore_changes = [
      initialization
    ]
  }
}
```
2. Modify disk size 50->60
3. Run 'terraform apply'
4. See error:
```
module.proxmox.data.proxmox_virtual_environment_version.prox_srv3: Reading...
module.proxmox.proxmox_virtual_environment_vm.base: Refreshing state... [id=104]
module.proxmox.data.proxmox_virtual_environment_version.prox_srv3: Read complete after 0s [id=version]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.proxmox.proxmox_virtual_environment_vm.base will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "base" {
        id                      = "104"
        name                    = "astra-test-vm"
        tags                    = [
            "astra-1.7.4-base",
            "terraform",
        ]
        # (24 unchanged attributes hidden)

      ~ disk {
          ~ size              = 50 -> 60
            # (8 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.proxmox.proxmox_virtual_environment_vm.base: Modifying... [id=104]
╷
│ Error: Cannot resize vzdata:104/vm-104-disk-0.qcow2 in VM 104 configuration, it is not owned by this VM!
│
│   with module.proxmox.proxmox_virtual_environment_vm.base,
│   on ../modules/proxmox-base/main.tf line 24, in resource "proxmox_virtual_environment_vm" "base":
│   24: resource "proxmox_virtual_environment_vm" "base" {
│
╵
```

**Expected behavior**
Disk size increased to specified value.

**Additional context**
- Single or clustered Proxmox: PVE 8.0.3 cluster of 3 nodes with local storage
- Provider version (ideally it should be the latest version): 0.35.0
- Terraform version: 1.5.7
- Ubuntu 22.04 LTS (WSL2)
- From resource's name one could guess that's i'm using module, if that's important

P.S.
Didn't work with Proxmox much before (mostly GUI menial tasks) but in the new place we already created a 3-node cluster and i immediately knew i'd want to use a Terraform for that. People suggested Telmate's provider citing their previous experiences but after one glance i realized i want this one and not Telmate's and it was an easy-to-force decision considering i'm almost the only user of Terraform here (still rather meh at it). Still testing waters so to say and hope for incremental improvements of the provider. Wanted to test it on simple resources before i'd try to iterate over big map of objects using for_each.

**Comment by otopetrik** [comment]
Thanks for the report!
Looks like it is related to #606 introduced in the last version [v0.35.0](https://github.com/bpg/terraform-provider-proxmox/releases/tag/v0.35.0).

For short term workaround, using version 0.34.0 might be good idea.

Change #606 allows one VM 1 to use disks that are part of different VM 2.
There is a check, to make sure that changing the size of that disk in VM 1 is not allowed (it would resize the disk actually belonging to VM 2).

That is the error you are seeing is result of that check:
> │ Error: Cannot resize vzdata:104/vm-104-disk-0.qcow2 in VM 104 configuration, it is not owned by this VM!

The check was tested on ZFS storage, but it seems that Proxmox uses different pattern for directory storage.

**Comment by ratiborusx** [comment]
Damn, you're lightning fast, dudes! If i knew i'd post an issue yesterday! :)
> The check was tested on ZFS storage, but it seems that Proxmox uses different pattern for directory storage.

Yep, i remember they mention different notations for different storage backends. But i didn't use anything aside directory so far so can't tell.
> For short term workaround, using version 0.34.0 might be good idea.

Thanks, I'll keep that in mind! But seeing how frequently this provider gets updated i'm pretty sure you'll bake out something next week. Meanwhile i'll try to work on creating a bunch of VMs in one go with iteration.

**Comment by bpg** [comment]
@all-contributors please add @ratiborusx for bug
