### ISSUE TITLE
Problem create LXC from local file template

### ISSUE THREAD

**Issue by AndrzejMilewski** [bpg/terraform-provider-proxmox#637]
Hello.
I try to create new container and on console. I would like to create new container from local downloaded file local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz 

### This file is on my storage
root@pve:/var/log# pvesm list local
Volid                                                       Format  Type           Size VMID
local:iso/debian-11.7.0-amd64-netinst.iso                   iso     iso       407896064
local:vztmpl/debian-11-turnkey-openldap_17.1-1_amd64.tar.gz tgz     vztmpl    221649427
local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz     tgz     vztmpl    214203058
local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz      txz     vztmpl      2983844
local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst        tzst    vztmpl    123187438

### error terraform

proxmox_virtual_environment_container.alpine_container: Creating...
╷
│ Error: error creating container: received an HTTP 500 response - Reason: unable to parse directory volume name 'vztmpl/alpine-3.18-default_20230607_amd64.tar.xz '
│
│   with proxmox_virtual_environment_container.alpine_container,
│   on provider.tf line 30, in resource "proxmox_virtual_environment_container" "alpine_container":
│   30: resource "proxmox_virtual_environment_container" "alpine_container" {

### my code

terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.35.0"
    }
  }
}

provider "proxmox" {
  endpoint = var.endpoint-tfvars
  username = var.username-tfvars
  password = var.password-tfvars
  insecure = true
}

resource "proxmox_virtual_environment_container" "alpine_container" {
  description = "Managed by Terraform"

  node_name = "pve"
  vm_id     = 1234

  initialization {
    hostname = "terraform-provider-proxmox-alpine-container"

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  network_interface {
    name = "veth0"
  }

  operating_system {
    template_file_id = "local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz "
    type             = "alpine"

  }

}

**Comment by bpg** [comment]
Hi @AndrzejMilewski!
It looks like you've copy-pasted an extra space at the end of the filename: `...tar.xz "` in the template.

**Comment by AndrzejMilewski** [comment]
"Hi BGP. Yes, you are right, the extra space was a problem. Thank you for pointing out my mistake."

**Comment by AndrzejMilewski** [comment]
My mistake

**Comment by AndrzejMilewski** [comment]
close, my mistake
