### ISSUE TITLE
How to use path_in_datastore with VM?

### ISSUE THREAD

**Issue by devopski** [bpg/terraform-provider-proxmox#651]
Hello, 
I don't know how to use **path_in_datastore**. My goal is to mount centos.qcow2 file which I uploaded directly to Proxmox filesystem. Could you please help?

Option 1
```
  disk {
    datastore_id = ""
    size = 100
    interface    = "virtio0"
    file_format = "qcow2"
    path_in_datastore = "/var/lib/vz/template/qemu/centos.qcow2"
  }
```
![image](https://github.com/bpg/terraform-provider-proxmox/assets/77720864/f648f61e-a737-48f9-a256-87b32ff6f47c)

Option 2
```
  disk {
    datastore_id = "local"
    size = 100
    interface    = "virtio0"
    file_format = "qcow2"
    path_in_datastore = "/var/lib/vz/template/qemu/centos.qcow2"
  }
```
![image](https://github.com/bpg/terraform-provider-proxmox/assets/77720864/3fdcfa24-36e6-44e3-bfbb-0fd653e99049)

**Comment by bpg** [comment]
Hi @devopski!

For your use case you can use few methods to initialize a disk from a .qcow2 file.

- use `file_name` attribute to override the name of the uploading file, so Proxmox won't complain about unsupported extension.
  ```terraform
  resource "proxmox_virtual_environment_vm" "centos_vm" {
    name        = "test"
    node_name   = "pve"
    ...
  
    disk {
      datastore_id = "local-lvm"
      file_id      = proxmox_virtual_environment_file.centos_cloud_image.id
      interface    = "virtio0"
      iothread     = true
      discard      = "on"
      size         = 20
    }
    ...
  }
  
  resource "proxmox_virtual_environment_file" "centos_cloud_image" {
    content_type = "iso"
    datastore_id = "local"
    node_name    = var.virtual_environment_node_name
  
    source_file {
      path = "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1503.qcow2"
      # or if you already have it locally
      # path = "/home/user/Downloads/CentOS-7-x86_64-GenericCloud-1503.qcow2"
      file_name = "centos.img"
    }
  }
  ```
- if file is already on PVE in a correct datastore location, you can use `pvesm list <datastore id>` to list file IDs, then use the ID as `disk.file_id` value:
  ```
  root@pve:~# pvesm list local
  Volid                                         Format  Type            Size VMID
  local:iso/centos.img                          iso     iso       1004994560
  local:iso/debian-11-generic-amd64.img         iso     iso       2147483648
  local:iso/talos-amd64-3.iso                   iso     iso         84588544  
  ...
  ```
  ```
  resource "proxmox_virtual_environment_vm" "centos_vm" {
    name        = "test"
    node_name   = "pve"
    ...
  
    disk {
      datastore_id = "local-lvm"
      file_id      = "local:iso/centos.img"
      interface    = "virtio0"
      iothread     = true
      discard      = "on"
      size         = 20
    }
    ...
  }  
  ``` 

The `path_in_datastore` is a _computed_ attribute that is set by provider, and should be only  used to handle a special use case when a disk owned by one VM is used by another VM. You can find more details about it here: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#example-attached-disks
I don't really think it is applicable for your use case. 


Hope this helps!

**Comment by devopski** [comment]
@bpg Thank you! This exactly what I was looking for.
