### ISSUE TITLE
file upload on with multiple NICs not working

### ISSUE THREAD

**Issue by DanielHabenicht** [bpg/terraform-provider-proxmox#687]
**Describe the bug**
Sorry to bother you yet again! 
With a Proxmox instance that has multiple NIC (Network Ports) on different networks (which might not be reachable via the terraform client) the right one can not be determined, which leads to selecting the wrong IP address for any SSH-related workaround this module uses. 

**To Reproduce**
1. Proxmox with multiple configured CIDR NICs: 
![image](https://github.com/bpg/terraform-provider-proxmox/assets/13590797/d7e6ff64-c643-44eb-ba39-938839cb1a26)
3. Use `proxmox_virtual_environment_file` to write any file
4. Run `terraform apply`
5. See error

```bash
╷
│ Error: failed to open SSH client: failed to dial 10.0.0.2:22: dial tcp 10.0.0.2:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
│
│   with proxmox_virtual_environment_file.cloud_config,
│   on main.tf line 16, in resource "proxmox_virtual_environment_file" "cloud_config":
│   16: resource "proxmox_virtual_environment_file" "cloud_config" {
│
╵
```

**Expected behavior**
That it finds the right IP! :D
The best workaround would probably be to define another provider variable (or use hostname resolution of the provided URL), instead of magically detecting it via the network interfaces. 

**Additional context**
Single or clustered Proxmox: Single
Provider version (ideally it should be the latest version): 0.37.0
Terraform version: v1.3.7
OS (where you run Terraform from): Windows 10
Debug logs (TF_LOG=DEBUG terraform apply):
Proxmox Virtual Environment 8.0.4

**Comment by bpg** [comment]
Hey @DanielHabenicht!

That's a known limitation with the configuration you've described. It can be a bit tricky to automagically figure out the right adapter because there are so many ways people set up their networks, and sometimes they get pretty creative with it.

Please check out the [SSH Connection](https://registry.terraform.io/providers/bpg/proxmox/latest/docs#ssh-connection) section in the docs, "Node IP address used for SSH connection" block. You can specify which IP the SSH client should connect to, per PVE node.

**Comment by DanielHabenicht** [comment]
Alright, sorry I overlooked that. It was kind of late here already. 
I will send you a PR with some documentation changed on the resources `proxmox_virtual_environment_vm` and `proxmox_virtual_environment_file`. To state that they use SSH and probably need extra configuration.

**Comment by otopetrik** [comment]
This:
https://github.com/bpg/terraform-provider-proxmox/blob/64c67d947362e2653feaab7fa9ffb3b6016d0650/proxmoxtf/provider/provider.go#L184-L189
and this:
https://github.com/bpg/terraform-provider-proxmox/blob/64c67d947362e2653feaab7fa9ffb3b6016d0650/fwprovider/provider.go#L410-L415
does not seem right.

It just uses the first interface with an address.
It should first try the interface which has `d.Gateway` or `d.Gateway6` set, only if there is no interface with a gateway, then it should fall back to the current behavior.

Unless Proxmox node itself (the host, not a VM)  is used as a router for a home network, the user is very likely accessing the node using the same interface the node uses to connect to the internet.
