### ISSUE TITLE
module not work.

### ISSUE THREAD

**Issue by sor88** [bpg/terraform-provider-proxmox#695]
**Describe the bug**
When I create tf modules with proxmox_virtual_environment_vm, I get error:
❯ terraform init

Initializing the backend...
Initializing modules...

Initializing provider plugins...
- Reusing previous version of bpg/proxmox from the dependency lock file
- Finding latest version of hashicorp/proxmox...
- Using previously-installed bpg/proxmox v0.37.0
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/proxmox: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/proxmox
│ 
│ Did you intend to use bpg/proxmox? If so, you must specify that source address in each module which requires that provider. To see which modules are currently depending on
│ hashicorp/proxmox, run the following command:
│     terraform providers

**Comment by ratiborusx** [comment]
Hey!
You probably didn't specify "required_providers" in child module:
```
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
      version = ">= 0.37.0"
    }
  }
  required_version = ">= 0.13"
}
```
Othen than that i have no ideas as of now - i already wrote a module for my cluster (with some specifics) and it works fine.
Maybe you could provide your root and child module manifests?

**Comment by sor88** [comment]
Yes!!! its work )) thank's.

**Comment by gregbrant2** [comment]
Adding `required_version` was the solution I needed to get off the ground with OpenTofu. 

It took some googling and luck to find this so I'm including the full error message below to help others find this solution.

```
Initializing provider plugins...
- Finding latest version of bgp/proxmox...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider bgp/proxmox: provider registry registry.opentofu.org does not have
│ a provider named registry.opentofu.org/bgp/proxmox
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module.
│ To see which modules are currently depending on bgp/proxmox, run the following command:
│     tofu providers
│
│ If you believe this provider is missing from the registry, please submit a issue on the OpenTofu Registry
│ https://github.com/opentofu/registry/issues/
```

**Comment by bpg** [comment]
In the error message the provider’s name is misspelled. Should be `bpg/proxmox`
