### ISSUE TITLE
proxmox_virtual_environment_file:  backups content_type erroring on apply

### ISSUE THREAD

**Issue by DanielHabenicht** [bpg/terraform-provider-proxmox#700]
**Describe the bug**
Errors when trying to create a backup on a Proxmox 8 server. 

**To Reproduce**
1. Create a resource 
```
resource "proxmox_virtual_environment_file" "backup" {
  content_type = "backup"
  datastore_id = "local"
  node_name    = "pve"

  source_file {
    path = "vzdump-lxc-100-2023_11_08-23_10_05.tar"
  }
}
```

```
proxmox_virtual_environment_file.backup: Creating...
╷
│ Error: failed to create file /var/lib/vz/backup/vzdump-lxc-100-2023_11_08-23_10_05.tar: file does not exist
│
│   with proxmox_virtual_environment_file.backup,
│   on main.tf line 25, in resource "proxmox_virtual_environment_file" "backup":
│   25: resource "proxmox_virtual_environment_file" "backup" {
│
╵
```

**Expected behavior**
Seems like on Proxmox 8 the folder changed to `/var/lib/vz/dump`.

**Additional context**
Single or clustered Proxmox: Single
Provider version (ideally it should be the latest version): 0.37.0
Terraform version: v1.3.7
OS (where you run Terraform from): Windows 10
Debug logs (TF_LOG=DEBUG terraform apply):
Proxmox Virtual Environment 8.0.4

**Comment by DanielHabenicht** [comment]
Should I change the upload path?

**Comment by bpg** [comment]
> Should I change the upload path?

Yes, I think it makes sense. This feature probably was never tested. From what I can see on the Proxmox forums, `/var/lib/vz/dump` has been used for quite a while, at least since 7.x.

**Comment by DanielHabenicht** [comment]
Seems like it is configured here:
https://github.com/bpg/terraform-provider-proxmox/blob/0eeb7a7fd924f4cd09e424219c532e55cc3ea721/proxmoxtf/resource/validator/vm.go#L56

and used directly as path here: 

https://github.com/bpg/terraform-provider-proxmox/blob/0eeb7a7fd924f4cd09e424219c532e55cc3ea721/proxmox/ssh/client.go#L158-L160

The easiest solution would be to rename to `backup` to `dump` (probably a breaking change for anybody using it. But this should be nobody, as it is currently unusable) or we add an if statement.
