### ISSUE TITLE
Container description is always showed as changed when heredoc syntax

### ISSUE THREAD

**Issue by bpg** [bpg/terraform-provider-proxmox#721]
### Discussed in https://github.com/bpg/terraform-provider-proxmox/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **Xel-Naha** November 13, 2023</sup>
hi there,

i've just started using this provider and looks promising, so thanks for that to begin with.

I've created a test container on my cluster and noticed that when I did a second apply the environment wanted to make some changes eventhough nothing had changed:

> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
> ```
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   # module.envs.module.dev.proxmox_virtual_environment_container.ubuntu_container[0] will be updated in-place
>   ~ resource "proxmox_virtual_environment_container" "ubuntu_container" {
>       ~ description   = <<-EOT
>             test
>         EOT
>         id            = "101"
>         tags          = []
>         # (6 unchanged attributes hidden)
> 
>         # (3 unchanged blocks hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```
the tf config is pretty simple description = "test"

looking at the notes section it almost looks like a line feed is added:

![image](https://github.com/bpg/terraform-provider-proxmox/assets/100222761/3d3812bc-d9b1-49ed-a577-7b278b500cc5)

am I doing something wrong, or would this be a bug?</div>

**Comment by bpg** [comment]
I can't reproduce this issue on Mac / Linux, so I suspect there is something to do with Windows EOL characters.
@Xel-Naha or anyone else who +1-ed this bug, could you please confirm if you're running TF from Windows?

**Comment by geoshapka** [comment]
i have this bug also
my system is ubuntu in WSL, terraform from official source 1.6.5 and proxmox 8.0.4
version of provider was 0.38.1, update to 0.39.0 did not help
i haven`t yet updated to proxmox 8.1, maybe this will help?
@bpg do you need more info?

**Comment by bpg** [comment]
Hi @geoshapka! 👋🏼 
(nice account name btw :))

Would you be able to zip your .tf file and attach here? 
Thanks!

**Comment by geoshapka** [comment]
Here, this is abridged version of my setup
i checked, it still has same bug
[test-lxc.zip](https://github.com/bpg/terraform-provider-proxmox/files/13533928/test-lxc.zip)

**Comment by bpg** [comment]
Thanks, but nothing really stands out in the templates you've attached.

BTW, I don't see it using heredoc style, i.e.
```
description   = <<-EOT
    some desc
EOT
```
but you still have the error? 🤔

I'd love to see some minimal example that causes the issue, preferably with debug logs.

I've ran several tests on windows / linux / mac with this template, using tabs/spaces/LF/CRLF -- without any problems. Apply & re-apply shows no difference:

```hcl
resource "proxmox_virtual_environment_container" "test_container" {
  node_name = var.virtual_environment_node_name

  disk {
    datastore_id = "local-lvm"
    size         = 8
  }

  started = false

  description = <<-EOT
  some desc
  EOT

  initialization {
    hostname = "test"

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  network_interface {
    name = "vmbr0"
  }

  operating_system {
    template_file_id = proxmox_virtual_environment_file.ubuntu_container_template.id
    type = "ubuntu"
  }
}

resource "proxmox_virtual_environment_file" "ubuntu_container_template" {
  content_type = "vztmpl"
  datastore_id = "local"
  node_name    = "pve"

  source_file {
    path = "http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
  }
}
```

**Comment by geoshapka** [comment]
That\`s the problem - i don`t use heredoc, i believe it is not needed here, and it worked for some time
changing in variables
```
description = "some desc"
```
to
```
description = <<-EOT
some desc
EOT
```
fixed it, but its annoying, no?

**Comment by geoshapka** [comment]
```
resource "proxmox_virtual_environment_container" "test_container" {
  node_name = "pve-beelink-minis12"
  disk {
    datastore_id = "local-zfs"
    size         = 2
  }
  started     = false
  description = "some desc"

  initialization {
    hostname = "test"
  }
  network_interface {
    name = "vmbr0"
  }
  operating_system {
    template_file_id = "bulk:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
    type             = "ubuntu"
  }
}
```
here is my absolute minimum for creating this bug
changing `description = "some desc"` to `description = "some desc\n"` also fixes it

seems like proxmox is putting a newline there and provider is seeing this as change

**Comment by bpg** [comment]
Ah, I understand now! It turns out there was no heredoc description in the template to begin with. 🤦🏼‍♂️

**Comment by bpg** [comment]
@all-contributors please add @geoshapka for bug, testing
