### ISSUE TITLE
 GetResponseData.data.memory changed from int64 to string in api in qemu-server 8.0.8

### ISSUE THREAD

**Issue by sbilo** [bpg/terraform-provider-proxmox#727]
**Describe the bug**
When running against the latest proxmox api the run fails due to a schema type change.
see also: https://bugzilla.proxmox.com/show_bug.cgi?id=5048

**To Reproduce**
1. Create a vm resource
2. Run terraform apply
3. See error:
   `Reason: json: cannot unmarshal string into Go struct field GetResponseData.data.memory of type int64`

Please also provide a minimal Terraform configuration that reproduces the issue.

```
resource "proxmox_virtual_environment_vm" "test-vm" {
  vm_id       = 1111
  node_name = "pve"
  memory {
    dedicated = 16384
  }
}
```

**Expected behavior**
The resource gets created without errors

**Comment by bpg** [comment]
Thanks for the report, @sbilo & @noriban!
That seems to be a trend with Proxmox silently converting int -> string 😞 

I'll take a look and push a fix soon.
