### ISSUE TITLE
Datastore name regex validation error

### ISSUE THREAD

**Issue by midoriiro** [bpg/terraform-provider-proxmox#732]
My data store name is composed of dots `terraform.proxmox.storage.compute.zen`. But the regex only permit underscores or dashes:

https://github.com/bpg/terraform-provider-proxmox/blob/a96a3a9641a5d7c387e65ea17d13ddbc82054bfd/proxmoxtf/resource/validator/file.go#L42

Any chance to permit that ?

**Error message:**
`Error: expected template_file_id to be a valid file identifier (datastore-name:iso/some-file.img), got terraform.proxmox.storage.compute.zen:vztmpl/zen-dns-0.1.tar.zst`

**Expected Behavior:**
Dots in data store name should be permitted.

**Comment by bpg** [comment]
Thanks @midoriiro, that's definitely something that provider should allow.

**Comment by bpg** [comment]
@all-contributors please add @midoriiro for bug
