### ISSUE TITLE
Reboot needed after cloud-init has been applied [Resolved]

### ISSUE THREAD

**Issue by TheFrisianClause** [bpg/terraform-provider-proxmox#736]
**Describe the bug**
Strange bug... 
When deploying a VM with cloud-init, the Terraform job changes the hardware etc. But not the cloud-init. 
But after guest rebooting the VM via the Proxmox GUI the hostname changed to the one defined and cloud-init has been applied.

So what happens here? Is this a known issue or a new one?

**To Reproduce**
1. Create template (alma9)
2. Deploy template with Terraform and specified settings
3. It is errorless but when Terraform is busy provisioning the VM, it keeps doing it. Until you reboot the VM manually via the Proxmox GUI, then it will continue with local provisioner for example.

"proxmox_virtual_environment_vm" "download" {
  name              = var.vm_name.download
  description       = var.vm_template_desc.download
  node_name         = var.node
  vm_id             = var.vmid.download

  clone {
    datastore_id    = var.vm_datastore_id
    vm_id           = 250
  }

  agent {
    enabled         = var.vm_agent
  }

  cpu {
    cores           = var.vm_cores.download
    sockets         = var.vm_sockets
    type            = var.vm_cpu
  }

  memory {
    dedicated       = var.vm_memory.download
  }

  startup {
    order           = "2"
    up_delay        = "60"
    down_delay      = "180"
  }

  bios              = var.vm_bios
  efi_disk {
    datastore_id    = var.vm_datastore_id
    file_format     = var.vm_file_format
    type            = "4m"
  }
  boot_order        = [var.vm_bootdisk]
  scsi_hardware     = var.vm_scsihw

  disk {
    size            = var.vm_disk_size.download
    datastore_id    = var.vm_datastore_id
    file_format     = var.vm_file_format
    interface       = "scsi0"
  }

  network_device {
    model           = "virtio"
    bridge          = "vmbr0"
  }
  initialization {
    datastore_id    = var.vm_datastore_id
    dns {
      server        = var.dns
    }
    ip_config {
      ipv4 {
        address     = var.ip4.download
        gateway     = var.gw4
      }
      ipv6 {
        address     = var.ip6.download
        gateway     = var.gw6
      }
    }
    user_account {
      username = "root"
      keys     = [file(var.ssh_keys["pub"])]
    }
  }

  connection {
  type = "ssh"
  host = "${var.vm_name.download}.localhost"
  user = "root"
  private_key = file(var.ssh_keys["priv"])
  agent = false
  timeout = "5m"
  }

  provisioner "local-exec" {
  #Performs installation of default configuration for VM
  working_dir = var.ansible_working_dir
  command     = "ansible-playbook /srv/ansible/playbooks/deployment/proxmox/download_vm.yml --e 'host=${var.vm_name.download}.localhost'"
  }
}

**Expected behavior**
VM is being deployed without needing a manual reboot.

**Screenshots**

- Single or clustered Proxmox: Single (Proxmox version 8.0.9)
- Provider version (ideally it should be the latest version): 0.38.1
- Terraform version: v1.6.2
- OS (where you run Terraform from): RHEL 9

**Comment by TheFrisianClause** [comment]
Missed the option that there is an 'reboot' parameters

**Comment by otopetrik** [comment]
> **Describe the bug** Strange bug... When deploying a VM with cloud-init, the Terraform job changes the hardware etc. But not the cloud-init. But after guest rebooting the VM via the Proxmox GUI the hostname changed to the one defined and cloud-init has been applied.

It is possible to configure VM using cloud init without rebooting the VM, debian example [here](https://gist.github.com/otopetrik/f6e6ef79636592cab957407da1ac5f7b)

>   3. It is errorless but when Terraform is busy provisioning the VM, it keeps doing it. Until you reboot the VM manually via the Proxmox GUI, then it will continue with local provisioner for example.
> 
> agent { enabled = var.vm_agent }
> 

See qemu guest agent [documentation section](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#qemu-guest-agent). Make sure that `proxmox_virtual_environment_vm` is configured with agent enabled **only if** the agent is installed in the VM and *will be running* (note that the debian example has 'runcmd' to actually run it after installing, package installation makes the agent auto start on boot, but not on installation).

When configured with agent enabled, the provider waits for agent inside VM to run before continuing (e.g. running provisioner). If there is no agent running, that would explain the need to manualy reboot the VM.

> Missed the option that there is an 'reboot' parameters

I would advise against the `reboot` option. The reboot command is sent to the VM just after the VM starts running,
there is no guarantee that all the initialization is done. Discussed [here](https://github.com/bpg/terraform-provider-proxmox/issues/669#issuecomment-1786879029).

**Comment by TendonT52** [comment]
I am facing the same issue.

This is my template to clone 
```
cd /var/lib/vz/template/iso/
wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
apt install libguestfs-tools -y
virt-customize -a noble-server-cloudimg-amd64.img --install qemu-guest-agent
qm create 9999 --memory 2048 --core 2 --name ubuntu-cloud --net0 virtio,bridge=vmbr0
qm importdisk 9999  noble-server-cloudimg-amd64.img local-lvm
qm set 9999 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9999-disk-0
qm set 9999 --ide2 local-lvm:cloudinit
qm set 9999 --boot c --bootdisk scsi0
qm set 9999 --serial0 socket --vga serial0
qm template 9999
```
Template config
<img width="649" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/88754538/4a517514-8cc7-4fb1-9f3d-103b20c3202c">
<img width="586" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/88754538/8346305a-addd-4a63-aeea-5e4b9055802c">
<img width="707" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/88754538/bc2f9aa1-b456-4a83-aa87-d885ec2c212b">

This is my terrafrom
```
resource "proxmox_virtual_environment_vm" "kube-controller" {
  name      = "kube-controller"
  node_name = "pve"
  machine   = "q35"
  bios      = "ovmf"
  reboot    = true

  agent {
    enabled = true
  }

  clone {
    vm_id = "9999"
  }

  operating_system {
    type = "l26"
  }

  cpu {
    cores = 2
    type  = "host"
    numa  = true
  }

  memory {
    dedicated = 4096
  }

  disk {
    size         = "50"
    interface    = "virtio0"
    datastore_id = "local-lvm"
    file_format  = "raw"
    iothread     = true
    ssd          = true
  }

  efi_disk {
    datastore_id = "local-lvm"
    file_format  = "raw"
    type         = "4m"
  }

  network_device {
    bridge = "vmbr0"
    model  = "virtio"
  }

  initialization {
    ip_config {
      ipv4 {
        address = "192.168.0.210/24"
        gateway = "192.168.0.1"
      }
    }
  }
}
```

**Comment by otopetrik** [comment]
Template has cloud-init drive on `ide2` by default, which works for VMs using *bios* boot.

The terraform-cloned VM is configured to boot using *uefi*:
>   bios      = "ovmf"

[Experiment showed](https://github.com/bpg/terraform-provider-proxmox/issues/586#issuecomment-1793602323) that if VM is booted using uefi with the cloud-init drive on `ideX`, the cloud-init drive is not used. Booting using uefi requires cloud init drive on `scsiX` (e.g `initialization.interface` set to `scsi1` or similar).

**Comment by Sparkxxx** [comment]
> Template has cloud-init drive on `ide2` by default, which works for VMs using _bios_ boot.
> 
> The terraform-cloned VM is configured to boot using _uefi_:
> 
> > bios      = "ovmf"
> 
> [Experiment showed](https://github.com/bpg/terraform-provider-proxmox/issues/586#issuecomment-1793602323) that if VM is booted using uefi with the cloud-init drive on `ideX`, the cloud-init drive is not used. Booting using uefi requires cloud init drive on `scsiX` (e.g `initialization.interface` set to `scsi1` or similar).

For me cloudinit works with sata0. Since I use (cloned vm and my desire) scsi_hardware = "virtio-scsi-single" due to the better performance of the disk with iothread = true, I think this is the reason I can't use scsiX with initialization.interface. Tested and it does not work. What scsi_hardware is your machine set to?

**Comment by TendonT52** [comment]
> Template has cloud-init drive on `ide2` by default, which works for VMs using _bios_ boot.
> 
> The terraform-cloned VM is configured to boot using _uefi_:
> 
> > bios      = "ovmf"
> 
> [Experiment showed](https://github.com/bpg/terraform-provider-proxmox/issues/586#issuecomment-1793602323) that if VM is booted using uefi with the cloud-init drive on `ideX`, the cloud-init drive is not used. Booting using uefi requires cloud init drive on `scsiX` (e.g `initialization.interface` set to `scsi1` or similar).

Thank you for the very clear explanation. Now I can solve this. For those who read this later, this is my config that works for me.

`cd /var/lib/vz/template/iso/
wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
apt install libguestfs-tools -y
virt-customize -a noble-server-cloudimg-amd64.img --install qemu-guest-agent
qm create 9999 --memory 2048 --core 2 --name ubuntu-cloud --net0 virtio,bridge=vmbr0
qm importdisk 9999  noble-server-cloudimg-amd64.img local-lvm
qm set 9999 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9999-disk-0
qm set 9999 --scsi1 local-lvm:cloudinit
qm set 9999 --boot c --bootdisk scsi0
qm set 9999 --serial0 socket --vga serial0
qm template 9999`

`resource "proxmox_virtual_environment_vm" "kube-controller" {
  name      = "kube-controller"
  node_name = "pve"
  machine   = "q35"
  bios      = "ovmf"

  agent {
    enabled = true
  }

  clone {
    vm_id = "9999"
  }

  operating_system {
    type = "l26"
  }

  cpu {
    cores = 2
    type  = "host"
    numa  = true
  }

  memory {
    dedicated = 4096
  }

  disk {
    size         = "50"
    interface    = "virtio0"
    datastore_id = "local-lvm"
    file_format  = "raw"
    iothread     = true
    ssd          = true
  }

  efi_disk {
    datastore_id = "local-lvm"
    file_format  = "raw"
    type         = "4m"
  }

  network_device {
    bridge = "vmbr0"
    model  = "virtio"
  }

  initialization {
    interface = "scsi1"
    ip_config {
      ipv4 {
        address = "192.168.0.210/24"
        gateway = "192.168.0.1"
      }
    }
  }
}`



> > Template has cloud-init drive on `ide2` by default, which works for VMs using _bios_ boot.
> > The terraform-cloned VM is configured to boot using _uefi_:
> > > bios      = "ovmf"
> > 
> > 
> > [Experiment showed](https://github.com/bpg/terraform-provider-proxmox/issues/586#issuecomment-1793602323) that if VM is booted using uefi with the cloud-init drive on `ideX`, the cloud-init drive is not used. Booting using uefi requires cloud init drive on `scsiX` (e.g `initialization.interface` set to `scsi1` or similar).
> 
> For me cloudinit works with sata0. Since I use (cloned vm and my desire) scsi_hardware = "virtio-scsi-single" due to the better performance of the disk with iothread = true, I think this is the reason I can't use scsiX with initialization.interface. Tested and it does not work. What scsi_hardware is your machine set to?

I use scsihw: virtio-scsi-pci on the vm.

**Comment by M0NsTeRRR** [comment]
Hello guys,

Cloud init with IDE2 (default) is working on my side, you can find the attached apply i've posted in an other issue https://github.com/bpg/terraform-provider-proxmox/issues/734#issuecomment-1826280294
You can find my terraform config [here](https://github.com/M0NsTeRRR/homelabv3-infra/blob/main/terraform/modules/vm/main.tf) (I use terragrunt to boostrap everything)

Tested with Proxmox Virtual Environment 8.0.9, Terraform v1.6.4 and Ubuntu 22.04.3.

I'm creating a template with packer, with some ansible scripts (in the same repo), at the end I reset cloud init instance with `cloud-init clean --seed --machine-id` and I deploy this template with Terraform.

Note : I use cloud init file
```
  initialization {
    interface            = "ide2"
    network_data_file_id = proxmox_virtual_environment_file.cloud_network_config.id
    user_data_file_id    = proxmox_virtual_environment_file.cloud_user_config.id
    meta_data_file_id    = proxmox_virtual_environment_file.cloud_meta_config.id
  }
```

**Comment by bpg** [comment]
I'm going to close this issue as the problem seems to be resolved, and no followup is needed.
We'll work on [adding HOW-TOs](https://github.com/bpg/terraform-provider-proxmox/issues/758) for various cloud-init use cases.
