### ISSUE TITLE
API Endpoint has wrong default values

### ISSUE THREAD

**Issue by bitchecker** [bpg/terraform-provider-proxmox#795]
**Describe the bug**
Hi,
I configured the provider section in order to have a dynamic configuration (IP/password/port) and I'm setting these variables via tfvars file.

```hcl
provider "proxmox" {
  endpoint = "https://${var.pm_host}:${var.pm_webport}/"
  username = "${var.pm_user}@pam"
  password = var.pm_password
  insecure = true
  tmp_dir  = "${path.module}"
  ssh {
    agent = true
      dynamic "node" {
      for_each = var.pm_nodes
      content {
        name    = node.value.name
        address = node.value.address
        port    = node.value.port
      }
    }
  }
}
```

But if the endpoint is not on the standard port (normal if you're behind Nat/firewalls) the call that the provider is trying to perform is referring to the default 8006 port.

```bash
Error: failed to get nodes: failed to authenticate HTTP GET request (path: nodes) - Reason: failed to authenticate: failed to retrieve authentication response: Post "https://XXX:8006/api2/json/access/ticket": dial tcp XXXXX:8006: connect: connection timed out
```
Of course, is not the classic port 8006, but another one.

**To Reproduce**
Try to change the ENDPOINT in order to use another port instead of classic 8006 and try to execute code.

**Expected behavior**
Normal connection like classic 8006 port is used

**Additional context**
- Single or clustered Proxmox: single
- Provider version (ideally it should be the latest version): latest
- Terraform version: `v1.6.5`
- OS (where you run Terraform from): `Fedora 39`

**Comment by bpg** [comment]
Hi @bitchecker! 
That's interesting 🤔 The port `8006` [is not hardcoded anywhere](https://github.com/search?q=repo%3Abpg%2Fterraform-provider-proxmox+8006&type=code) in the provider's code.
There is no any URL building magic in there, the HTTP client [initializes](https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/api/client.go#L92) from the provided `endpoint` argument, just truncating path from it.    

So I really have no much ideas where it is coming from. Could you doublecheck that `var.pm_webport` value is not 8006?

Another possibility could be a redirect from your firewall / proxmox. If you call `curl -v https://<your server>:<your non standard port>/` from your workstation, what does it print?

Does your firewall do SSL termination? If it does, then it probably sends the API traffic as HTTP (not HTTPs) to the Proxmox host behind, then Proxmox replies with 301 redirect which will have a default 8006 port, and that goes to the client which can't connect to 8006... 

Just a simple example of that from my lab (note http vs https):
```
❯ curl -v http://pve.home.lab:8006/api2/json/
*   Trying 192.168.3.40:8006...
* Connected to pve.home.lab (192.168.3.40) port 8006 (#0)
> GET /api2/json/ HTTP/1.1
> Host: pve.home.lab:8006
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Cache-Control: max-age=0
< Connection: Keep-Alive
< Date: Wed, 13 Dec 2023 02:24:35 GMT
< Pragma: no-cache
< Location: https://pve.home.lab:8006/api2/json/
< Server: pve-api-daemon/3.0
< Expires: Wed, 13 Dec 2023 02:24:35 GMT
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0

**Comment by bitchecker** [comment]
Hi @bpg,
thanks for your reply!

After your confirmation about “no hard-coded values”, I checked again on my code and I found that I wasn't pass the variable configured on tfvars file to my module, so it was running using default.

Thanks again.

**Comment by bpg** [comment]
Ah, ok! No worries, that happens to all of us :)
I'm closing the ticket then.
