### ISSUE TITLE
Support for decimal LXC disk sizes

### ISSUE THREAD

**Issue by romner-set** [bpg/terraform-provider-proxmox#810]
**Is your feature request related to a problem? Please describe.**
Currently, a container's disk size can only be a whole number of GB, which can be pretty wasteful with small Alpine LXCs that need <256MB of disk space. Proxmox itself allows using decimals through the Web UI (e.g. 0.5 for 512MB, 0.25 for 256MB).

**Describe the solution you'd like**
Adding support for decimal disk sizes.

**Describe alternatives you've considered**
Wasting a few GB of space on my drives, or using thin/sparse storage.

**Additional context**
N/A

**Comment by bpg** [comment]
Duplicated by #1511
