### ISSUE TITLE
Cloning a VM do not set the SMBIOS settings

### ISSUE THREAD

**Issue by olemathias** [bpg/terraform-provider-proxmox#813]
**Describe the bug**
When cloing a VM and setting SMBIOS settings like `serial`, the created VM are created without any of the SMBIOS settings. Triggering new update by changing the serial after the first apply works.

**To Reproduce**
```hcl
resource "proxmox_virtual_environment_vm" "test_vm" {
  name      = "my-test-vm"
  node_name = "pve1"
  started   = false
  on_boot   = false

  clone {
    vm_id        = 9201
    node_name    = "pve1"
    datastore_id = "ceph1"
  }

  cpu {
    cores = 4
  }

  memory {
    dedicated = 1024
  }

  disk {
    datastore_id = "ceph1"
    interface    = "scsi0"
    size         = "10"
    iothread     = true
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 101
  }

  smbios {
    serial = "my-custom-serial"
  }

  lifecycle {
    ignore_changes = [
      node_name,
      started
    ]
  }
}
```

**Expected behavior**
Serial under smbios settings is set to "my-custom-serial"

**Screenshots**
<img width="276" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/891048/752da449-f87c-4aa4-895c-31b6ff27bec7">
smbios->serial is showing in the plan

**Additional context**

- Single or clustered Proxmox: Cluster
- Provider version (ideally it should be the latest version): latest (0.40.0)
- Terraform version: v1.6.5
- OS (where you run Terraform from): Debian 12
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by scibi** [comment]
I have the same issue. I'm not a Go programmer by I think that's because in `vmCreateCustom()` smbios is set but in `vmCreateClone()` it's not updated. It would be useful to have this fixed to use smbios serial numer as a datasource for cloud-init to set hostname.

**Comment by bpg** [comment]
Thanks @scibi, that's a really good catch!

**Comment by bpg** [comment]
@all-contributors
please add @olemathias for bug
please add @scibi for bug, ideas

**Comment by bpg** [comment]
@al-contributors please add @scibi for bug, ideas
