### ISSUE TITLE
Allow Multiple DNS Servers for proxmox_virtual_environment_container and in vm template

### ISSUE THREAD

**Issue by mkopnsrc** [bpg/terraform-provider-proxmox#816]
**Is your feature request related to a problem? Please describe.**
Currently based on documentation and example, it only shows and supports single DNS server IP in the proxmox_virtual_environment_container dns -> server block. Normally everyone uses internal DNS servers rather then public DNS servers shown in example. Multiple DNS servers allows containers and VMs for failover DNS Resolve.
![image](https://github.com/bpg/terraform-provider-proxmox/assets/2036998/78a7f18d-aeb2-4bbb-b183-d84f84bd7700)

**Describe the solution you'd like**
Please add the feature to allow multiple DNS servers in the server block as shown below.
![image](https://github.com/bpg/terraform-provider-proxmox/assets/2036998/6c29053c-7272-43f8-ab29-f87e3b40915e)

**Describe alternatives you've considered**
Alternatively, when deploying container when no DNS server block provided it should automatically inherit the PVE Node Host DNS servers into container which is by default it's built-on feature within Proxmox VE. 

**Additional context**
None

**Comment by mkopnsrc** [comment]
Update on this issue, 

It seems that you can have multiple DNS servers in a single string format with space in between, which it seem to worked for me. However, for the proper formatting of the values, it should be in object format.

`dns {
            domain = "home.lan"
            server = "10.100.1.11 10.100.1.12"
}
`

Proxmox Release = 8.1
Proxmox Version = 8.1.3
Terraform Version = 1.6.6
Terraform Module = bpg/proxmox v0.40.0

**Comment by bpg** [comment]
Hi @mkopnsrc! 👋🏼 

I think this is already supported, albeit not documented.

PVE does not provide an option to specify a list of DNS servers as separate items neither in UI, nor in APIs:

<img width="814" alt="Screenshot 2023-12-17 at 9 27 38 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/c70702e0-ff57-43cd-afe4-f65716904ef9">

<img width="1716" alt="Screenshot 2023-12-17 at 9 04 02 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/3235b304-7e92-4bce-9889-8c0a6b192760">


But we can use a space-separated lists of IPs instead (tested with ubuntu cloud image):

```hcl
 dns {
    domain = "example.com"
    server = "192.168.3.1 192.168.1.1"
  }
```

<img width="553" alt="Screenshot 2023-12-17 at 9 25 33 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/26a8cb43-175a-4c76-ac88-6bebe7951559">

Then, on the VM itself:
```
ubuntu@test:~$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (eth0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.3.1
       DNS Servers: 192.168.3.1 182.168.1.1
        DNS Domain: example.com
```

**Comment by mkopnsrc** [comment]
I appreciate your quick response, yes you're correct. Would be still possible to support the object based at the  module level and when executing on PVE side, it would convert it to string format ?

The object level formatting on code would help admins to spot multiple entries easier  and enables for comment for each DNS entries. Ex:

![image](https://github.com/bpg/terraform-provider-proxmox/assets/2036998/5f115c18-45ee-4880-a0dc-551d91bd420a)

**Comment by bpg** [comment]
That would break backward compatibility with existing deployments. We could probably add a new attribute `servers` there, keeping the old `server` for compatibility.

**Comment by bpg** [comment]
@all-contributors please add @mkopnsrc for financial

**Comment by mkopnsrc** [comment]
Thank you @bpg for your support.
