### ISSUE TITLE
Creating multiple VMs in a proxmox cluster, but the first one never boots

### ISSUE THREAD

**Issue by Neels-v-Wyk** [bpg/terraform-provider-proxmox#831]
**Describe the bug**
I am creating three identical VMs accross three proxmox nodes which are configured the same, but only vm2 and vm3 boot, vm1 doesn't start and complains about not having a boot device
 
**To Reproduce**
Apply the following. My proxmox cluster nodes are labeled `server-01, server-02, server-03` for context. If this is too long please say so and I will submit it as a gist

```hcl
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.41.0"
    }
  }
}

provider "proxmox" {
  endpoint = "https://${var.proxmox_ve_node_1_ip}:8006/api2/json"

  # The Proxmox VE API doesn't allow some operations when using token authentication
  # so we'll have to use root username/password authentication
  username = var.proxmox_ve_username
  password = var.proxmox_ve_password
  insecure = true

  ssh {
    agent = true

    node {
      name    = var.proxmox_ve_node_1_name
      address = var.proxmox_ve_node_1_ip
    }
    node {
      name    = var.proxmox_ve_node_2_name
      address = var.proxmox_ve_node_2_ip
    }
    node {
      name    = var.proxmox_ve_node_3_name
      address = var.proxmox_ve_node_3_ip
    }
  }
}

resource "proxmox_virtual_environment_vm" "k8s-node" {

  count       = 3
  name        = "k8s-node-${count.index + 1}"
  description = "Kubernetes Node Managed by Terraform"
  tags        = ["terraform", "ubuntu", "kubernetes"]

  node_name = "server-0${count.index + 1}"
  vm_id     = count.index + 501

  agent {
    enabled = true
  }

  cpu {
    cores   = 2
    sockets = 1
    type    = "host"
  }

  startup {
    order      = count.index + 10
    up_delay   = "30"
    down_delay = "60"
  }

  disk {
    datastore_id = "server-zfs-storage"
    interface    = "scsi0"
    size         = "50"
    file_id      = proxmox_virtual_environment_file.ubuntu_cloud_image[count.index].id
  }

  boot_order = ["scsi0"]

  initialization {

    ip_config {
      ipv4 {
        address = "192.168.0.5${count.index + 1}/24"
        gateway = "192.168.0.1"
      }
    }

    user_account {
      keys     = [var.ssh_public_key]
      password = random_password.ubuntu_vm_password.result
      username = "ubuntu"
    }

    user_data_file_id = proxmox_virtual_environment_file.cloud_config[count.index].id
  }


  network_device {
    bridge = "vmbr0"
  }

  operating_system {
    type = "l26"
  }

  tpm_state {
    datastore_id = "server-zfs-storage"
  }

  serial_device {}
}

resource "random_password" "ubuntu_vm_password" {
  length           = 16
  override_special = "_%@"
  special          = true
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  count        = 3
  content_type = "snippets"
  datastore_id = "nas-nfs"
  node_name    = "server-0${count.index + 1}"

  source_raw {
    data = <<EOF
#cloud-config
hostname: k8s-node-${count.index + 1}

users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - ${trimspace(var.ssh_public_key)}
    sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/sudoers.d/cloud-init
    content: |
      Defaults !requiretty

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

EOF
    # Prevent files overwriting eachother by giving them unique names with the count.index
    file_name = "ubuntu-terraform-cloud-config${count.index}.yaml"
  }
}

resource "proxmox_virtual_environment_file" "ubuntu_cloud_image" {
  count        = 3
  content_type = "iso"
  datastore_id = "nas-nfs"
  node_name    = "server-0${count.index + 1}"

  source_file {
    path = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    file_name = "noble-server-cloudimg-amd64-${count.index}.img"
  }
}
```

**Expected behavior**
All three VMs start up the same way.

**Additional context**
A screenshot of what I get when opening a console. The other VMs show me the normal linux login screen and I can ssh into them
<img width="850" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/48153065/1bb3e8e9-a5a4-4717-b544-bf4722308cc8">

Here is a `qm config` output of the first and second vm for comparison, one works one doesn't but there seems to be no clear difference

```
broken:
root@server-01:~# qm config 501
acpi: 1
agent: enabled=1,fstrim_cloned_disks=0,type=virtio
arch: x86_64
balloon: 0
bios: seabios
boot: order=scsi0
cicustom: user=nas-nfs:snippets/ubuntu-terraform-cloud-config0.yaml
cipassword: **********
ciuser: ubuntu
cores: 2
cpu: cputype=host
cpuunits: 1024
description: Kubernetes Node Managed by Terraform
ide2: local-lvm:vm-501-cloudinit,media=cdrom
ipconfig0: gw=192.168.0.1,ip=192.168.0.51/24
keyboard: en-us
memory: 512
meta: creation-qemu=8.1.2,ctime=1703261997
name: k8s-node-1
net0: virtio=BC:24:11:43:13:F5,bridge=vmbr0,firewall=0
numa: 0
onboot: 1
ostype: l26
scsi0: server-zfs-storage:vm-501-disk-1,cache=none,size=50G
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=62ae1909-e02f-46e8-90e8-6482a4d8e83e
sockets: 1
sshkeys: ssh-rsa%20AAAAsnipped_for_readability_wEOl
startup: order=10,up=30,down=60
tablet: 1
tags: kubernetes;terraform;ubuntu
template: 0
tpmstate0: server-zfs-storage:vm-501-disk-0,size=4M,version=v2.0
vga: memory=16,type=std
vmgenid: 11a9d3b9-ab6e-4744-9b9e-b5bdb3fb8580

working:
root@server-02:~# qm config 502
acpi: 1
agent: enabled=1,fstrim_cloned_disks=0,type=virtio
arch: x86_64
balloon: 0
bios: seabios
boot: order=scsi0
cicustom: user=nas-nfs:snippets/ubuntu-terraform-cloud-config1.yaml
cipassword: **********
ciuser: ubuntu
cores: 2
cpu: cputype=host
cpuunits: 1024
description: Kubernetes Node Managed by Terraform
ide2: local-lvm:vm-502-cloudinit,media=cdrom
ipconfig0: gw=192.168.0.1,ip=192.168.0.52/24
keyboard: en-us
memory: 512
meta: creation-qemu=8.1.2,ctime=1703261997
name: k8s-node-2
net0: virtio=BC:24:11:2D:66:58,bridge=vmbr0,firewall=0
numa: 0
onboot: 1
ostype: l26
scsi0: server-zfs-storage:vm-502-disk-1,cache=none,size=50G
scsihw: virtio-scsi-pci
serial0: socket
smbios1: uuid=b8dd1c36-6e21-4936-aa8c-b1055cff49f0
sockets: 1
sshkeys: ssh-rsa%20AAAAsnipped_for_readabilityAXwEOl
startup: order=11,up=30,down=60
tablet: 1
tags: kubernetes;terraform;ubuntu
template: 0
tpmstate0: server-zfs-storage:vm-502-disk-0,size=4M,version=v2.0
vga: memory=16,type=std
vmgenid: 2893919e-3ce5-45ef-86a1-487952f17119
```

- Single or clustered Proxmox:
Clustered
- Provider version (ideally it should be the latest version):
Latest (v0.41.0)
- Terraform version:
Latest (v1.6.6)
- OS (where you run Terraform from):
MacOS Ventura 13.6.1
- Debug logs (`TF_LOG=DEBUG terraform apply`):
I think due to the inclusion of a image to be uploaded it outputs it as bytes in the debug log causing it to be comically massive (8GB or so), here's the top and bottom parts, I canceled the apply after roughly 40 minutes in, vm2 and vm3 came up roughly at the same time a few minutes in, vm1 never does. The [gist](https://gist.github.com/Neels-v-Wyk/838c3ba3135a6e8b7f11d11bee9dd2f7) of that is here. It also looks like the password is put here as plaintext, I'm not sure if that is intentional.

**Comment by bpg** [comment]
Thanks for the report @Neels-v-Wyk! Definitely, there is something interesting going on, I haven't seen such behaviour before. Would you mind provide some extra details?
 
If you deploy just one VM, does it work?
Is it always failing on `server-01`? Could you try reverse order of the servers?
Is there any errors in tasks lists on the cluster?

**Comment by Neels-v-Wyk** [comment]
> If you deploy just one VM, does it work?
Yup! Setting the `count` to `1` results in one working vm on server-01. Setting it to 2 results in one broken one on server-01 and a working one on server-02. Interestingly enough, setting the servers to be created by trying to reverse the count `3 - count.index` yields the same result, I think probably because terraform doesn't creating things in order but in parrallel, so this would make no difference

Explicitly excluding server-01 form being selected for creating VMs and only creating them on 02 and 03, both still get created correctly :(

...

Alright, I tried a few more things and ended up reinstalling proxmox on server-01 and re joining it to the cluster. Everything is working now, consistently. I wish I had more info on why this worked when creating 1 VM but not multiple. I'll close this issue for now and reopen it if it happens again but it seems like I must have messed something up myself



> Is there any errors in tasks lists on the cluster?
No task errors, no errors in the logs either. It seems that the creation process is working, I'm assuming this is something to do with how the machine starts

**Comment by Neels-v-Wyk** [comment]
Heck, the issue is back. I can't `terraform apply -destroy` and then `terraform apply` again without making it happen. Something that does seem to help though is rebooting the first server, then it works for one instance of `terraform apply` and a subsequent `destroy`

**Comment by Neels-v-Wyk** [comment]
That is no longer the case ^, I am consistently getting the same issue again :(

**Comment by Neels-v-Wyk** [comment]
This seems to be a ZFS related issue. I deleted my ZFS pool and recreated another one, and then nothing started coming up. I deleted my ZFS pool again and extended local-lvm to make use of the freed up space, and now everything works.

I also attempted to use a different proxmox node as the entrypoint but that still resulted on the vm on server-01 not having a boot disk

**Comment by bpg** [comment]
Hi @Neels-v-Wyk!

Was you able to sort things out? Do you need any support from the provider's side?
From what I'm reading here, there seems to be an obscure issue with the Proxmox ZFS storage that prevents VM from a normal boot.

Realistically, I don't think provider / terraform can do anything about it, except maybe set [parallelism](https://developer.hashicorp.com/terraform/cli/commands/apply#parallelism-n) to 1, so only one VM is provisioned at a time?

**Comment by Neels-v-Wyk** [comment]
Interesting! I don't know if that will solve the problem but I think it's a step in the right direction. I'll have to try this later, I'll get back to you if there's any new results
