### ISSUE TITLE
ERROR: create vm  with disk in storage LVM type

### ISSUE THREAD

**Issue by sor88** [bpg/terraform-provider-proxmox#845]
I can't create vm with disk in storage LVM type. But I create vm with disk in storage type qcow2(local). VM is create succesfully. And after i change storage type im my terraform code. Disk moved in storage type LVM.proxmox_virtual_environment_vm.k8s1: Creating...
╷
│ Error: error waiting for VM creation: task "UPID:**********:" failed to complete with exit code: unable to create VM 233 - unsupported format 'qcow2' at /usr/share/perl5/PVE/Storage/LVMPlugin.pm line 366.
│ 
│   with proxmox_virtual_environment_vm.k8s1,
│   on k8s.tf line 1, in resource "proxmox_virtual_environment_vm" "k8s1":
│    1: resource "proxmox_virtual_environment_vm" "k8s1" {
│ 

 terraform apply
Acquiring state lock. This may take a few moments...
data.proxmox_virtual_environment_datastores.first_node: Reading...
proxmox_virtual_environment_file.ubuntu_cloud_image: Refreshing state... [id=local:iso/ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img]
proxmox_virtual_environment_file.talos_image: Refreshing state... [id=local:iso/metal-amd64.iso]
proxmox_virtual_environment_vm.vm_11: Refreshing state... [id=9001]
data.proxmox_virtual_environment_datastores.first_node: Read complete after 0s [id=pve01_datastores]
proxmox_virtual_environment_vm.k8s1: Refreshing state... [id=233]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.k8s1 will be updated in-place
  ~ resource "proxmox_virtual_environment_vm" "k8s1" {
        id                      = "233"
        name                    = "k8s1"
        tags                    = [
            "k8s-master",
            "talos",
            "terraform",
        ]
        # (26 unchanged attributes hidden)

      ~ disk {
          ~ datastore_id      = "local" -> "def2"
            # (8 unchanged attributes hidden)
        }

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_vm.k8s1: Modifying... [id=233]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 10s elapsed]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 20s elapsed]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 30s elapsed]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 40s elapsed]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 50s elapsed]
proxmox_virtual_environment_vm.k8s1: Still modifying... [id=233, 1m0s elapsed]
proxmox_virtual_environment_vm.k8s1: Modifications complete after 1m7s [id=233]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

datastore_lvm = "def2"

**Comment by bpg** [comment]
Hi @sor88! 👋🏼 

Sorry, it is really hard to read your report 🤔 

Could you please follow the [bug template](https://github.com/bpg/terraform-provider-proxmox/issues/new?assignees=&labels=%F0%9F%90%9B+bug&projects=&template=bug_report.md&title=) when opening a ticket, and also use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when posting snippets of your config / logs?

That would greatly help us to understand your problem, and provide you with an advise or a fix. 

Thanks!

**Comment by Qarasique** [comment]
@bpg Also have same "problem" after clone cloud-init capable template. Seems to provider ignore/skip parameters on disk directive. Only resize disk from template
![image](https://github.com/bpg/terraform-provider-proxmox/assets/18091423/21d84e71-cc7f-454d-a0c2-e5d6416212f3)
![image](https://github.com/bpg/terraform-provider-proxmox/assets/18091423/3ad9bc4f-41f5-4dc0-999c-5b76b257eb61)

**Comment by bpg** [comment]
@Qarasique I think your comment is more related to #873 or #360.

But I have troubles deciphering what this issue is about. The original poster doesn't seem to be interested in this ticket anymore, so I'm going to close it.
