### ISSUE TITLE
Add `virtual_environment_token`

### ISSUE THREAD

**Issue by otopetrik** [bpg/terraform-provider-proxmox#853]
**Is your feature request related to a problem? Please describe.**
After the initial provider configuration, additional users and roles can be configured using the provider. Only token creation is missing.

Using token resource with `local_file` it would be possible to easily (re)configure the provider in sibling projects with limited permissions, without creating additional PVE or PAM users.

**Describe the solution you'd like**
Add resource `virtual_environment_token` for [this API](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/access/users/{userid}/token/{tokenid}).
It should support acl configuration, like the `virtual_environment_user` resource.

As the token value is not readable, the resource should not allow import.

**Comment by bpg** [comment]
Duplicates #740
