### ISSUE TITLE
Ability to exclude disk from replication - replicate attribute

### ISSUE THREAD

**Issue by Dr-Shadow** [bpg/terraform-provider-proxmox#857]
Hello, I'm currently in the progress of migrating my project from Telmate provider.

I don't find this attribute in the disk block :

![image](https://github.com/bpg/terraform-provider-proxmox/assets/5308086/fb7ca062-c0bb-4376-b855-b83c01b8ba9c)

Should be equivalent to ticking this checkbox : 

![image](https://github.com/bpg/terraform-provider-proxmox/assets/5308086/0e21ecd8-9d0d-4e4d-a1f1-a74d8b862507)

Unless I'm missing something ?

Thanks in advance

**Comment by bpg** [comment]
Hi @Dr-Shadow 👋🏼

You're right it is not supported in the current version.
