### ISSUE TITLE
docs for proxmox_virtual_environment_cluster_firewall_security_group in the tf registy

### ISSUE THREAD

**Issue by EugenMayer** [bpg/terraform-provider-proxmox#859]
https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_firewall_rules does not show any docs for `proxmox_virtual_environment_cluster_firewall_security_group` - i assume it has just been forgotten, right?

**Comment by bpg** [comment]
Hi @EugenMayer, isn't it this one:
https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_cluster_firewall_security_group ?

**Comment by EugenMayer** [comment]
Odd! Thanks for following up.

Interesting, when going on https://registry.terraform.io/providers/bpg/proxmox/latest/docs and searching for "sec" or "group" - you wont find anything.
