### ISSUE TITLE
.bz2 archives for `proxmox_virtual_environment_download_file`

### ISSUE THREAD

**Issue by benbouillet** [bpg/terraform-provider-proxmox#860]
**Is your feature request related to a problem? Please describe.**
Looking for a way to manage .bz2 archives of ISOs via the `proxmox_virtual_environment_download_file`, eg. all OPNsense images are compressed in .bz2 on their FTP mirrors (for example, [this mirror](https://www.mirrorservice.org/sites/opnsense.org/releases/mirror/)).

Unfortunately, the `bz2` is not an option for [`decompression_algorithm`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_download_file#decompression_algorithm) as of now.

When setting `bz2` for `decompression_algorithm`:
```
Attribute decompression_algorithm value must be one of: ["gz" "lzo" "zst"], got: "bz2"
```

When trying `gz`:
```
Could not DownloadFileByURL: `opnsense.img`, unexpected error: error download file to datastore <REDACTED>: failed waiting for url download - task
"UPID:pve:00353CA3:09FDB8F5:6598858D:download:opnsense.img:<REDACTED>@pam:" failed to complete with exit code: command 'zcat
/var/lib/pve/<REDACTED>/template/iso/opnsense.img.tmp_dwnl.3488931' failed: exit code 1
```

When trying `lzo`:
```
Could not DownloadFileByURL: `opnsense.img`, unexpected error: error download file to datastore <REDACTED>: failed waiting for url download - task
"UPID:pve:00352701:09F9C4FD:65987B6E:download:opnsense.img:<REDACTED>@pam:" failed to complete with exit code: command 'lzop -d -c
/var/lib/pve/<REDACTED>/template/iso/opnsense.img.tmp_dwnl.3483393' failed: exit code 1
```

When trying `zst`:
```
Could not DownloadFileByURL: `opnsense.img`, unexpected error: error download file to datastore <REDACTED>: failed waiting for url download - task
"UPID:pve:00352701:09F9C4FD:65987B6E:download:opnsense.img:<REDACTED>@pam:" failed to complete with exit code: command 'zstd -q -d -c
/var/lib/pve/<REDACTED>/template/iso/opnsense.img.tmp_dwnl.3483393' failed: exit code 1
```

**Describe the solution you'd like**
Add the `bz2` support in the available decompression algorithms.

**Describe alternatives you've considered**
Keeping a local decompressed version of the `.img` file and uploading it to the PVE instance with `proxmox_virtual_environment_file`. Usable but not very lean and simple :)

Thank you for all the work !

**Comment by bpg** [comment]
Hi @benbouillet! 👋🏼 

Unfortunately, this isn't within the provider's control. Decompression needs to happen server-side (on a Proxmox node), and we can only pass algorithms supported by Proxmox for this API, which are: "gz," "lzo," "zst."

For the reference, this is how it works through the UI:
<img width="773" alt="Screenshot 2024-01-05 at 8 29 36 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/dba37780-c09b-4453-8469-eb72b1b059bf">

**Comment by benbouillet** [comment]
Hey there, thank you for your quick answer, learning everyday :) I'll raise a request to Proxmox then!
