### ISSUE TITLE
126 vs l16 for operating_system  - lowercase L vs number 1

### ISSUE THREAD

**Issue by TheBelgarion** [bpg/terraform-provider-proxmox#863]
Error: expected type to be one of ["l24" "l26" "other" "solaris" "w2k" "w2k3" "w2k8" "win7" "win8" "win10" "win11" "wvista" "wxp"], got 126
│
│   with proxmox_virtual_environment_vm.test,
│   on test.tf line 64, in resource "proxmox_virtual_environment_vm" "test":
│   64:     type = "126"

It took me quite some time to figure out its not "126" but "l26"

![l16](https://github.com/bpg/terraform-provider-proxmox/assets/7360346/1c0bd0fb-0757-4489-81cb-cce53e271a92)

on my putty terminal is was not as visible as it is here (guess should select another font anyway)

maybe is should be upper case  L26 and WIN7 ... and do an internal conversion lowertoupper to be backward compatible with old terraform?

**Comment by bpg** [comment]
Thanks, seems reasonable :)

**Comment by TheBelgarion** [comment]
i just saw that the values are from proxmox QM so not sure if that will accept uppercase there as well - if not maybe just a notice in the docu section ;-) so noone else falls for the same trap :-)
