### ISSUE TITLE
Unable to set hostname for newly created vms

### ISSUE THREAD

**Issue by verb5** [bpg/terraform-provider-proxmox#866]
**Unable to set hostname for newly created vm**
I expect to set the appropriate hostname via bpg provider.
Unfortunately hostname is always set to localhost. Only way to change hostname is via cloud-init if i specify preserve_hostname: false and hostname: my_vm_name  ,but i need to set the hostname via terraform.

**To Reproduce**

1. Create a resource : 
```
resource "proxmox_virtual_environment_vm" "rocky" {
  name        = "Rocky01"
  ...
}
```
2. create cloud-init config
3. bring vm up

**Additional context**

- Single node Proxmox: Virtual Environment 8.1.3
- Provider version : latest
- Terraform version: v1.6.6
- OS (where you run Terraform from): linux
- Test has been done with debian and rocky vms on both hostname was set as localhost

**Comment by verb5** [comment]
I think this issue is not related to the provider. Just noticed that vm that hasn't been provisioned with this provider has same behavior when hostname get changed from web-ui Options>Name the hostname into the vm doesn't change.

**Comment by bpg** [comment]
That's right, for VMs the host name should be configured from withing the OS, and cloud-init is the (only) way to do that.
You can have a cloud-init configuration via an [inline snippet file resource](https://github.com/bpg/terraform-provider-proxmox/blob/main/example/resource_virtual_environment_file.tf#L53-L65), and have the host name there parametrized via a terraform var.
