### ISSUE TITLE
Disk resize fails with timeout when creating vms in a loop

### ISSUE THREAD

**Issue by 10x4reply** [bpg/terraform-provider-proxmox#868]
**Brief explanation**
I create 4 VMs with could-init ubuntu image **with a loop**. The creation of the vms is successful, but the next step to resize the vms disks ends up in got timeout. The provider exits with apply complete resources added 0 errors. 
If I create this vms **without a loop there is no issue.**

** Observations **
TEST 1
Creating 4 vms without a loop parallelism=4 
1. Creating:  vms are created almost instantly => OK
2. Disc resize : I observe in the PX web ui tasks **only one task is started for the disk resize** for one of the vms, **after it completes OK the rest 3 tasks for disk resize start** and complete almost instantly with OK
3. I check in the web ui the 4 vms configs are exactly as the should OK

TEST 2
Creating 4 vms with a loop parallelism=4 
1. Creating tasks:  vms are created almost instantly => OK
2.Disk resizing tasks:  4 resize tasks start instantly vs no loop TEST 1 point 2
3.  sometimes only 1 or 2 vm resize task finish OK, but most of the time the 4 vms disk resize got this:
(example from PX web UI just for vm 701 for the other is identical)
TASK ERROR: command '/usr/bin/qemu-img resize -f qcow2 /tank/vm_disks/images/701/vm-701-disk-1.qcow2 17179869184' failed: got timeout
4. terraform exits with no errors
5. I check in the web ui to see the vms configs(disk size), only the passed disk resize tasks (if any) for the particular vm(s) is OK

TEST 3
Creating 4 vms with a loop parallelism=1 
1. Creating tasks:  vms are created OK
2. Disk resizing tasks: most of the time 3 vms disk resize task got OK , but least 1 vm again fails with this error in the web UI task log:
TASK ERROR: command '/usr/bin/qemu-img resize -f qcow2 ..... failed: got timeout

- Single Proxmox: pve 8.1.3 32 (enough pve resources for vms)
- zfs pool mirror-0 (2x ssd Samsung 870 QVO 1TB) health OK , disk no bad sectors
- Provider version : 0.43.0
- Terraform version: 1.6.6
- OS (where you run Terraform from): macOS Sonoma 14.2.1
- Debug logs (`TF_LOG=DEBUG terraform apply`): NO errors from provider, apply completes successfully

**Screenshots with loop**
![Screenshot 2024-01-08 at 10 46 21](https://github.com/bpg/terraform-provider-proxmox/assets/155946145/1ad6db1f-2375-4d12-b97f-cca3b5550379)

I have used this configuration. 
1. NO loop copy/paste 4 time (with changed, resource name, vm_id, ip .. etc)
2. with loop I change with vars but same properties
```hcl

resource "proxmox_virtual_environment_vm" "ubuntu_cloudinit_vms_1" {
  vm_id = 700

  name        = "vm1"
  description = "some-vm1"

  node_name = "pve"

  agent {
    enabled = true
  }
  on_boot = true
  started = false
  startup {
    order      = "3"
    up_delay   = "60"
    down_delay = "60"
  }

  disk {
    interface = "scsi0"
    file_id   = "isos:iso/ubuntu-cloud-init-2022.4-minimal-amd64.img"
    discard   = "on"
    size      = 16
  }
  disk {
    datastore_id = "vm_disks"
    interface    = "scsi1"
    file_format  = "qcow2"
    discard      = "on"
    size         = 5
  }
  initialization {
    dns {
      servers = ["192.168.88.1"]
    }
    ip_config {
      ipv4 {
        address = "10.42.0.21/24"
        gateway = "10.42.0.1"
      }
    }
    datastore_id = "vm_disks"

    user_account {
      password = "test123"
      username = "test"
    }

  }

  cpu {
    architecture = "x86_64"
    cores        = 4
    type         = "Westmere-IBRS"
  }
  memory {
    dedicated = 2048
  }
  network_device {
    bridge  = "vmbr1"
    vlan_id = 20
  }

  operating_system {
    type = "l26"
  }

  serial_device {}
}


```

Lastly I want to thank to @bpg and all contributors for the great effort you put here :)

**Comment by bpg** [comment]
Interesting,... there was another similar use case: https://github.com/bpg/terraform-provider-proxmox/issues/831, also on ZFS. Curious if we're hitting some IO limitation there. 
Could you also try with `virtio` [interface](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#interface) for your disks? It supposed to have [better performance](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#_emulated_devices_and_paravirtualized_devices) that scsi.

**Comment by 10x4reply** [comment]
Thank you for the fast reply :)))

**My mistake it wasn't from the loop nor from virtio interface, or parallelism.**

**From provider documentation:**
initialization - (Optional) The cloud-init configuration.
datastore_id - (Optional) The identifier for the datastore to create the cloud-init disk in (defaults to local-lvm).
 I have set the **datastore_id** I thought it will result the cloud init disk in to **vm_disk**
 initialization {
......
    datastore_id = "vm_disks"
....
}
that's why I omitted **datastore_id** in the **disk section** thinking that it will be placed into vm_disk but defaults to **local-lvm(LVM-thin)** and placed there the disks in raw format
  disk {
    interface = "scsi0"
    file_id   = "isos:iso/ubuntu-cloud-init-2022.4-minimal-amd64.img"
    discard   = "on"
    size      = 16
  }


**After correcting my self** 
I tried with datastore_id = "local-lvm" for initialisation and disk.
Both with loop and without loop multiple vms were created and resized, correctly just as they should. (disks are placed in local-lvm(LVM-thin)  :) 

**Next**
I tried with datastore_id = "vm_disks" for initialisation and disk **to see if the zfs pool or local-lvm(LVM-thin) makes difference**. And YES Both with loop and without loop multiple vms  => Disk resize fails with timeout.

1. Creating tasks: vms are created almost instantly => OK
2. TASK ERROR: command '/usr/bin/qemu-img resize -f ..... failed: got timeout
3. Terraform exits no errors.
4. I check the UI the disks are not resized (in the vm_disks datastore zfs pool) 
5. I apply terraform **second** time       ~ disk {
          ~ size              = 2 -> 16
            # (9 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
6. Almost instantly the 4 resize tasks went OK
7. I powered up one vm df -h showed 16 GB exactly as desired

Unfortunatelly I have to apply twice to correct the state and the px vm hardware disk props. and manually start them. 
If the state of the vm is started, the disks are not resized from **the first terraform apply** and my cloud init has to install some packages and if the disk id not resized, it ends up no space. 

**So you might be right there is something to do with zfs pool:**
with local-lvm: io delay spiked for short period of time around 40%
with zfs : io delay spiked for short around 60%

I will focus more on your suggestion about zfs. If I have updates will post.

**Comment by 10x4reply** [comment]
You were right there is something to do with zfs, or maybe because I stored the vms disk in "dir" type. Anyway here how I solve my problem.

I destroyed my zfs and created again here is my pve storage config /etc/pve/storage.cfg **(this time I use zfspool not dir type )**:
`
lvmthin: local-lvm
	thinpool data
	vgname pve
	content rootdir,images

dir: local
	path /var/lib/vz
	content backup,iso,vztmpl,images,rootdir,snippets
	prune-backups keep-all=1

# add mounts ANSIBLE MANAGED BLOCK
dir: zfs_dir_isos
        path /tank/zfs_dir_isos
        content iso
        shared 0

dir: zfs_dir_vm_disks
        path /tank/zfs_dir_vm_disks
        content images,vztmpl,snippets
        shared 0

dir: zfs_dir_backups
        path /tank/zfs_dir_backups
        content backup
        shared 0

zfspool: zfs_pool_vm_disks
         pool tank
         content images,rootdir
         mountpoint /tank
         sparse 1
# add mounts ANSIBLE MANAGED BLOCK
`
terraform:
`
....
      disk = {
        datastore_id = "zfs_pool_vm_disks"
        interface   = "virtio0"
        file_id     = "zfs_dir_isos:iso/jammy-server-cloudimg-amd64.img"
        discard     = "ignore"
        size        = 16
        file_format = "qcow2"
      }
  initialization {
.....
    datastore_id = "zfs_pool_vm_disks"
......
  }
`

parallelism=2 is best at least for me.

if I put it to 3 or 4 very frequently I get this error:

`
module.heye_vms_s3.proxmox_virtual_environment_vm.ubuntu_cloudinit_vms_s3["703"]: Creation complete after 45s [id=703]
module.heye_vms_s3.proxmox_virtual_environment_vm.ubuntu_cloudinit_vms_s3["700"]: Creation complete after 45s [id=700]
╷
│ Error: trying to acquire lock...
│ can't lock file '/var/lock/pve-manager/pve-storage-zfs_pool_vm_disks' - got timeout
│ 400 Parameter verification failed.
│ virtio0: invalid format - format error
│ virtio0.file: invalid format - unable to parse volume ID 'zfs_pool_vm_disks:'
│ 
│ 
│ qm set <vmid> [OPTIONS]
│ 
│ 
│   with module.heye_vms_s3.proxmox_virtual_environment_vm.ubuntu_cloudinit_vms_s3["702"],
│   on ../_modules/proxmox/vms/s3/compute.tf line 28, in resource "proxmox_virtual_environment_vm" "ubuntu_cloudinit_vms_s3":
│   28: resource "proxmox_virtual_environment_vm" "ubuntu_cloudinit_vms_s3" {
│ 
╵
╷
│ Error: trying to acquire lock...
│  OK
│ command 'zfs create -s -V 2306048k tank/vm-701-disk-0' failed: got timeout
│ 400 Parameter verification failed.
│ virtio0: invalid format - format error
│ virtio0.file: invalid format - unable to parse volume ID 'zfs_pool_vm_disks:'
│ 
│ 
│ qm set <vmid> [OPTIONS]
│ 
│ 
│   with module.heye_vms_s3.proxmox_virtual_environment_vm.ubuntu_cloudinit_vms_s3["701"],
│   on ../_modules/proxmox/vms/s3/compute.tf line 28, in resource "proxmox_virtual_environment_vm" "ubuntu_cloudinit_vms_s3":
`
**But I'am happy to run it with parallelism=2 , no errors, bulletproof :)**

Thank you very much for the support @bpg
