### ISSUE TITLE
Static IP address on Rocky Linux not being set

### ISSUE THREAD

**Issue by Nordal** [bpg/terraform-provider-proxmox#885]
**Describe the bug**
I use the following to set a static IP address deploying ubuntu with the proxmox_virtual_environment_vm resource:

```hcl
  initialization {
    datastore_id = "shared_storage"

    dns {
      servers = ["x.x.x.x", "x.x.x.x"]
        }

    ip_config {
      ipv4 {
        address = "x.x.x.x"
        gateway = "x.x.x.x"
      }
    }
```

The IP address is being set on Ubuntu 22.04, but not Rocky Linux 9. The DNS servers are being set though.

- Single or clustered Proxmox: Clustered
- Provider version (ideally it should be the latest version): 0.43.1
- Terraform version: 1.6.6
- OS (where you run Terraform from): Rocky Linux 8.9

**Comment by bpg** [comment]
Hi @Nordal 👋🏼

The `initialization` section of the template is an interface to Proxmox [cloud-init support](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_cloud_init) for VM configuration.
So, for the settings to be applied, the VM should be booted from a cloud-init -enabled image.

What image are you using?
After a quick look at the Rocky Linux [downloads](https://rockylinux.org/cloud-images), I think this one should be good (haven't tested myself)
<img width="713" alt="Screenshot 2024-01-14 at 5 18 21 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/f38bed00-7f75-4857-a9a1-e45182f9cdc6">

**Comment by Nordal** [comment]
Hi 
I am using the cloud-init ready rocky image. Also, DNS, hostname and user is created as expected.
But the anticipation is that this should work on any cloud-init-ready OS? (Also Windows with Cloudbase-init)?
When using the initialization section, am I then limited to the proxmox cloud-init options?

**Comment by Nordal** [comment]
A little follow-up
I did a test with a rocky8 image we have, and everything is working as expected, the rocky9 image is bad. 
Sorry for wasting your time.

BR Kasper

**Comment by bpg** [comment]
Alright! Closing the ticket then.
