### ISSUE TITLE
Support for "hardware mapping" as dedicated Terraform resource & data source

### ISSUE THREAD

**Issue by svengreb** [bpg/terraform-provider-proxmox#886]
First of all: Happy new year and thanks for this provider, this is definitely the best to automate everything for a home lab 😄

I recently set up a new [OPNsense](https://opnsense.org) router device ([Protectli VP2420](https://protectli.com/product/vp2420)) as an additional Proxmox node. The whole VM is automatically created via [Packer](https://www.packer.io) which results in a VM template in the end. The actual VM is managed with Terraform, using this provider. Since the [NIC](https://en.wikipedia.org/wiki/Network_interface_controller) that acts as the [WAN](https://en.wikipedia.org/wiki/Wide_area_network) in _OPNSense_ should only be used by this VM, and also to improve the performance, I pass it through as PCI device.

After revisiting my code after the holidays I noticed that [it is also possible to use a mapped resource](https://github.com/bpg/terraform-provider-proxmox/pull/500), but that there is no dedicated `proxmox_virtual_environment_cluster_hardware_mapping` resource but that this step must still be done manually (or automated through other ways that interact with the Proxmox API). Even though [the Proxmox API endpoint for hardware mappings](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/mapping/pci) is quite confusing I guess it might be nice if this provider could allow to manage this resource too.

I know that this would add another point in the "Known Issues" documentation since it is only possible to map a PCI/USB device using the `root` PAM account, but I guess this is still better than having to use my mouse to click it… because [IaC](https://en.wikipedia.org/wiki/Infrastructure_as_code) everything 😀

An alternative solution I've considered was to add this PCI passthrough mapping to my _Packer_ configuration, but that is not an ideal solution as it would bind it to the template which should rather act as a "one-time VM template" that gets deleted after (fully) cloning the VM with Terraform. This is also only a solution for me and does not allow to manage hardware mappings with Terraform in a general way.

Looking forward to hear your opinion! I'm also open to contribute this feature if you're busy, or support in any way to test it if you'd implement it yourself.

**Comment by bpg** [comment]
Hi @svengreb! 👋🏼

Thank you for the suggestion. I'm totally on board with configuring PCI mapping through a resource. Even though I don't play around with mapped devices in my home lab, I'd love some help getting this feature up and running!

If you (or anyone else! 😄) want to jump in and contribute, we've got two main things to tackle: setting up an API wrapper around the Proxmox REST API in /proxmox, and creating the resource itself in /fwprovider. The most recent resources/datasources were created using the [TF Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework), and you can use the code under /fwprovider as an example.

Feel free to drop any questions here or, better yet, open a pull request. Any contributions and insights will be much appreciated!

**Comment by svengreb** [comment]
Thanks for the tips to get started in this repository! 👍🏼
I've planned to implement it within the next weeks, but of course everyone who reads this ticket can pick it up.

**Comment by svengreb** [comment]
Just as a quick note: I started (and almost finished) the implementation while running it against my own _homelab_, just in case someone wanted to pick this issue up and we end up with duplicated PRs in the end 😄

**Comment by svengreb** [comment]
@bpg The PR is finally submitted: [#1213](https://github.com/bpg/terraform-provider-proxmox/pull/1213) 🎉

Took some time again because I refactored my first revision that used some generic code to "prevent" to create dedicated resources & data sources for each bus type (PCI and USB), but the Terraform _Plugin Framework_ is designed to enforce explicit and non-abstract implementations so I restored by previous implementation agin, which is the state that is now available in the PR.
