### ISSUE TITLE
SOCKS5 proxy support for SSH

### ISSUE THREAD

**Issue by laktosterror** [bpg/terraform-provider-proxmox#887]
**Is your feature request related to a problem? Please describe.**
My problem is that i need to use a SOCKS5 proxy to access my Proxmox host. 

I have tried setting environment variables like `http_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` which works, but only for the API calls. Not for the SSH connection needed by the `proxmox_virtual_environment_vm` resource. The request times out.

**Describe the solution you'd like**
If the provider could detect if for example environment variable `ALL_PROXY` was set and use the proxy specified, for the SSH connection, my problem would be solved.

Any way to be able to configure a proxy for the providers SSH connection would be fine.

**Describe alternatives you've considered**
I have found a workaround for now where i use SSH Tunneling to forward port 18006(->8006) and 10022(->22) to my Proxmox host. 

To create the SSH tunnel via the SOCKS5 proxy im using [ProxyChains](https://github.com/haad/proxychains).
This way i only need to create the SSH tunnel and then configure the provider to use `localhost` and forwarded ports instead of remote Proxmox IP and ports.

SSH tunnel:
`proxychains -f <path-to-proxychains.conf> ssh -fN -L 18006:<proxmox-ip>:8006 -L 10022:<proxmox-ip>:22 <pam-account>@<proxmox-ip>`

Terraform provider:
```terraform
provider "proxmox" {
  endpoint = "https://localhost:18006"
  username = var.virtual_environment_username
  password = var.virtual_environment_password
  insecure = true
  ssh {
    node {
       name    = "first-node"
       address = "localhost"
       port    = "10022"
    }
  }
}
```

**Additional context**
none

Thank you for your time and keep doing the lords work.

Take care

**Comment by bpg** [comment]
Hi @laktosterror! 👋🏼

The provider is using native golang ssh client for estabishing an SSH session, which seems to be pretty straightforward to adapt for using a SOCKS5 proxy -- I found this example after a quick googling: https://stackoverflow.com/questions/36102036/how-to-connect-remote-ssh-server-with-socks-proxy.
To pass the proxy address/credentials to the SSH client we can parse them from `http_proxy` env. var, or alternatively have them configured via provider's arguments / provider-specific env vars.

This doesn't look like lots work, so I may squeeze this feature in one of the upcoming releases.
And thank you for the kind words! ❤️

**Comment by laktosterror** [comment]
That's great to hear!

Now that i think about it, i'm wondering if having provider-specific env var would be more flexible.
Maybe one would need to use different proxies for different tools in ones workflow, having `http_proxy` set might force other tools to use specified proxy when they don't need it.

And kind words is the least i can do! 😄

**Comment by bpg** [comment]
@all-contributors please add @laktosterror for ideas
