### ISSUE TITLE
Incorrect indentations in terraform registry doc

### ISSUE THREAD

**Issue by zmingxie** [bpg/terraform-provider-proxmox#953]
**Describe the bug**

I'm trying to follow the documentation on [Terraform Registry](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container), and I found some sections aren't indented correctly. E.g. https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container#type
<img width="581" alt="image" src="https://github.com/bpg/terraform-provider-proxmox/assets/1136583/d5e44152-d36d-4d32-8460-ce81447bd7a8">

However, when I check the code here, it looks correct: https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/resources/virtual_environment_container.md?plain=1#L188-L197

It seems to be an issue with the doc-gen tool, but I'm not sure how the CI is set up for publishing this. The wrong indentations are making the documentation more difficult to follow.

Hopefully, we can find a quick fix for it. Thanks!

**To Reproduce**
- Already included within the description

**Comment by bpg** [comment]
Thanks @zmingxie, good catch!

I noticed wrong rendering in few other places as well.

The documentation pages are rendered from the markdown by Terraform Registry itself. And the syntax they are using is a bit different from a standard (or GitHub :) markdown. 

Based on testing via https://registry.terraform.io/tools/doc-preview it looks like lists should be using double indentation.

**Comment by zmingxie** [comment]
> Thanks @zmingxie, good catch!
> 
> I noticed wrong rendering in few other places as well.
> 
> The documentation pages are rendered from the markdown by Terraform Registry itself. And the syntax they are using is a bit different from a standard (or GitHub :) markdown.
> 
> Based on testing via https://registry.terraform.io/tools/doc-preview it looks like lists should be using double indentation.

Yes, I can reproduce the issue using the doc-preview too. However, I'm not sure what you mean by "double indentation" to fix it. Could you give me an example? I'm happy to review the doc and update all if you can show me the proper way. Thanks!

**Comment by bpg** [comment]
Thanks for offering help! ❤️ 

This change did the trick:
```diff
 ## Argument Reference
 
 - `clone` - (Optional) The cloning configuration.
-  - `datastore_id` - (Optional) The identifier for the target datastore.
-  - `node_name` - (Optional) The name of the source node (leave blank, if
-      equal to the `node_name` argument).
-  - `vm_id` - (Required) The identifier for the source container.
+    - `datastore_id` - (Optional) The identifier for the target datastore.
+    - `node_name` - (Optional) The name of the source node (leave blank, if
+        equal to the `node_name` argument).
+    - `vm_id` - (Required) The identifier for the source container.
 - `console` - (Optional) The console configuration.
-  - `enabled` - (Optional) Whether to enable the console device (defaults
-      to `true`).
-  - `mode` - (Optional) The console mode (defaults to `tty`).
-    - `console` - Console.
-    - `shell` - Shell.
-    - `tty` - TTY.
-  - `tty_count` - (Optional) The number of available TTY (defaults to `2`).
+    - `enabled` - (Optional) Whether to enable the console device (defaults
+        to `true`).
+    - `mode` - (Optional) The console mode (defaults to `tty`).
+        - `console` - Console.
+        - `shell` - Shell.
+        - `tty` - TTY.
+    - `tty_count` - (Optional) The number of available TTY (defaults to `2`).
```
