### ISSUE TITLE
Missing pool id forces replacement on Pool import

### ISSUE THREAD

**Issue by jtamas96** [bpg/terraform-provider-proxmox#963]
**Describe the bug**
After a pool is imported, the pool_id parameter is missing in the imported resource.
This forces a replacement on the first run.

**To Reproduce**

1. Create a pool on the proxmox server
2. Import it with terraform
3. Run terraform plan
4. Terraform wants to replace the pool

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

resource "proxmox_virtual_environment_pool" "import" {
  comment = "Managed by Terraform"
  pool_id = "import"
}

```

terraform import proxmox_virtual_environment_pool.import import

**Expected behavior**
After the import, the resource has the pool_id parameter, and Terraform doesn't want to replace it

**Comment by bpg** [comment]
@all-contributors please add @jtamas96 for bug
