### ISSUE TITLE
"permission denied" when proxmox_virtual_environment_file

### ISSUE THREAD

**Issue by kvangent** [bpg/terraform-provider-proxmox#986]
**Describe the bug**
I get `failed to create file /var/lib/vz/snippets/user-data.yml: permission denied` when creating a snippet from a local file using the enviroment_file resource. 

This very might possibly be a permissions issue -- I can't find much information from Proxmox on what permissions I need to create a snippet. However I followed the instructions to set up my terraform user has the ability to sudo without a password, and I can make the file with sudo. So it seems like the SSH agent isn't using sudo? 

**To Reproduce**

1. Create a user "terraform" with "Administrator" on '/'
2. Run `terraform apply` with the following resource:

```hcl

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "olympus"

  source_file {
    path = "cloud-init/user-data.yml"
  }
}

```

**Expected behavior**
I would expect the file to be created, or the error to tell me what I need to do to create the file. 

**Screenshots**

**Additional context**

- Single or clustered Proxmox: single
- Provider version (ideally it should be the latest version): 0.45.1
- Terraform version: 1.7.1
- OS (where you run Terraform from): Linux code-server 4.19.0-26-amd64 #1 SMP Debian 4.19.304-1 (2024-01-09) x86_64 GNU/Linux
- Debug logs (`TF_LOG=DEBUG terraform apply`):
```
2024-01-28T20:24:43.473Z [DEBUG] provider.terraform-provider-proxmox_v0.45.1: SSH connection established: @module=proxmox tf_provider_addr=registry.terraform.io/bpg/proxmox tf_resource_type=proxmox_virtual_environment_file @caller=github.com/bpg/terraform-provider-proxmox/proxmox/ssh/client.go:304 host=192.168.0.100:22 tf_mux_provider=tf5to6server.v5tov6Server tf_req_id=49d75294-ebb5-5684-d33b-5df59da70f22 tf_rpc=ApplyResourceChange user=terraform timestamp=2024-01-28T20:24:43.473Z
2024-01-28T20:24:43.825Z [ERROR] provider.terraform-provider-proxmox_v0.45.1: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=49d75294-ebb5-5684-d33b-5df59da70f22 @caller=github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/diag/diagnostics.go:62 @module=sdk.proto diagnostic_summary="failed to create file /var/lib/vz/snippets/user-data.yml: permission denied" tf_resource_type=proxmox_virtual_environment_file tf_rpc=ApplyResourceChange timestamp=2024-01-28T20:24:43.825Z
2024-01-28T20:24:43.879Z [ERROR] vertex "proxmox_virtual_environment_file.cloud_config" error: failed to create file /var/lib/vz/snippets/user-data.yml: permission denied
╷
│ Error: failed to create file /var/lib/vz/snippets/user-data.yml: permission denied
│ 
│   with proxmox_virtual_environment_file.cloud_config,
│   on files.tf line 12, in resource "proxmox_virtual_environment_file" "cloud_config":
│   12: resource "proxmox_virtual_environment_file" "cloud_config" {
│ 
╵
2024-01-28T20:24:43.926Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-01-28T20:24:43.926Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/bpg/proxmox/0.45.1/linux_amd64/terraform-provider-proxmox_v0.45.1 pid=11329
2024-01-28T20:24:43.927Z [DEBUG] provider: plugin exited
```

**Comment by bpg** [comment]
Hi @kvangent! 👋🏼

I might've missed that part in documentation. The snippets folder has root-only access by default, ao you can try changing it by
```
chgrp terraform /var/lib/vz/snippets
chmod 775 /var/lib/vz/snippets/
```
(assuming `terraform` is the user/group name you've created)

**Comment by pardon-denim** [comment]
Thanks! Just to let you know, I had the same issue and changed the permissions like you mentioned.

But I wonder if the sudo permission we set for non-root users should be able to handle that file creation/interaction so we don't have to change directory permissions.

**Comment by bpg** [comment]
Creating a snippet essentially is copying a file to the `/var/lib/vz/snippets/` folder using SSH and the permissions of the configured SSH user.

We could technically upload to, say, the `/tmp` folder and then do a `sudo cp` to get it into snippets. But with #993 in mind, I'd rather let the SSH user have access to snippets than allow any random cp operations.

**Comment by pardon-denim** [comment]
Oh ye, that makes total sense, thanks!

**Comment by kvangent** [comment]
Similar issue on my end -- I ended up manually setting permissions after creating the issue, but the missions have reset themselves. 

@bpg it seems like maybe we should be using SUDO to copy the file? And for permission of least permission they would need to add a line for each folder they want to be able to access with the SUDOer

**Comment by bpg** [comment]
Thanks for update @kvangent.

You're right, we can use something like this in shudders
```
terraform ALL=(root) NOPASSWD: /usr/bin/mv /tmp/tfpve/* /var/lib/vz/snippets/
``` 
and change the file upload flow to buffer snippets to /tmp first

**Comment by otopetrik** [comment]
Using `/tmp` with hardcoded `tfpve` string might have its own issues:
- possible name collisions when two snippets with the same filename name (each snippet in different datastore) are used at the very same time.
- existence of `tfpve` directory, what if it is owned by different user e.g. terraform1, terraform2,... for cases with multiple different non-root (but sudo-with-limitations capable) users. there could be security issues.

Go equivalent of something like:
`cat example.txt | ssh proxmoxhost 'sudo tee /var/lib/vz/snippets/example.txt >/dev/null'`
might work without using temporary directory, and `sudoers` would require something like this:
```
%pve-local-snippets ALL=(root) NOPASSWD: /usr/bin/tee /var/lib/vz/snippets/*
%pve-some-other-snippets ALL=(root) NOPASSWD: /usr/bin/tee /path/to/some/other/snippets/*
```
(non-root users' snippets could be limited to specific datastores, based on their PAM user groups)

**Comment by bpg** [comment]
@otopetrik `/tmp/tfpve/` is just a common parent folder, and I'm using a unique subfolder per upload, so I think there should be no collisions.

**Comment by rarrais** [comment]
Facing the exact same issue with Terraform versions 1.5.7 and 1.7.4 on MacOS, running the latest provider version (v0.47.0). 

It fails to create a directory at /tmp/tfpve for snippets with a user defined through the procedure at the [documentation](https://registry.terraform.io/providers/bpg/proxmox/0.47.0/docs), returning a permission denied error.

It works fine with Proxmox's root user, however.

**Comment by bpg** [comment]
HI @itrf98 👋🏼 

Please refer to the [0.48.0 release notes](https://github.com/bpg/terraform-provider-proxmox/releases/tag/v0.48.0) -- there was a breaking change related to the sudo permissions.
The [documentation](https://registry.terraform.io/providers/bpg/proxmox/latest/docs#ssh-user) has been updated as well.
