### ISSUE TITLE
docs: sudo permissions too extensive

### ISSUE THREAD

**Issue by Eusebius1920** [bpg/terraform-provider-proxmox#993]
Currently the docs of the provider say that you should add

```
terraform ALL=(ALL) NOPASSWD:ALL
```

to the sudoers file.

Looking at the code and trying myself it suffices to add something like this to the sudoers file:

```
terraform ALL=(root) NOPASSWD: /sbin/pvesm
terraform ALL=(root) NOPASSWD: /sbin/qm
terraform ALL=(root) NOPASSWD: /usr/bin/echo tfpve
```

with the principle of least privilege.

By changing the "is sudo installed"-check we could even get rid of the echo-line.

**Comment by bpg** [comment]
Thanks @Eusebius1920, good points!

Would you mind opening a PR to update that? 
The doc source is [here](https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/index.md?plain=1#L166). 
And you're right about the `sudo` check, I think it can be done using `/sbin/pvesm`, for example. So we just need the first 2 lines there.
